-- 回滚 loss_rate 双算修复（2026-08-11）。以表 owner（postgres）执行。
BEGIN;
ALTER TABLE cost_card_recipe DISABLE TRIGGER cost_card_recipe_protect;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=6 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=19 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=20 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=22 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=23 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=24 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=26 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=27 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=28 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=29 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=38 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=39 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=40 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=41 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=46 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=47 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=48 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=51 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=52 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=55 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=56 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=69 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=70 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=71 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=72 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=73 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=90 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=92 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=93 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=94 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=95 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=106 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=112 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=120 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=121 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=126 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=133 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=150 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=164 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=190 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=192 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=193 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=200 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=216 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=248 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=249 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=254 AND version=2;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=6;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=19;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=20;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=22;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=23;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=24;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=26;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=27;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=28;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=29;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=38;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=39;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=40;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=41;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=46;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=47;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=48;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=51;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=52;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=55;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=56;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=69;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=70;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=71;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=72;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=73;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=90;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=308;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=309;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=310;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=95;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=106;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=112;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=120;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=121;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=126;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=133;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=150;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=164;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=190;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=192;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=193;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=200;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=216;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=248;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=249;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=254;
ALTER TABLE cost_card_recipe ENABLE TRIGGER cost_card_recipe_protect;
COMMIT;