-- 回滚 ×1.7 第二批修复（2026-08-11）。以表 owner（postgres）执行。
BEGIN;
ALTER TABLE cost_card_recipe DISABLE TRIGGER cost_card_recipe_protect;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=1 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=2 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=3 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=4 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=5 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=7 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=8 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=9 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=10 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=11 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=12 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=13 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=14 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=15 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=16 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=17 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=18 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=21 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=25 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=30 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=31 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=32 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=33 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=36 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=37 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=42 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=43 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=44 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=45 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=49 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=50 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=53 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=54 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=57 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=58 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=59 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=60 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=61 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=67 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=74 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=75 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=76 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=77 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=78 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=79 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=80 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=81 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=82 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=83 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=84 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=85 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=86 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=87 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=88 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=89 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=91 AND version=2;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=6 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=19 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=20 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=22 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=23 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=24 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=26 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=27 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=28 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=29 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=38 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=39 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=40 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=41 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=46 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=47 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=48 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=51 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=52 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=55 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=56 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=69 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=70 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=71 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=72 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=73 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=90 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=65 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=66 AND version=3;
UPDATE cost_card_recipe SET status='archived', effective_to=CURRENT_DATE WHERE item_id=68 AND version=3;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=1;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=2;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=3;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=4;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=5;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=7;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=8;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=9;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=10;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=11;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=12;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=13;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=14;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=15;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=16;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=17;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=18;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=21;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=25;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=30;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=31;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=32;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=33;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=36;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=37;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=42;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=43;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=44;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=45;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=49;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=50;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=53;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=54;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=57;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=58;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=59;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=60;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=61;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=67;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=74;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=75;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=76;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=77;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=78;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=79;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=80;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=81;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=82;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=83;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=84;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=85;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=86;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=87;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=88;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=89;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=91;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=311;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=312;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=313;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=314;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=315;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=316;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=317;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=318;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=319;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=320;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=321;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=322;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=323;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=324;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=325;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=326;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=327;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=328;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=329;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=330;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=331;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=332;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=333;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=334;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=335;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=336;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=337;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=292;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=293;
UPDATE cost_card_recipe SET status='published', effective_to=NULL WHERE id=294;
ALTER TABLE cost_card_recipe ENABLE TRIGGER cost_card_recipe_protect;
COMMIT;