"use server";

import {
  getBusinessRulesFromDB,
  getPlanningRulesFromDB,
  getProducts,
  getStrategies,
  getSalesBaselines,
  getTimeslotSalesRecords,
  getOutOfStockRecords,
  saveOutOfStockRecords,
  deleteOutOfStockByDate,
  getContextEvents,
  addContextEvent,
  deleteContextEvent,
  getDailyReview,
  saveDailyReview,
  adoptDailyReview,
  getHolidays,
  addHoliday,
  deleteHoliday,
  getPromptSegments,
  upsertPromptSegment,
  deletePromptSegment,
  getPromptTemplates,
  upsertPromptTemplate,
  deletePromptTemplate,
  getEmpowermentEvents,
  addEmpowermentEvent,
  updateEmpowermentReview,
  deleteEmpowermentEvent,
  upsertDailyRevenue,
  getDailyRevenues,
  getProductSalesTrend,
  getDailySalesTotal,
  getFixedShipmentSchedules,
  updateFixedShipmentSchedule,
  deleteFixedShipmentSchedule,
  getProductAliases,
  updateProductAlias,
  deleteProductAlias,
  updateBusinessRule,
  importTimeslotSalesData,
  hasTimeslotSalesData,
  getProductConfigs,
  updateProductConfig,
  autoImportFromDataDir,
} from "@/modules/data/repositories/forecast.repository";
import {
  generateFullForecast,
  generateMonthlyTargetsWithCustomCoefficients,
  generateDailyTargets,
  generateProductSuggestions,
  generateTimeSlotSuggestions,
} from "@/modules/domain/forecast/forecast.service";

export {
  getBusinessRulesFromDB as getBusinessRules,
  getBusinessRulesFromDB,
  getPlanningRulesFromDB as getPlanningRules,
  getProducts,
  getStrategies,
  getSalesBaselines,
  getTimeslotSalesRecords,
  getOutOfStockRecords,
  saveOutOfStockRecords,
  deleteOutOfStockByDate,
  getContextEvents,
  addContextEvent,
  deleteContextEvent,
  getDailyReview,
  saveDailyReview,
  adoptDailyReview,
  getHolidays,
  addHoliday,
  deleteHoliday,
  getPromptSegments,
  upsertPromptSegment,
  deletePromptSegment,
  getPromptTemplates,
  upsertPromptTemplate,
  deletePromptTemplate,
  getEmpowermentEvents,
  addEmpowermentEvent,
  updateEmpowermentReview,
  deleteEmpowermentEvent,
  upsertDailyRevenue,
  getDailyRevenues,
  getProductSalesTrend,
  getDailySalesTotal,
  getFixedShipmentSchedules,
  updateFixedShipmentSchedule,
  deleteFixedShipmentSchedule,
  getProductAliases,
  updateProductAlias,
  deleteProductAlias,
  updateBusinessRule,
  importTimeslotSalesData,
  hasTimeslotSalesData,
  getProductConfigs,
  updateProductConfig,
  autoImportFromDataDir,
  generateFullForecast,
  generateMonthlyTargetsWithCustomCoefficients,
  generateDailyTargets,
  generateProductSuggestions,
  generateTimeSlotSuggestions,
};
