"""Supply chain, costing, and finance source-fact tables."""

from __future__ import annotations

from .model_types import F, ID, T


TABLES = [
    # ------------------------------------------------------------------
    # SCM: supplier, inventory, requirements, replenishment, PO, receipt
    # ------------------------------------------------------------------
    T(
        "scm_material_unit_conversion", "物料单位换算", "scm",
        "版本化维护某种原料或包材在采购包装、配方用量和库存基础单位之间的可审核换算。",
        "原料 × 起始单位 × 目标单位 × 生效区间一行", "供应链主数据审核",
        ("BakeryOps", "财务网站", "分析/BI"), "供应商规格、称量验证或批准的成本卡迁移", "REQUIRED",
        [
            ID("material_unit_conversion_id", "物料单位换算ID", "一条有生效期的物料单位换算稳定主键。"),
            ID("material_id", "原料ID", "该换算仅适用的统一原料或包材。", fk="scm_material.material_id"),
            ID("from_unit_id", "起始单位ID", "原始数量使用的受控单位。", fk="app_unit.unit_id"),
            ID("to_unit_id", "目标单位ID", "换算后数量使用的受控单位，通常为 material.base_unit_id。", fk="app_unit.unit_id"),
            F("conversion_factor", "换算系数", "numeric(24,12)", "一个 from_unit 等于多少个 to_unit。", "统一配方、报价、下单、收货和盘点的数量口径。", example="10000.000000000000", checks=("conversion_factor > 0",)),
            F("valid_from", "生效时间", "timestamptz", "该规格换算开始有效的时间。", "供应商改包装后旧事实仍使用旧系数。", example="2026-08-01T00:00:00+08:00"),
            F("valid_to", "失效时间", "timestamptz", "该换算停止适用的时间；仍有效时为空。", "定义无重叠的历史区间。", nullable=True, example="2026-12-01T00:00:00+08:00"),
            ID("source_system_id", "来源系统ID", "提供规格或换算证据的来源；纯人工称量可以为空。", fk="app_source_system.source_system_id", nullable=True),
            F("evidence", "换算证据", "jsonb", "包装净含量、称量记录、供应商规格或迁移来源。", "使换算可以复核，不依赖口头约定。", default="'{}'::jsonb", example='{"specification":"10 kg/case","net_weight_g":10000}'),
            F("status", "换算状态", "text", "PENDING、VERIFIED、REJECTED 或 RETIRED。", "只有 VERIFIED 且在生效期内的换算可进入正式成本和库存。", default="'PENDING'", example="VERIFIED", checks=("status IN ('PENDING','VERIFIED','REJECTED','RETIRED')",)),
            ID("verified_by_user_id", "核验账号", "确认该换算证据的应用账号。", fk="app_user.user_id", nullable=True),
            F("verified_at", "核验时间", "timestamptz", "换算进入 VERIFIED 的时间。", "证明何时获准用于正式计算。", nullable=True, example="2026-08-02T10:00:00+08:00"),
        ],
        standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN",
        uniques=(("material_id", "from_unit_id", "to_unit_id", "valid_from"),),
        checks=("from_unit_id <> to_unit_id", "valid_to IS NULL OR valid_to > valid_from", "status <> 'VERIFIED' OR verified_at IS NOT NULL"),
        exclusions=("NO_OVERLAP(material_id, from_unit_id, to_unit_id, tstzrange(valid_from, valid_to, '[)')) WHERE status = 'VERIFIED'",),
        retention="永久保留；新规格创建新生效区间，不覆盖旧系数",
        notes="kg↔g 等全局线性换算由 app_unit 管理；CASE、BAG 等与具体物料规格相关的换算必须在本表核验。PENDING 可补证据；VERIFIED、REJECTED 或 RETIRED 后冻结，包装变化新增生效区间。",
    ),
    T(
        "scm_supplier", "供应商主数据", "scm",
        "维护供应商稳定身份、采购币种、付款条件和状态。",
        "一个法律或经营供应商一行", "供应链主数据流程",
        ("BakeryOps", "财务网站", "分析/BI"), "采购合同和人工审核", "REQUIRED",
        [
            ID("supplier_id", "供应商ID", "跨报价、供应商SKU、PO、收货和财务核对的稳定身份。"),
            F("supplier_code", "供应商代码", "text", "企业内部唯一不可变供应商代码。", "导入和业务沟通使用。", unique=True, example="SUP-MY-0012"),
            F("supplier_name", "供应商名称", "text", "当前正式显示名称。", "展示和搜索，不作为跨表连接键。", example="ABC Ingredients Sdn Bhd"),
            F("legal_name", "法定名称", "text", "合同和发票使用的法定实体名称。", "财务核对和合同。", nullable=True, sensitive="internal", example="ABC Ingredients Sdn. Bhd."),
            F("registration_no", "注册编号", "text", "供应商公司注册或税务标识。", "供应商去重和合规。", nullable=True, sensitive="restricted", example="202001234567"),
            F("country_code", "国家代码", "char(2)", "供应商所在 ISO 国家代码。", "采购提前期和税务规则。", default="'MY'", example="MY"),
            F("default_currency", "默认币种", "char(3)", "报价和采购默认币种。", "解释价格。", default="'MYR'", example="MYR"),
            F("payment_terms_days", "付款账期天数", "integer", "标准付款到期天数。", "现金流计划。", nullable=True, example="30", checks=("payment_terms_days IS NULL OR payment_terms_days >= 0",)),
            F("lead_time_days", "默认提前期天数", "integer", "未在 SKU 层覆盖时的标准交货提前期。", "补货建议。", nullable=True, example="3", checks=("lead_time_days IS NULL OR lead_time_days >= 0",)),
            F("status", "供应商状态", "text", "PENDING、ACTIVE、SUSPENDED 或 RETIRED。", "停用供应商但保留采购历史。", default="'PENDING'", example="ACTIVE"),
            F("contact_data", "受限联系信息", "jsonb", "采购联系人和渠道的受限结构化信息。", "日常采购联系；普通分析不得读取。", default="'{}'::jsonb", sensitive="restricted", example='{"channel":"email"}'),
        ], standard="manual", uniques=(("supplier_code",),), retention="永久保留；停用不删除",
    ),
    T(
        "scm_supplier_item", "供应商商品", "scm",
        "以版本行维护供应商 SKU、对应统一物料、包装换算、MOQ和商业条件；规格变化新增版本，不再拆一张一对一映射表。",
        "供应商 × 外部SKU × 生效版本一行", "供应链主数据流程",
        ("BakeryOps", "财务网站", "分析/BI"), "供应商目录和人工审核", "REQUIRED",
        [
            ID("supplier_item_id", "供应商商品ID", "供应商 SKU 的一个有效版本身份。"),
            ID("supplier_id", "供应商ID", "SKU所属供应商。", fk="scm_supplier.supplier_id"),
            ID("supersedes_supplier_item_id", "被替代供应商商品ID", "本版本替代的上一版本；首次为空。", fk="scm_supplier_item.supplier_item_id", nullable=True),
            F("supplier_sku", "供应商SKU", "text", "供应商提供的稳定商品编号。", "与供应商共同唯一。", example="CHOCO70-5KG"),
            F("supplier_item_name", "供应商商品名称", "text", "报价或目录中的原始名称。", "保留来源证据。", example="Dark Chocolate 70% 5kg"),
            ID("order_unit_id", "订购单位ID", "PO 上使用的受控包装或计量单位。", fk="app_unit.unit_id"),
            ID("material_id", "原料ID", "本版本确认对应的统一原料；尚未完成映射时为空。", fk="scm_material.material_id", nullable=True),
            ID("material_unit_conversion_id", "物料单位换算ID", "把订购单位换算到物料基础单位的已核验规格；尚未核验时为空。", fk="scm_material_unit_conversion.material_unit_conversion_id", nullable=True),
            F("minimum_order_quantity", "最小订购量", "numeric(18,4)", "供应商要求的最小 order_unit 数量。", "补货取整。", nullable=True, example="2", checks=("minimum_order_quantity IS NULL OR minimum_order_quantity > 0",)),
            F("order_multiple", "订购倍数", "numeric(18,4)", "允许下单数量的倍数。", "把建议量转成可下单量。", default="1", example="1", checks=("order_multiple > 0",)),
            F("lead_time_days", "SKU提前期天数", "integer", "该 SKU 特有交货提前期。", "覆盖供应商默认值。", nullable=True, example="5", checks=("lead_time_days IS NULL OR lead_time_days >= 0",)),
            F("valid_from", "生效时间", "timestamptz", "该映射和包装规格开始可用于业务的时间。", "按下单或观察发生时点选择正确映射。", example="2026-08-01T00:00:00+08:00"),
            F("valid_to", "失效时间", "timestamptz", "该映射停止适用的时间上界；仍有效时为空。", "保留历史并允许相邻版本。", nullable=True, example="2026-12-01T00:00:00+08:00"),
            F("mapping_status", "映射状态", "text", "PENDING、CONFIRMED、REJECTED 或 RETIRED。", "只有 CONFIRMED 且时点有效的映射可进入正式补货、PO和成本。", default="'PENDING'", example="CONFIRMED", checks=("mapping_status IN ('PENDING','CONFIRMED','REJECTED','RETIRED')",)),
            F("evidence", "映射证据", "jsonb", "供应商规格、包装照片、称量、目录或迁移证据。", "证明不是按名称猜映射。", default="'{}'::jsonb", example='{"pack":"5kg/case","verified_weight_g":5000}'),
            ID("confirmed_by_user_id", "确认账号", "确认物料和包装规格的应用账号。", fk="app_user.user_id", nullable=True),
            F("confirmed_at", "确认时间", "timestamptz", "映射进入 CONFIRMED 的时间。", "审计何时获准使用。", nullable=True, example="2026-08-02T10:00:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN",
        uniques=(("supplier_id", "supplier_sku", "valid_from"),),
        checks=(
            "valid_to IS NULL OR valid_to > valid_from",
            "mapping_status <> 'CONFIRMED' OR (material_id IS NOT NULL AND confirmed_at IS NOT NULL)",
        ),
        exclusions=("NO_OVERLAP(supplier_id, supplier_sku, tstzrange(valid_from, valid_to, '[)')) WHERE mapping_status = 'CONFIRMED'",),
        retention="永久保留；映射或包装变化新增生效区间，不覆盖旧映射",
        notes="R6 将目录与其一对一物料/包装版本合并；同一 supplier_sku 规格变化时新增 supplier_item_id 并通过 supersedes 连接，禁止覆盖旧版本。每订购单位基础量不重复保存：order_unit_id 等于物料基础单位时派生为 1，否则由 material_unit_conversion_id 指向的已冻结系数计算。受控确认函数必须验证单位方向与 material_id 一致。",
    ),
    T(
        "scm_supplier_item_mapping_review", "供应商商品映射审核", "scm",
        "处理供应商 SKU 无法唯一映射到 material_id 的候选和证据。",
        "一个供应商SKU的一次待审核问题一行", "供应链主数据审核",
        ("BakeryOps", "财务网站"), "目录匹配质量检查", "REQUIRED",
        [
            ID("supplier_item_mapping_review_id", "审核ID", "一次供应商商品映射审核稳定主键。"),
            ID("supplier_item_id", "供应商商品ID", "待审核 SKU。", fk="scm_supplier_item.supplier_item_id"),
            ID("candidate_material_id", "候选原料ID", "候选统一原料；无候选为空。", fk="scm_material.material_id", nullable=True),
            F("reason_code", "进入队列原因", "text", "NO_CANDIDATE、MULTIPLE_CANDIDATES、UNIT_CONFLICT 或 SPEC_CONFLICT。", "决定审核重点。", example="UNIT_CONFLICT"),
            F("candidate_score", "候选得分", "numeric(5,4)", "匹配算法 0 至 1 得分。", "只用于排序。", nullable=True, example="0.8100"),
            F("evidence", "候选证据", "jsonb", "名称、规格、包装和供应商证据。", "禁止仅按名称自动确认。", default="'{}'::jsonb", example='{"pack":"5kg"}'),
            F("status", "审核状态", "text", "OPEN、APPROVED、REJECTED 或 DEFERRED。", "批准后创建新的有效供应商商品版本。", default="'OPEN'", example="OPEN"),
            ID("reviewed_by_user_id", "审核账号", "完成审核的账号。", fk="app_user.user_id", nullable=True),
            F("reviewed_at", "审核时间", "timestamptz", "审核进入终态时间。", "审计处理时长。", nullable=True, example="2026-08-10T09:00:00+08:00"),
            F("review_note", "审核说明", "text", "人工结论和必要说明。", "处理新建原料或拒绝映射。", nullable=True, example="包装单位需供应商确认"),
        ], standard="manual", mutation_policy="CONTROLLED_WORKFLOW", retention="永久保留审核结论",
        notes="OPEN 阶段允许补充候选证据；APPROVED、REJECTED 或 DEFERRED 后冻结结论。批准动作创建新的有效 scm_supplier_item 版本，不覆盖旧版本。",
    ),
    T(
        "scm_inventory_count", "库存盘点单", "scm",
        "记录某地点某时点的一次完整或抽样盘点及批准状态。",
        "地点 × 盘点时点 × 一次盘点一行", "仓库或门店库存流程",
        ("BakeryOps", "财务网站", "分析/BI"), "人工盘点、WMS或导入", "REQUIRED",
        [
            ID("inventory_count_id", "盘点单ID", "一次库存盘点稳定主键。"),
            ID("location_id", "地点ID", "被盘点门店、厨房或仓库。", fk="ops_location.location_id"),
            ID("source_system_id", "来源系统ID", "盘点来源；人工后台也作为来源注册。", fk="app_source_system.source_system_id"),
            F("count_code", "盘点单号", "text", "业务可读唯一盘点编号。", "现场沟通和幂等。", unique=True, example="CNT-PAV-20260831"),
            F("counted_at", "盘点时点", "timestamptz", "库存数量实际对应的时点。", "不能用导入时间代替。", example="2026-08-31T22:00:00+08:00"),
            F("count_type", "盘点类型", "text", "FULL、CYCLE、SPOT 或 IMPORTED_MONTH_END。", "解释覆盖范围。", example="FULL"),
            F("status", "盘点状态", "text", "DRAFT、SUBMITTED、APPROVED、REJECTED 或 SUPERSEDED。", "只有 APPROVED 进入库存余额。", example="APPROVED"),
            ID("approved_by_user_id", "批准账号", "批准盘点的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "盘点获批时间。", "审计。", nullable=True, example="2026-09-01T09:00:00+08:00"),
            F("note", "盘点说明", "text", "范围、异常或来源说明。", "解释抽样和差异。", nullable=True, example="月末全盘"),
        ], standard="manual", uniques=(("count_code",),),
    ),
    T(
        "scm_inventory_count_line", "库存盘点行", "scm",
        "保存盘点时每种原料的实盘数量、批次和效期。",
        "盘点单 × 原料 × 可选批号一行", "仓库或门店库存流程",
        ("BakeryOps", "财务网站", "分析/BI"), "盘点记录", "REQUIRED",
        [
            ID("inventory_count_line_id", "盘点行ID", "一条库存盘点行稳定主键。"),
            ID("inventory_count_id", "盘点单ID", "所属盘点单。", fk="scm_inventory_count.inventory_count_id"),
            ID("material_id", "原料ID", "被盘点统一原料。", fk="scm_material.material_id"),
            F("lot_code", "批号", "text", "批次追踪物料的供应商或内部批号。", "效期和召回追踪。", nullable=True, example="LOT-20260715-A"),
            F("expiry_date", "到期日期", "date", "该批原料到期日期。", "FEFO和报废预警。", nullable=True, example="2027-07-15"),
            F("counted_quantity", "实盘数量", "numeric(18,6)", "按 material.base_unit 归一化的盘点数量。", "库存余额事实。", example="12500", checks=("counted_quantity >= 0",)),
            F("raw_quantity", "来源数量", "numeric(18,6)", "盘点表原始数量。", "保留换算前证据。", nullable=True, example="2.5"),
            F("raw_unit_text", "来源原始单位文本", "text", "盘点来源原样提供的单位文本。", "在单位未映射时仍保留证据；不得直接参与计算。", nullable=True, example="kg"),
            ID("raw_unit_id", "原始单位ID", "原始单位确认后对应的受控单位；未映射时为空。", fk="app_unit.unit_id", nullable=True),
            ID("material_unit_conversion_id", "物料单位换算ID", "将原始单位换算到物料基础单位采用的已核验换算；全局单位换算可为空。", fk="scm_material_unit_conversion.material_unit_conversion_id", nullable=True),
            F("conversion_factor_snapshot", "换算系数快照", "numeric(24,12)", "本次盘点实际使用的 raw_unit_id 到基础单位系数。", "使历史盘点不受换算主数据后续版本变化影响。", nullable=True, example="1000.000000000000", checks=("conversion_factor_snapshot IS NULL OR conversion_factor_snapshot > 0",)),
            F("quality_status", "质量状态", "text", "COMPLETE、UNIT_UNMAPPED、MATERIAL_UNMAPPED 或 REJECTED。", "不完整行进入质量队列。", example="COMPLETE"),
        ], standard="immutable", uniques=(("inventory_count_id", "material_id", "lot_code"),),
        nulls_not_distinct_uniques=(("inventory_count_id", "material_id", "lot_code"),),
        notes="raw_quantity/raw_unit 保留来源原值，counted_quantity 是按当次批准换算与舍入规则形成、随后用于库存调整的正式基础单位数量；它属于获批盘点结果而非随当前换算表变化的缓存。conversion_factor_snapshot 让两者可核对。",
    ),
    T(
        "scm_inventory_movement", "库存移动单", "scm",
        "记录收货、领用、生产消耗、调整、报废或地点转移的一次库存事件。",
        "一个业务库存事件一行", "供应链库存服务",
        ("BakeryOps", "财务网站", "分析/BI"), "PO收货、生产、盘点调整或人工批准", "REQUIRED",
        [
            ID("inventory_movement_id", "库存移动ID", "一次库存移动稳定主键。"),
            ID("from_location_id", "发出地点ID", "库存减少地点；外部入库时为空。", fk="ops_location.location_id", nullable=True),
            ID("to_location_id", "接收地点ID", "库存增加地点；消耗或报废时为空。", fk="ops_location.location_id", nullable=True),
            F("movement_type", "移动类型", "text", "RECEIPT、TRANSFER、PRODUCTION_CONSUMPTION、ADJUSTMENT、WASTE 或 RETURN。", "决定数量正负和来源要求。", example="RECEIPT"),
            ID("goods_receipt_id", "收货单ID", "收货触发库存增加时对应的明确收货单。", fk="scm_goods_receipt.goods_receipt_id", nullable=True),
            ID("production_run_id", "生产运行ID", "生产领料或消耗触发库存减少时对应的明确生产运行；只有生产执行与采购库存两个扩展包同时启用后才允许写入并创建外键。", fk="ops_production_run.production_run_id", fk_activation="EXTENSION_PACK:PROCUREMENT_AND_INVENTORY+PRODUCTION_EXECUTION", nullable=True),
            ID("inventory_count_id", "盘点单ID", "批准盘点产生调整时对应的明确盘点单。", fk="scm_inventory_count.inventory_count_id", nullable=True),
            F("manual_reason_code", "人工事件原因代码", "text", "TRANSFER、WASTE、RETURN、EMERGENCY_ADJUSTMENT 或 OTHER 等受控原因。", "没有上游业务单据时仍说明为何发生，并由创建账号审计。", nullable=True, example="WASTE"),
            F("occurred_at", "发生时间", "timestamptz", "库存实际发生变化的时间。", "按时点重建库存。", example="2026-08-10T09:30:00+08:00"),
            F("business_date", "营业日期", "date", "库存事件归属营业日。", "与生产和销售连接。", example="2026-08-10"),
            F("status", "状态", "text", "DRAFT、POSTED、REVERSED 或 REJECTED。", "只有 POSTED 进入余额；更正用反向事件。", example="POSTED"),
            ID("reverses_movement_id", "冲销移动ID", "本事件冲销的原库存移动。", fk="scm_inventory_movement.inventory_movement_id", nullable=True),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN",
        checks=(
            "from_location_id IS NOT NULL OR to_location_id IS NOT NULL",
            "from_location_id IS NULL OR to_location_id IS NULL OR from_location_id <> to_location_id",
            "num_nonnulls(goods_receipt_id, production_run_id, inventory_count_id) <= 1",
            "movement_type <> 'RECEIPT' OR goods_receipt_id IS NOT NULL",
            "movement_type <> 'PRODUCTION_CONSUMPTION' OR production_run_id IS NOT NULL",
            "num_nonnulls(goods_receipt_id, production_run_id, inventory_count_id, manual_reason_code) >= 1",
        ),
        retention="永久保留；已过账事件不更新数量，错误用冲销事件",
        notes="删除 source_object_type/source_object_id 多态文本。DRAFT 可编辑；POSTED、REVERSED 或 REJECTED 后单头和行冻结。成品配送不直接作为物料库存来源，除非未来业务确认同一库存账确实管理成品。",
    ),
    T(
        "scm_inventory_movement_line", "库存移动行", "scm",
        "保存库存事件中每种原料、批号和数量。",
        "库存移动单 × 原料 × 可选批号一行", "供应链库存服务",
        ("BakeryOps", "财务网站", "分析/BI"), "对应业务来源行", "REQUIRED",
        [
            ID("inventory_movement_line_id", "库存移动行ID", "一条库存移动行稳定主键。"),
            ID("inventory_movement_id", "库存移动ID", "所属库存移动事件。", fk="scm_inventory_movement.inventory_movement_id"),
            ID("material_id", "原料ID", "发生数量变化的统一原料。", fk="scm_material.material_id"),
            F("lot_code", "批号", "text", "批次追踪物料的批号。", "库存和召回。", nullable=True, example="LOT-20260715-A"),
            F("expiry_date", "到期日期", "date", "该批物料到期日。", "FEFO。", nullable=True, example="2027-07-15"),
            F("quantity", "移动数量", "numeric(18,6)", "按基础单位记录的正数量；方向由单头 from/to 和类型决定。", "避免同一字段混用正负语义。", example="5000", checks=("quantity > 0",)),
            F("unit_cost", "移动单位成本", "numeric(18,6)", "移动时确认的基础单位成本；无法确认可为空。", "库存价值和差异分析。", nullable=True, example="0.085", checks=("unit_cost IS NULL OR unit_cost >= 0",)),
            F("currency", "币种", "char(3)", "unit_cost 币种。", "保证价值计算。", default="'MYR'", example="MYR"),
        ], standard="immutable", uniques=(("inventory_movement_id", "material_id", "lot_code"),),
        nulls_not_distinct_uniques=(("inventory_movement_id", "material_id", "lot_code"),),
    ),
    T(
        "scm_material_requirement_run", "原料需求计算运行", "scm",
        "把已发布生产计划按生效配方展开成原料需求，并冻结输入版本。",
        "地点 × 计划营业日 × 一次需求计算一行", "BakeryOps供应链任务",
        ("BakeryOps", "财务网站", "分析/BI"), "已发布预估单和配方版本", "REQUIRED",
        [
            ID("material_requirement_run_id", "需求运行ID", "一次原料需求计算稳定身份。"),
            ID("job_run_id", "任务运行ID", "执行计算的自动任务。", fk="app_job_run.job_run_id"),
            ID("location_id", "需求地点ID", "原料被消耗或需要备货的地点。", fk="ops_location.location_id"),
            ID("production_plan_version_id", "预估单版本ID", "需求采用的已发布计划版本。", fk="ops_production_plan_version.production_plan_version_id"),
            F("requirement_date", "需求日期", "date", "原料需可用的营业日期。", "补货和采购到货目标。", example="2026-08-10"),
            F("calculation_version", "计算版本", "text", "配方展开、损耗和单位换算算法版本。", "复现需求。", example="mrp-v2"),
            F("input_manifest", "输入清单", "jsonb", "计划版本、配方版本、单位换算和规则版本。", "完整血缘。", example='{"plan_version":"..."}'),
            F("status", "运行状态", "text", "RUNNING、SUCCEEDED、PARTIAL、FAILED 或 REJECTED。", "PARTIAL 不得自动形成正式 PO。", example="SUCCEEDED"),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL",
        notes="RUNNING 阶段只允许任务服务更新状态和运行元数据；进入 SUCCEEDED、PARTIAL、FAILED 或 REJECTED 后整次运行冻结，重算必须新增 run。",
    ),
    T(
        "scm_material_requirement_component", "原料需求组成血缘", "scm",
        "逐项保留需求运行中每个计划产品行展开出的一个原料贡献或一个明确质量阻断；原料总需求只从这些最细行汇总。",
        "需求运行 × 计划产品行 × 展开序号一行", "BakeryOps供应链任务",
        ("BakeryOps", "财务网站", "分析/BI"), "配方展开明细或质量阻断", "REQUIRED",
        [
            ID("material_requirement_component_id", "需求组成ID", "一条需求组成稳定主键。"),
            ID("material_requirement_run_id", "需求运行ID", "所属需求计算运行。", fk="scm_material_requirement_run.material_requirement_run_id"),
            ID("production_plan_line_id", "计划产品行ID", "产生需求的产品计划行。", fk="ops_production_plan_line.production_plan_line_id"),
            F("component_index", "展开序号", "integer", "同一运行和计划行内从 1 递增的展开项序号；质量阻断也占一行。", "稳定区分多个配方组件和无组件错误行。", example="1", checks=("component_index > 0",)),
            ID("material_id", "原料ID", "成功展开时得到的统一原料；缺配方或缺映射时为空。", fk="scm_material.material_id", nullable=True),
            ID("recipe_component_id", "配方组件ID", "实际采用的配方组件版本；缺配方或无法定位组件时为空。", fk="cost_card_recipe_component.recipe_component_id", nullable=True),
            F("material_quantity", "贡献原料数量", "numeric(18,6)", "该计划行和配方组件贡献的物料基础单位数量；质量阻断行为空。", "按运行和 material_id 汇总得到毛需求。", nullable=True, example="4800", checks=("material_quantity IS NULL OR material_quantity >= 0",)),
            F("quality_status", "质量状态", "text", "COMPLETE、MISSING_RECIPE、MISSING_MAPPING、UNIT_ERROR 或 REJECTED。", "任何非 COMPLETE 行都阻断该运行自动形成正式订货。", example="COMPLETE"),
            F("warning_detail", "质量说明", "jsonb", "缺配方、缺映射、单位错误或拒绝原因的结构化明细。", "即使无法产生 material_id 也保留问题事实。", default="'{}'::jsonb", example="{}"),
            F("calculation_detail", "计算细节", "jsonb", "批产量、净得率、损耗和单位换算。", "精确解释数量。", default="'{}'::jsonb", example='{"loss_rate":0.02}'),
        ], standard="immutable", uniques=(("material_requirement_run_id", "production_plan_line_id", "component_index"),),
        checks=("quality_status <> 'COMPLETE' OR (material_id IS NOT NULL AND recipe_component_id IS NOT NULL AND material_quantity IS NOT NULL)",),
        notes="scm_material_requirement_line 不再物理保存：gross_required_quantity、base_unit_id、quality_status 和组成行数都由本表与 material 主档派生。planned_product_quantity 也不复制，本行经 production_plan_line_id 读取已冻结计划量；只保存算法实际输出的 material_quantity、采用组件和阻断证据。",
    ),
    T(
        "scm_replenishment_run", "补货建议运行", "scm",
        "把原料需求、可用库存、在途、安全量、MOQ和提前期转换为建议订货。",
        "地点 × 需求日期 × 一次补货计算一行", "BakeryOps供应链任务",
        ("BakeryOps", "财务网站", "分析/BI"), "原料需求、库存、PO和供应商条件", "REQUIRED",
        [
            ID("replenishment_run_id", "补货运行ID", "一次补货计算稳定身份。"),
            ID("job_run_id", "任务运行ID", "执行计算的自动任务。", fk="app_job_run.job_run_id"),
            ID("location_id", "补货地点ID", "需要获得库存的地点。", fk="ops_location.location_id"),
            ID("material_requirement_run_id", "需求运行ID", "补货采用的原料需求计算。", fk="scm_material_requirement_run.material_requirement_run_id"),
            F("target_date", "目标日期", "date", "原料需要可用的日期。", "计算提前期。", example="2026-08-10"),
            F("calculation_version", "计算版本", "text", "安全量、在途和取整算法版本。", "复现建议。", example="replenishment-v2"),
            F("input_manifest", "输入清单", "jsonb", "库存盘点、已过账移动、在途 PO 和规则版本。", "解释建议差异。", example='{"inventory_count":"..."}'),
            F("status", "运行状态", "text", "RUNNING、SUCCEEDED、PARTIAL、FAILED 或 REJECTED。", "质量门禁。", example="SUCCEEDED"),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL",
        notes="RUNNING 阶段只允许任务服务更新；任何终态后冻结输入清单和结果，算法或输入变化必须新增 replenishment_run。",
    ),
    T(
        "scm_replenishment_line", "补货建议行", "scm",
        "保存原料建议量、批准量、库存构成、MOQ取整和调整原因。",
        "补货运行 × 原料 × 供应商商品版本候选一行", "BakeryOps计算；采购人员批准",
        ("BakeryOps", "财务网站", "分析/BI"), "补货计算和人工审批", "REQUIRED",
        [
            ID("replenishment_line_id", "补货行ID", "一条补货建议稳定主键。"),
            ID("replenishment_run_id", "补货运行ID", "所属补货计算。", fk="scm_replenishment_run.replenishment_run_id"),
            ID("material_id", "原料ID", "需要补货的统一原料。", fk="scm_material.material_id"),
            ID("supplier_item_id", "供应商商品ID", "建议采用的有效供应商SKU、物料和包装版本；未选定时为空。", fk="scm_supplier_item.supplier_item_id", nullable=True),
            F("required_quantity", "需求量", "numeric(18,6)", "来自原料需求的基础单位数量。", "补货公式起点。", example="12500"),
            F("available_quantity", "可用库存", "numeric(18,6)", "按 material.base_unit 冻结的批准盘点加已过账移动可用量。", "从需求中扣除。", example="4000"),
            F("in_transit_quantity", "在途数量", "numeric(18,6)", "按 material.base_unit 冻结的已批准且未完成收货 PO 数量。", "避免重复订货。", example="2000"),
            F("safety_quantity", "安全量", "numeric(18,6)", "按 material.base_unit 保存的批准规则额外缓冲量。", "应对波动。", default="0", example="1000"),
            F("suggested_quantity", "建议量", "numeric(18,6)", "公式计算并按包装/MOQ取整后的基础单位数量。", "采购审批建议。", example="8000", checks=("suggested_quantity >= 0",)),
            F("approved_quantity", "批准量", "numeric(18,6)", "采购人员最终按 material.base_unit 批准的数量。", "PO 行采用前再按 supplier_item 包装单位换算。", nullable=True, example="10000", checks=("approved_quantity IS NULL OR approved_quantity >= 0",)),
            F("adjustment_reason_code", "调整原因代码", "text", "MOQ、SUPPLIER_CAPACITY、MARKET_PRICE、STORAGE_LIMIT、JUDGEMENT 或 OTHER。", "说明批准量变化。", nullable=True, example="MOQ"),
            F("status", "审批状态", "text", "SUGGESTED、APPROVED、REJECTED 或 ORDERED。", "只有 APPROVED 可生成 PO。", default="'SUGGESTED'", example="APPROVED"),
            ID("approved_by_user_id", "批准账号", "批准订货量的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "批准订货量时间。", "审计和提前期。", nullable=True, example="2026-08-09T11:00:00+08:00"),
        ], standard="manual", mutation_policy="CONTROLLED_WORKFLOW", uniques=(("replenishment_run_id", "material_id", "supplier_item_id"),),
        nulls_not_distinct_uniques=(("replenishment_run_id", "material_id", "supplier_item_id"),),
        checks=(
            "status NOT IN ('APPROVED','ORDERED') OR (approved_quantity IS NOT NULL AND approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL)",
            "approved_quantity IS NULL OR approved_quantity = suggested_quantity OR adjustment_reason_code IS NOT NULL",
        ),
        notes="需求、库存、在途、安全量和 suggested_quantity 是该算法运行的冻结输入/输出，不是当前库存镜像；人工只填写批准量、原因和审批信息。delta_quantity 由 v_scm_replenishment_trace 计算。进入 ORDERED 后冻结。",
    ),
    T(
        "scm_purchase_order_revision", "采购订单版本", "scm",
        "直接保留某采购单号每次草稿、审批、发送、供应商确认或取消，不再另建空壳采购主单。",
        "采购单号 × 版本号一行", "采购流程；审批人改变状态",
        ("BakeryOps", "财务网站", "分析/BI"), "补货批准或上一版本", "REQUIRED",
        [
            ID("purchase_order_revision_id", "采购版本ID", "一版采购单稳定身份。"),
            F("purchase_order_code", "采购单号", "text", "跨版本稳定且不可复用的企业采购单号。", "与 revision_no 共同选择版本；供应商沟通和财务核对使用该代码。", example="PO-20260809-001"),
            ID("supplier_id", "供应商ID", "本版本下单供应商；变更供应商必须生成新版本。", fk="scm_supplier.supplier_id"),
            ID("deliver_to_location_id", "交付地点ID", "本版本要求送达的门店、厨房或仓库。", fk="ops_location.location_id"),
            ID("based_on_revision_id", "基础版本ID", "本版从哪一版本修改。", fk="scm_purchase_order_revision.purchase_order_revision_id", nullable=True),
            F("revision_no", "版本号", "integer", "采购单内递增版本。", "排序和供应商确认。", example="2", checks=("revision_no > 0",)),
            F("currency", "币种", "char(3)", "本版采购单全部行金额采用的 ISO 4217 币种。", "行单价和单据合计统一解释；不同币种必须拆成不同采购单。", default="'MYR'", example="MYR"),
            F("order_date", "下单日期", "date", "本版正式下单日期。", "采购期间归属。", nullable=True, example="2026-08-09"),
            F("expected_delivery_date", "预计到货日", "date", "供应商确认的预计交付日期。", "在途和缺货风险。", nullable=True, example="2026-08-11"),
            F("status", "版本状态", "text", "DRAFT、SUBMITTED、APPROVED、SENT、CONFIRMED、SUPERSEDED、REJECTED 或 CANCELLED。", "只有批准/发送版本可收货。", example="CONFIRMED"),
            F("subtotal_amount", "未税小计", "numeric(18,4)", "本版所有行未税金额之和。", "与行金额和财务核对。", example="1250.00"),
            F("tax_amount", "税额", "numeric(18,4)", "本版税额。", "财务核对。", default="0", example="0"),
            F("total_amount", "总金额", "numeric(18,4)", "本版最终应付总额。", "现金流和财务采购核对。", example="1250.00"),
            ID("approved_by_user_id", "批准账号", "批准本版本的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "本版本获批时间。", "审计。", nullable=True, example="2026-08-09T12:00:00+08:00"),
            F("sent_at", "发送时间", "timestamptz", "版本正式发送给供应商的时间。", "供应商响应和提前期。", nullable=True, example="2026-08-09T12:05:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("purchase_order_code", "revision_no"),),
        checks=("abs(total_amount - subtotal_amount - tax_amount) <= 0.01",),
        notes="R6 终审将 scm_purchase_order 合并到本表：没有业务事实应只引用抽象采购主单，收货必须指向供应商确认的具体版本。DRAFT 可编辑；提交审批后仅允许受控状态迁移。SENT、CONFIRMED、REJECTED、CANCELLED 或 SUPERSEDED 后本版本及其行冻结。已发送前的内容调整新增 revision_no；一旦任一版本已发送，变更供应商、交付地点或币种必须使用新 purchase_order_code，不能冒充原单修订。",
    ),
    T(
        "scm_purchase_order_line", "采购订单行", "scm",
        "保存采购版本中已确认的供应商商品版本、订购包装数量、单位价格和来源补货行。",
        "采购版本 × 供应商商品版本一行", "采购流程",
        ("BakeryOps", "财务网站", "分析/BI"), "批准补货或人工添加", "REQUIRED",
        [
            ID("purchase_order_line_id", "采购行ID", "一条采购版本行稳定主键。"),
            ID("purchase_order_revision_id", "采购版本ID", "所属采购订单版本。", fk="scm_purchase_order_revision.purchase_order_revision_id"),
            ID("supplier_item_id", "供应商商品ID", "采购采用的供应商SKU、物料和包装有效版本。", fk="scm_supplier_item.supplier_item_id"),
            ID("replenishment_line_id", "补货建议行ID", "该行来源的批准补货；纯人工采购可为空。", fk="scm_replenishment_line.replenishment_line_id", nullable=True),
            F("order_quantity", "订购数量", "numeric(18,4)", "按 supplier_item.order_unit 的数量。", "供应商订单事实。", example="2", checks=("order_quantity > 0",)),
            ID("order_unit_id", "订购单位ID", "本次下单采用的受控单位快照。", fk="app_unit.unit_id"),
            ID("material_unit_conversion_id", "物料单位换算ID", "本行将订购单位换算到基础单位采用的已核验规格。", fk="scm_material_unit_conversion.material_unit_conversion_id", nullable=True),
            F("unit_price", "订购单位价格", "numeric(18,6)", "每 order_unit 的确认价格。", "采购金额和价格观察。", example="625.00", checks=("unit_price >= 0",)),
            F("line_amount", "行金额", "numeric(18,4)", "order_quantity × unit_price 按批准舍入得到。", "与采购单小计核对。", example="1250.00", checks=("line_amount >= 0",)),
            F("note", "采购行备注", "text", "替代规格或供应商确认说明。", "必要例外。", nullable=True, example="同品牌新包装"),
        ], standard="immutable", uniques=(("purchase_order_revision_id", "supplier_item_id"),),
        notes="基础单位总数量不重复保存；由 order_quantity 与 material_unit_conversion_id 的冻结系数确定性派生。币种直接读取采购版本，不在行上复制。line_amount 仍保留，因为它是经批准并发送给供应商的舍入后单据行金额快照，必须由采购核对视图持续验证。",
    ),
    T(
        "scm_goods_receipt", "采购收货单", "scm",
        "记录针对供应商确认采购版本的一次实际到货、验收和入库。",
        "采购版本 × 一次收货一行", "仓库或门店收货流程",
        ("BakeryOps", "财务网站", "分析/BI"), "现场验收或WMS", "REQUIRED",
        [
            ID("goods_receipt_id", "收货单ID", "一次采购收货稳定身份。"),
            ID("purchase_order_revision_id", "采购版本ID", "供应商实际履约的 SENT 或 CONFIRMED 采购版本。", fk="scm_purchase_order_revision.purchase_order_revision_id"),
            ID("location_id", "收货地点ID", "实际收货地点。", fk="ops_location.location_id"),
            F("receipt_code", "收货单号", "text", "企业内部唯一可读收货编号。", "现场和财务沟通。", unique=True, example="GR-20260811-001"),
            F("supplier_delivery_note", "供应商送货单号", "text", "供应商提供的送货文件编号。", "发票和采购核对。", nullable=True, example="DO-99812"),
            F("received_at", "收货时间", "timestamptz", "货物实际到达并开始验收的时间。", "交付及时率和价格生效。", example="2026-08-11T10:30:00+08:00"),
            F("status", "收货状态", "text", "DRAFT、POSTED、PARTIAL、REJECTED 或 REVERSED。", "只有 POSTED/PARTIAL 生成库存移动。", example="POSTED"),
            ID("received_by_employment_id", "收货员工雇佣ID", "现场确认收货的员工。", fk="hr_employment.employment_id", nullable=True),
            F("note", "收货说明", "text", "异常、温度或文件说明。", "解释拒收和差异。", nullable=True, example="外箱一处破损"),
        ], standard="manual", uniques=(("receipt_code",),),
        notes="收货头直接引用具体 purchase_order_revision_id；实施迁移必须创建可延迟约束触发器，逐行确认 goods_receipt_line.purchase_order_line_id 所属版本等于本头 purchase_order_revision_id，禁止把不同采购版本混在一张收货单。为保持最小粒度，不在收货行重复保存 purchase_order_revision_id。",
    ),
    T(
        "scm_goods_receipt_line", "采购收货行", "scm",
        "保存每个采购行的实收、拒收、批号、效期和实际价格。",
        "收货单 × 采购行 × 可选批号一行", "仓库或门店收货流程",
        ("BakeryOps", "财务网站", "分析/BI"), "现场验收", "REQUIRED",
        [
            ID("goods_receipt_line_id", "收货行ID", "一条收货明细稳定主键。"),
            ID("goods_receipt_id", "收货单ID", "所属收货单。", fk="scm_goods_receipt.goods_receipt_id"),
            ID("purchase_order_line_id", "采购行ID", "对应采购订单行。", fk="scm_purchase_order_line.purchase_order_line_id"),
            ID("material_id", "原料ID", "实收统一原料，必须与供应商 SKU 已确认映射一致。", fk="scm_material.material_id"),
            F("lot_code", "批号", "text", "供应商批号。", "召回和效期。", nullable=True, example="LOT-20260801-A"),
            F("expiry_date", "到期日期", "date", "该批原料到期日。", "FEFO和验收。", nullable=True, example="2027-08-01"),
            F("received_order_quantity", "实收订购单位数", "numeric(18,4)", "按 PO order_unit 的实收数量。", "供应商履约。", example="2", checks=("received_order_quantity >= 0",)),
            F("accepted_base_quantity", "合格基础量", "numeric(18,6)", "按 material.base_unit 的合格入库量。", "库存增加。", example="9800", checks=("accepted_base_quantity >= 0",)),
            F("rejected_base_quantity", "拒收基础量", "numeric(18,6)", "按 material.base_unit 记录的验收不合格数量。", "供应商质量和采购差异。", default="0", example="200", checks=("rejected_base_quantity >= 0",)),
            F("actual_unit_price", "实际订购单位价", "numeric(18,6)", "收货或发票确认的每 order_unit 实际价格。", "形成市场采购价观察和成本来源。", example="630.00", checks=("actual_unit_price >= 0",)),
            F("currency", "币种", "char(3)", "实际价格币种。", "价格归一化。", default="'MYR'", example="MYR"),
            F("variance_reason", "数量价格差异原因", "text", "短收、拒收、涨价或替代规格原因。", "采购复盘。", nullable=True, example="PRICE_INCREASE"),
        ], standard="immutable", uniques=(("goods_receipt_id", "purchase_order_line_id", "lot_code"),),
        nulls_not_distinct_uniques=(("goods_receipt_id", "purchase_order_line_id", "lot_code"),),
    ),
    T(
        "scm_supplier_price_observation", "供应商市场价观察", "scm",
        "沉淀报价、PO或收货形成的原始和归一化采购价，供成本卡选择生效价格。",
        "供应商商品 × 观察时间 × 来源记录一行", "采购或收货流程",
        ("BakeryOps", "财务网站", "分析/BI"), "供应商报价、PO或实际收货", "REQUIRED",
        [
            ID("supplier_price_observation_id", "价格观察ID", "一条采购价观察稳定主键。"),
            ID("supplier_item_id", "供应商商品ID", "被观察的有效供应商 SKU、物料和包装版本。", fk="scm_supplier_item.supplier_item_id"),
            ID("source_system_id", "来源系统ID", "产生报价、PO、收货或人工市场检查的注册来源；人工后台也必须注册为来源。", fk="app_source_system.source_system_id"),
            F("source_record_id", "来源记录ID", "text", "来源中的报价编号、收货行号或人工检查幂等编号。", "与来源系统共同防止同一价格证据被重复导入。", nullable=True, sensitive="internal", example="QUOTE-20260811-17"),
            ID("goods_receipt_line_id", "收货行ID", "实际收货价来源时对应收货行；采购库存扩展包启用前必须为空且不创建该外键。", fk="scm_goods_receipt_line.goods_receipt_line_id", fk_activation="EXTENSION_PACK:PROCUREMENT_AND_INVENTORY", nullable=True),
            ID("purchase_order_line_id", "采购行ID", "PO确认价来源时对应采购行；采购库存扩展包启用前必须为空且不创建该外键。", fk="scm_purchase_order_line.purchase_order_line_id", fk_activation="EXTENSION_PACK:PROCUREMENT_AND_INVENTORY", nullable=True),
            F("observation_type", "观察类型", "text", "QUOTE、PO_CONFIRMED、RECEIPT_ACTUAL 或 MANUAL_MARKET_CHECK。", "区分价格证据强度。", example="RECEIPT_ACTUAL"),
            F("observed_at", "观察时间", "timestamptz", "报价、确认或收货价格发生时间。", "按时选择成本价。", example="2026-08-11T10:30:00+08:00"),
            F("raw_unit_price", "原始单价", "numeric(18,6)", "按供应商报价单位的原始价格。", "保留来源原值。", example="630.00", checks=("raw_unit_price >= 0",)),
            F("raw_price_unit_text", "来源价格单位文本", "text", "报价、PO或收货来源原样提供的价格单位文本。", "保留来源证据，不直接作为计算连接键。", example="case"),
            ID("raw_price_unit_id", "原始价格单位ID", "来源单位确认后对应的受控单位；未映射时为空。", fk="app_unit.unit_id", nullable=True),
            ID("material_unit_conversion_id", "物料单位换算ID", "将原始价格单位换算到物料基础单位所采用的已核验规格。", fk="scm_material_unit_conversion.material_unit_conversion_id", nullable=True),
            F("currency", "原始币种", "char(3)", "原始价格币种。", "汇率转换。", default="'MYR'", example="MYR"),
            F("fx_rate_to_myr", "兑MYR汇率", "numeric(18,8)", "观察时原币种 1 单位可兑换的 MYR 数量；原币种为 MYR 时可为空并按 1 计算。", "与原价和单位换算共同确定性派生 MYR 基础单价。", nullable=True, example="1.00000000", checks=("fx_rate_to_myr IS NULL OR fx_rate_to_myr > 0",)),
            F("fx_source_ref", "汇率来源引用", "text", "非 MYR 报价采用的汇率来源、日期和记录编号。", "证明汇率而不把计算结果重复落库。", nullable=True, sensitive="internal", example="BNM:2026-08-11:USD-MYR"),
            F("normalization_detail", "换算证据", "jsonb", "包装、单位、汇率日期及舍入规则的脱敏证据。", "复现归一化路径；数值输入仍使用结构化字段和单位换算外键。", default="'{}'::jsonb", example='{"rounding":"HALF_UP_8DP"}'),
            F("quality_status", "质量状态", "text", "VERIFIED、UNVERIFIED、UNIT_ERROR、FX_MISSING 或 REJECTED。", "只有符合政策的价格可进入成本卡。", example="VERIFIED"),
            ID("verified_by_user_id", "核验账号", "人工确认单位、币种或手工报价时的应用账号；自动收货价可以为空。", fk="app_user.user_id", nullable=True),
            F("verified_at", "核验时间", "timestamptz", "价格证据进入 VERIFIED 的时间。", "证明何时获准进入成本选择。", nullable=True, example="2026-08-11T11:00:00+08:00"),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL",
        uniques=(("source_system_id", "source_record_id"), ("goods_receipt_line_id", "observation_type"), ("purchase_order_line_id", "observation_type")),
        nulls_distinct_uniques=(("source_system_id", "source_record_id"), ("goods_receipt_line_id", "observation_type"), ("purchase_order_line_id", "observation_type")),
        checks=("num_nonnulls(goods_receipt_line_id, purchase_order_line_id, source_record_id) >= 1", "currency = 'MYR' OR fx_rate_to_myr IS NOT NULL", "quality_status <> 'VERIFIED' OR verified_at IS NOT NULL"),
        notes="normalized_price_myr 不作为独立事实保存；视图按 raw_unit_price × COALESCE(fx_rate_to_myr,1) ÷ 已核验单位换算系数确定性计算。supplier_item_id 已指向有效期版本；只有该版本 material_id、包装换算、单位和证据齐全时才允许 VERIFIED，该跨表门禁由受控写入函数执行。原始价格和来源键一经写入不得修改；正式价格更正追加新 observation。",
    ),

    # ------------------------------------------------------------------
    # COST CARD: recipe, effective price, immutable cost snapshots
    # ------------------------------------------------------------------
    T(
        "cost_card_recipe_version", "配方版本", "cost",
        "一行冻结一个配方代码版本的名称、产出对象、批产量、生效区间、售价参考和发布状态；不再为只有版本表引用的配方另建主档。",
        "配方代码 × 版本号一行", "财务成本卡网站",
        ("财务网站", "BakeryOps", "分析/BI"), "成本卡编辑和发布", "REQUIRED",
        [
            ID("recipe_version_id", "配方版本ID", "一版配方稳定身份。"),
            F("recipe_code", "配方代码", "text", "跨版本稳定且不可复用的企业配方代码。", "与 version_no 共同选择版本；跨表仍引用 recipe_version_id。", example="RCP-DARK-WELLINGTON"),
            F("recipe_name", "配方名称快照", "text", "本版本发布时的配方显示名称。", "名称变化不重写旧版本。", example="黑巧惠灵顿标准配方"),
            ID("output_product_id", "产出产品ID", "配方产出可售产品时填写。", fk="ops_product.product_id", nullable=True),
            ID("output_material_id", "产出半成品原料ID", "配方产出半成品时填写。", fk="scm_material.material_id", nullable=True),
            F("version_no", "版本号", "integer", "配方内递增版本。", "历史成本重现。", example="5", checks=("version_no > 0",)),
            F("batch_yield_quantity", "批产量", "numeric(18,6)", "一批配方产生的产出基础单位数量。", "将总原料成本换算到单位成本。", example="24", checks=("batch_yield_quantity > 0",)),
            ID("yield_unit_id", "产出单位ID", "批产量采用的受控单位；必须等于产出产品或半成品的基础单位。", fk="app_unit.unit_id"),
            F("reference_sale_price", "参考售价", "numeric(18,4)", "发布时用于成本率评审的参考售价；实际销售以POS事实为准。", "成本卡审核提示。", nullable=True, example="28.00", checks=("reference_sale_price IS NULL OR reference_sale_price >= 0",)),
            F("currency", "币种", "char(3)", "参考售价币种。", "解释参考售价。", default="'MYR'", example="MYR"),
            F("effective_from", "生效时间", "timestamptz", "配方开始用于新生产和成本快照的时间；仅历史迁移且尚未生效的 DRAFT 可为空。", "按交易日选择正确版本；不能为补齐历史而伪造日期。", nullable=True, example="2026-08-01T00:00:00+08:00"),
            F("effective_to", "失效时间", "timestamptz", "配方停止生效时间。", "保留历史。", nullable=True, example="2026-09-01T00:00:00+08:00"),
            F("status", "版本状态", "text", "DRAFT、PUBLISHED、ARCHIVED 或 REJECTED。", "只有 PUBLISHED 可进入物料需求和成本。", example="PUBLISHED"),
            F("notes", "配方说明", "text", "本版本由成本卡人员录入的操作说明、适用边界或迁移备注。", "承接旧配方 notes；不把稳定可计算字段塞进自由文本。", nullable=True, sensitive="internal", example="节日礼盒版本，仅 Pavilion 使用"),
            F("lock_version", "草稿并发版本", "integer", "DRAFT 每次受控修改递增的乐观锁版本；发布后冻结。", "避免两个编辑者互相覆盖尚未发布的配方草稿。", default="1", example="4", checks=("lock_version > 0",)),
            ID("approved_by_user_id", "批准账号", "批准配方版本的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "配方获批时间。", "审计。", nullable=True, example="2026-07-31T12:00:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("recipe_code", "version_no"),),
        checks=(
            "(output_product_id IS NOT NULL) <> (output_material_id IS NOT NULL)",
            "effective_to IS NULL OR effective_to > effective_from",
            "effective_from IS NOT NULL OR (status = 'DRAFT' AND effective_to IS NULL)",
        ),
        exclusions=("NO_OVERLAP(recipe_code, tstzrange(effective_from, effective_to, '[)')) WHERE status = 'PUBLISHED'",),
        notes="R6 终审将 cost_card_recipe 合并到本表：没有任何业务事实只引用配方主档，所有生产、需求和成本都必须引用具体 recipe_version_id；recipe_code 已足够跨版本分组。历史迁移中唯一尚未生效的 DRAFT 可以保留 effective_from=NULL；非 DRAFT 不允许缺失生效时间。DRAFT 可编辑，PUBLISHED、ARCHIVED 或 REJECTED 后冻结，修改只新增 version_no。",
    ),
    T(
        "cost_card_recipe_component", "配方原料组件", "cost",
        "逐项保存配方版本的统一原料用量、损耗和净得率。",
        "配方版本 × 原料 × 序号一行", "财务成本卡网站",
        ("财务网站", "BakeryOps", "分析/BI"), "成本卡配方输入", "REQUIRED",
        [
            ID("recipe_component_id", "配方组件ID", "一条配方用料稳定主键。"),
            ID("recipe_version_id", "配方版本ID", "所属配方版本。", fk="cost_card_recipe_version.recipe_version_id"),
            ID("material_id", "原料ID", "配方使用的统一原料或半成品。", fk="scm_material.material_id"),
            F("sequence_no", "顺序", "integer", "配方展示和执行顺序。", "稳定排序。", example="1", checks=("sequence_no > 0",)),
            F("input_quantity", "投料数量", "numeric(18,8)", "按 input_unit_id 的配方投料量。", "原始配方事实。", example="500", checks=("input_quantity > 0",)),
            ID("input_unit_id", "投料单位ID", "配方投料采用的受控单位。", fk="app_unit.unit_id"),
            ID("material_unit_conversion_id", "物料单位换算ID", "投料单位与物料基础单位不同时采用的已核验换算；全局单位换算可为空。", fk="scm_material_unit_conversion.material_unit_conversion_id", nullable=True),
            F("net_yield_rate", "净得率", "numeric(9,6)", "原料可用比例，0到1。", "处理清洗、去皮等损耗。", default="1", example="0.980000", checks=("net_yield_rate > 0 AND net_yield_rate <= 1",)),
            F("loss_rate", "额外损耗率", "numeric(9,6)", "生产过程额外损耗比例，0到1。", "物料需求放大和成本。", default="0", example="0.020000", checks=("loss_rate >= 0 AND loss_rate < 1",)),
            F("is_optional", "是否可选", "boolean", "组件是否仅在特定变体使用。", "可选组件必须有规则，不能默认计入。", default="false", example="false"),
            F("condition_schema_version", "使用条件结构版本", "text", "condition_rule 对应的固定 JSON Schema 版本；非可选组件为空。", "冻结允许的变体维度、操作符和取值类型。", nullable=True, example="recipe-condition-v1"),
            F("condition_rule", "使用条件", "jsonb", "可选组件按 condition_schema_version 校验的结构化条件；未知键拒绝。", "复现产品变体成本。", nullable=True, example='{"variant":"gift_pack"}'),
            F("note", "组件说明", "text", "只属于本配方组件的操作说明或迁移备注。", "承接旧 cost_card_recipe_item.notes，不把数量、单位或损耗塞进文本。", nullable=True, sensitive="internal", example="装饰用，最后一步加入"),
        ], standard="immutable", uniques=(("recipe_version_id", "sequence_no"),),
        checks=("(condition_rule IS NULL) = (condition_schema_version IS NULL)", "is_optional = (condition_rule IS NOT NULL)"),
        notes="base_unit_quantity 不重复保存；input_unit_id 等于物料基础单位时等于 input_quantity，否则由 material_unit_conversion_id 的冻结系数确定性派生。net_yield_rate 表示清洗/去皮后的可用比例，loss_rate 表示后续生产过程额外损耗，两者不是 1-x 的同一字段；可选组件必须按 condition_schema_version 经受控函数校验 condition_rule 并拒绝未知键；物料需求和成本视图按版本化公式顺序应用。",
    ),
    T(
        "cost_card_material_price", "成本采用价", "cost",
        "从供应商价格观察或人工批准值中选择某地点、原料的有效成本价格。",
        "地点或全局 × 原料 × 生效区间一行", "财务成本卡网站",
        ("财务网站", "BakeryOps", "分析/BI"), "收货价、PO价、报价或人工批准", "REQUIRED",
        [
            ID("material_price_id", "成本价格ID", "一条有效成本采用价稳定主键。"),
            ID("material_id", "原料ID", "被定价统一原料。", fk="scm_material.material_id"),
            ID("location_id", "地点ID", "地点特有价格；企业通用价为空。", fk="ops_location.location_id", nullable=True),
            ID("supplier_price_observation_id", "价格观察ID", "采用的供应商价格证据；纯人工价可为空。", fk="scm_supplier_price_observation.supplier_price_observation_id", nullable=True),
            F("price_myr_per_base_unit", "每基础单位MYR价格", "numeric(18,8)", "用于成本计算的归一化 MYR 单价。", "配方组件成本唯一价格输入。", example="0.06300000", checks=("price_myr_per_base_unit >= 0",)),
            F("price_source", "价格来源", "text", "RECEIPT_ACTUAL、PO_CONFIRMED、QUOTE、MIGRATED_MANUAL、MANUAL 或 FALLBACK。", "区分新供应链事实、现有成本卡启动价和无充分证据的兜底值。", example="RECEIPT_ACTUAL", checks=("price_source IN ('RECEIPT_ACTUAL','PO_CONFIRMED','QUOTE','MIGRATED_MANUAL','MANUAL','FALLBACK')",)),
            F("effective_from", "生效时间", "timestamptz", "价格开始用于成本快照的时间。", "按交易日选价。", example="2026-08-11T10:30:00+08:00"),
            F("effective_to", "失效时间", "timestamptz", "价格停止生效时间。", "保留采购价波动历史。", nullable=True, example="2026-08-20T00:00:00+08:00"),
            F("quality_status", "质量状态", "text", "VERIFIED、ESTIMATED、STALE、UNIT_ERROR 或 REJECTED。", "决定毛利是否可信。", example="VERIFIED"),
            F("evidence", "批准证据", "jsonb", "人工覆盖原因、汇率和验证记录。", "支持审计。", default="'{}'::jsonb", example='{"receipt_line":"..."}'),
            ID("approved_by_user_id", "批准账号", "批准该价格生效的账号。", fk="app_user.user_id", nullable=True),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN",
        uniques=(("material_id", "location_id", "effective_from"),),
        nulls_not_distinct_uniques=(("material_id", "location_id", "effective_from"),),
        checks=("effective_to IS NULL OR effective_to > effective_from",),
        exclusions=("NO_OVERLAP(material_id, COALESCE(location_id, NIL_UUID), tstzrange(effective_from, effective_to, '[)')) WHERE quality_status IN ('VERIFIED','ESTIMATED','STALE')",),
        notes="DRAFT 可补充证据；一旦质量状态进入可用或终态即冻结。迁移首日允许将现有 cost_card_item_price 作为 MIGRATED_MANUAL 启动价，但必须保留旧 price_id、原单位、换算和核验状态于 evidence；实际收货价出现后生成新生效区间，不原地改写历史。",
    ),
    # ------------------------------------------------------------------
    # FINANCE: independent source facts for reconciliation, not POS copies
    # ------------------------------------------------------------------
    T(
        "finance_import_batch", "财务导入批次", "finance",
        "记录财务模板、银行文件或人工数据每次导入的文件、期间、校验值和批准状态。",
        "来源文件或数据集 × 一次导入一行", "财务网站",
        ("财务网站", "分析/BI"), "批准的财务模板或文件", "REQUIRED",
        [
            ID("finance_import_batch_id", "财务批次ID", "一次财务导入稳定身份。"),
            ID("source_system_id", "来源系统ID", "财务数据来源。", fk="app_source_system.source_system_id"),
            ID("job_run_id", "任务运行ID", "自动导入任务；网页人工导入可为空。", fk="app_job_run.job_run_id", nullable=True),
            ID("scope_location_id", "批次范围地点ID", "文件只覆盖一个地点时填写；明确为多地点或公司级数据时为空。", fk="ops_location.location_id", nullable=True),
            ID("supersedes_finance_import_batch_id", "替代财务批次ID", "本批明确更正并替代的旧批次；首次导入为空。", fk="finance_import_batch.finance_import_batch_id", nullable=True),
            F("dataset_code", "数据集代码", "text", "SALES_DAILY、MONTHLY_COST、CASHFLOW 等类型。", "选择校验规则和目标表。", example="MONTHLY_COST"),
            F("source_layer", "来源层级", "text", "OPERATIONAL_TEMPLATE、MANAGEMENT_REPORT、POSTED_LEDGER 或 BANK_STATEMENT。", "区分运营原表、管理报表和已过账账簿，禁止把多个层级相加。", example="MANAGEMENT_REPORT", checks=("source_layer IN ('OPERATIONAL_TEMPLATE','MANAGEMENT_REPORT','POSTED_LEDGER','BANK_STATEMENT')",)),
            F("recognition_status", "财务确认状态", "text", "SOURCE_ONLY、APPROVED_FOR_RECONCILIATION、POSTED_ACCOUNTING 或 EXCLUDED。", "决定批次只能用于来源展示、可参与核对还是可作为已入账口径。", default="'SOURCE_ONLY'", example="APPROVED_FOR_RECONCILIATION", checks=("recognition_status IN ('SOURCE_ONLY','APPROVED_FOR_RECONCILIATION','POSTED_ACCOUNTING','EXCLUDED')",)),
            F("source_filename", "来源文件名", "text", "用户上传或同步文件的原始文件名。", "业务核对。", nullable=True, sensitive="internal", example="2026-07-Pavilion-PL.xlsx"),
            F("file_sha256", "文件校验值", "char(64)", "原始文件 SHA-256。", "阻止同一文件重复导入。", nullable=True, example="a91c...64位十六进制"),
            F("period_start", "期间开始", "date", "文件覆盖会计期间起点。", "定义影响范围。", example="2026-07-01"),
            F("period_end", "期间结束", "date", "文件覆盖会计期间终点。", "定义影响范围。", example="2026-07-31"),
            F("template_version", "模板版本", "text", "解析所依据的财务模板版本。", "防止旧模板误解析。", example="finance-template-v5"),
            F("loaded_row_count", "落库行数", "bigint", "导入成功或确认幂等的记录数。", "空批次和缺行监控。", default="0", example="125", checks=("loaded_row_count >= 0",)),
            F("status", "批次状态", "text", "UPLOADED、VALIDATED、APPROVED、LOADED、REJECTED 或 FAILED。", "只有 APPROVED/LOADED 才进入正式财务读取。", example="LOADED"),
            ID("approved_by_user_id", "批准账号", "批准财务导入的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "批次通过财务校验的时间。", "审计。", nullable=True, example="2026-08-05T10:00:00+08:00"),
            F("validation_result", "校验结果", "jsonb", "模板结构、合计、重复和映射检查结果。", "明确拒绝或警告原因。", default="'{}'::jsonb", example='{"totals_match":true}'),
        ], standard="manual", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL", uniques=(("dataset_code", "file_sha256"),),
        nulls_distinct_uniques=(("dataset_code", "file_sha256"),), checks=("period_end >= period_start", "supersedes_finance_import_batch_id IS NULL OR supersedes_finance_import_batch_id <> finance_import_batch_id"),
        notes="status 表示导入技术流程，recognition_status 表示财务可用层级。治理视图同一数据集/地点/期间只选一个获准批次；被 supersedes 的批次仍保留但不得重复汇总。",
    ),
    T(
        "finance_sales_daily", "财务日销售事实", "finance",
        "保存财务模板口径的门店日销售，保持与 POS 事实独立用于核对。",
        "财务批次 × 地点 × 日期一行", "财务网站",
        ("财务网站", "分析/BI"), "财务销售模板", "REQUIRED",
        [
            ID("finance_sales_daily_id", "财务日销售ID", "一条财务日销售稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生该事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            ID("location_id", "地点ID", "销售所属统一门店。", fk="ops_location.location_id"),
            F("business_date", "营业日期", "date", "财务表认定的销售日期。", "与 POS 日销售核对。", example="2026-07-20"),
            F("gross_sales", "财务流水", "numeric(18,4)", "财务模板口径流水金额；模板未提供时为空。", "独立来源核对；NULL 不得当成 0。", nullable=True, example="51000.00", checks=("gross_sales IS NULL OR gross_sales >= 0",)),
            F("discount_amount", "财务折扣", "numeric(18,4)", "财务模板直接提供或由模板明确组成项归一化的折扣金额；模板未提供时为空。", "净额和折扣率；NULL 表示未知，不表示没有折扣。", nullable=True, example="1000.00", checks=("discount_amount IS NULL OR discount_amount >= 0",)),
            F("net_sales", "财务实收", "numeric(18,4)", "财务模板口径实收或收入；模板未提供时为空。", "与 POS 净销售比较，不自动覆盖；NULL 不得当成 0。", nullable=True, example="50000.00", checks=("net_sales IS NULL OR net_sales >= 0",)),
            F("order_count", "财务订单数", "integer", "财务来源独立提供的订单或账单数量；来源不含该列时为空。", "保留历史财务导入中的账单观察并派生财务客单价；不得从 POS 反填。", nullable=True, example="805", checks=("order_count IS NULL OR order_count >= 0",)),
            F("currency", "币种", "char(3)", "金额币种。", "保证核对。", default="'MYR'", example="MYR"),
            F("quality_status", "质量状态", "text", "COMPLETE、PARTIAL、UNMAPPED_LOCATION 或 REJECTED。", "不完整数据不得伪装正式财务事实。", example="COMPLETE"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "location_id", "business_date"),),
        notes="财务日销售是与 POS 独立的来源观察。gross_sales、discount_amount、net_sales、order_count 未提供时保持 NULL；只有来源明确报告零值才写 0。折扣率和平均客单价从本表分子分母派生，不重复存储。",
    ),
    T(
        "finance_item_sales_monthly", "财务单品月销售", "finance",
        "保存财务模板中月度单品数量和金额，作为 POS 聚合的独立核对来源。",
        "财务批次 × 地点 × 月份 × 来源商品一行", "财务网站",
        ("财务网站", "分析/BI"), "财务单品销售模板", "REQUIRED",
        [
            ID("finance_item_sales_monthly_id", "财务单品月销售ID", "一条月单品销售稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            ID("location_id", "地点ID", "销售所属门店。", fk="ops_location.location_id"),
            ID("product_id", "产品ID", "确认映射后的统一产品；未确认时为空并进入质量队列。", fk="ops_product.product_id", nullable=True),
            F("business_month", "业务月份", "date", "用月份第一日表示的会计月。", "月度核对。", example="2026-07-01"),
            F("source_item_name", "来源商品名称", "text", "财务模板原始商品名称。", "保留证据，禁止直接按名连接。", example="黑巧惠灵顿"),
            F("quantity", "财务销量", "numeric(18,4)", "财务模板口径月销量。", "与 POS 月聚合比较。", example="850"),
            F("source_unit", "来源数量单位", "text", "财务模板原样提供的销量单位；模板未提供时为空。", "单位未确认时只能在同一来源商品内比较数量，不能直接换算到 product.base_unit。", nullable=True, example="ea"),
            F("sales_amount", "财务销售额", "numeric(18,4)", "财务模板口径单品销售额。", "与 POS 产品销售核对。", example="23800.00"),
            F("currency", "币种", "char(3)", "金额币种。", "保证核对。", default="'MYR'", example="MYR"),
            F("quality_status", "质量状态", "text", "COMPLETE、UNMAPPED_PRODUCT、PARTIAL 或 REJECTED。", "未映射行不进入产品级正式分析。", example="COMPLETE"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "location_id", "business_month", "source_item_name"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
    ),
    T(
        "finance_monthly_cost_line", "财务月成本费用行", "finance",
        "用统一粒度保存材料、人工、仓运和期间费用，同时保留类别和组织来源。",
        "财务批次 × 地点 × 月份 × 成本域 × 类别 × 子类 × 组织或来源一行", "财务网站",
        ("财务网站", "分析/BI"), "利润表、费用表和人工成本模板", "REQUIRED",
        [
            ID("finance_monthly_cost_line_id", "月成本行ID", "一条财务月成本稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生该成本事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            F("source_row_ref", "来源行定位符", "text", "导入文件中的稳定行定位，例如工作表名与原始行号或来源记录号。", "与批次共同实现重跑幂等，同时允许两条内容完全相同但位置不同的真实行并存。", example="P&L!R42"),
            F("source_row_fingerprint", "来源行内容指纹", "char(64)", "按版本化规范对来源行原值计算的 SHA-256。", "检测同一来源位置内容是否变化；不单独充当业务身份或去重键。", example="7ac4...64位十六进制"),
            ID("location_id", "地点ID", "成本归属地点。", fk="ops_location.location_id"),
            F("business_month", "业务月份", "date", "月份第一日。", "月度损益连接。", example="2026-07-01"),
            F("cost_domain", "成本域", "text", "MATERIAL、LABOR、LOGISTICS、OPERATING_EXPENSE 或 OTHER。", "保持不同成本口径可区分。", example="LABOR"),
            F("category_code", "类别代码", "text", "标准成本类别代码。", "期间费用和汇总口径。", example="WAGES"),
            F("subcategory_code", "子类代码", "text", "更细成本项目；无子类为空。", "费用穿透。", nullable=True, example="LOCAL_STAFF_WAGES"),
            F("organization_code", "组织代码", "text", "成本模板中的组织、资金来源或用工组织。", "保留原财务拆分。", nullable=True, example="MY_OPERATIONS"),
            F("source_label", "来源标签", "text", "模板原始类别或支付渠道文本。", "核对导入但不作为标准口径。", nullable=True, example="银行流水"),
            F("accounting_treatment", "会计处理", "text", "RAW_SOURCE、RECOGNIZED_EXPENSE、ACCRUAL、REVERSAL 或 EXCLUDED。", "防止来源明细、已确认费用、计提和冲销在同一汇总中重复计算。", example="RECOGNIZED_EXPENSE", checks=("accounting_treatment IN ('RAW_SOURCE','RECOGNIZED_EXPENSE','ACCRUAL','REVERSAL','EXCLUDED')",)),
            F("amount", "金额", "numeric(18,4)", "该成本行金额。", "损益和财务核对。", example="12500.00"),
            F("currency", "币种", "char(3)", "金额币种。", "保证正确汇总。", default="'MYR'", example="MYR"),
            F("quality_status", "质量状态", "text", "COMPLETE、UNCLASSIFIED、PARTIAL 或 REJECTED。", "未归类费用阻断正式利润表。", example="COMPLETE"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "source_row_ref"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
    ),
    T(
        "finance_cashflow_line", "财务现金流行", "finance",
        "保存门店月度现金流项目和金额，不与收入或利润混用。",
        "财务批次 × 地点 × 月份 × 现金流项目一行", "财务网站",
        ("财务网站", "分析/BI"), "现金流模板", "REQUIRED",
        [
            ID("finance_cashflow_line_id", "现金流行ID", "一条现金流事实稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生该事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            ID("location_id", "地点ID", "现金流归属地点。", fk="ops_location.location_id"),
            F("business_month", "业务月份", "date", "月份第一日。", "月度现金流。", example="2026-07-01"),
            F("cashflow_code", "现金流项目代码", "text", "OPENING_BALANCE、CASH_IN、CASH_OUT、REFUND、BANK_DEPOSIT 或 CLOSING_BALANCE。", "稳定现金流口径。", example="CASH_IN"),
            F("amount", "金额", "numeric(18,4)", "该项目月度金额。", "现金余额桥接。", example="50000.00"),
            F("currency", "币种", "char(3)", "金额币种。", "正确汇总。", default="'MYR'", example="MYR"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "location_id", "business_month", "cashflow_code"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
    ),
    T(
        "finance_order_logistics_line", "财务物流订货行", "finance",
        "保留财务模板中包含订货、付款、发货、到港、交付和入库日期的历史物流行。",
        "财务批次 × 来源订货单 × 来源商品行一行", "财务网站",
        ("财务网站", "供应链", "分析/BI"), "财务库存/物流模板", "REQUIRED",
        [
            ID("finance_order_logistics_line_id", "物流订货行ID", "一条历史物流行稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生该事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            F("source_row_ref", "来源行定位符", "text", "导入文件中的稳定行定位，例如工作表名与原始行号或来源记录号。", "与批次共同实现重跑幂等，同时保留内容相同的真实重复行。", example="Logistics!R18"),
            F("source_row_fingerprint", "来源行内容指纹", "char(64)", "按版本化规范对来源行原值计算的 SHA-256。", "检测同一来源位置内容变化，不作为唯一业务身份。", example="7ac4...64位十六进制"),
            ID("location_id", "地点ID", "订货服务地点。", fk="ops_location.location_id"),
            ID("supplier_id", "供应商ID", "确认映射的供应商；未知为空。", fk="scm_supplier.supplier_id", nullable=True),
            ID("material_id", "原料ID", "确认映射的原料；未知为空。", fk="scm_material.material_id", nullable=True),
            F("source_order_no", "来源订单号", "text", "财务模板中的订货单编号。", "历史单据核对。", example="CN-PO-202606-18"),
            F("source_supplier_name", "来源供应商名称", "text", "财务物流模板中的供应商名称原文。", "在 supplier_id 尚未确认时保留来源证据；不得按名称自动建立供应商身份。", nullable=True, example="Supplier Sdn Bhd"),
            F("source_item_name", "来源商品名称", "text", "模板原始商品名称。", "保留证据。", example="巧克力原料"),
            F("source_specification", "来源规格", "text", "财务物流模板中的商品规格原文。", "无损承接 finance_orders.spec，并辅助物料与供应商商品映射；不作为统一单位。", nullable=True, example="5kg/case"),
            F("source_category", "来源类别", "text", "财务物流模板中的商品类别原文。", "保留历史分类证据；正式分析类别必须通过治理映射，不按名称直连。", nullable=True, example="进口原料"),
            F("source_purchase_type", "来源采购类型", "text", "财务物流模板 ptype 的原始值。", "在来源词表未确认前原样保留；不得猜成 LOCAL/IMPORT 后覆盖原值。", nullable=True, example="IMPORT"),
            F("order_date", "订货日期", "date", "财务模板认定的下单日期。", "会计期间归属。", example="2026-06-12"),
            F("payment_date", "付款日期", "date", "实际付款日期。", "现金流。", nullable=True, example="2026-06-13"),
            F("shipped_date", "发货日期", "date", "供应商发货日期。", "物流提前期。", nullable=True, example="2026-06-15"),
            F("arrived_port_date", "到港日期", "date", "跨境采购到港日期。", "跨境物流。", nullable=True, example="2026-06-25"),
            F("delivered_date", "交付日期", "date", "送达本地地点日期。", "交付及时率。", nullable=True, example="2026-06-28"),
            F("warehoused_date", "入库日期", "date", "财务模板认定的入库日期。", "库存期间。", nullable=True, example="2026-06-28"),
            F("quantity", "数量", "numeric(18,4)", "来源订货数量。", "历史采购分析。", nullable=True, example="10"),
            F("source_unit", "来源数量单位", "text", "财务模板原样提供的订货单位；未提供时为空。", "解释数量并辅助与供应商包装单位映射。", nullable=True, example="case"),
            F("source_volume", "来源体积数值", "numeric(18,6)", "财务物流模板 volume 的原始数值；来源为空时保持为空。", "只为无损迁移和来源核对保留；旧模板没有证明单位，确认单位前不得与其他行求和或用于运费计算。", nullable=True, example="1.250000", notes="实施门禁：必须向财务模板所有者确认 volume 是单件体积、总体积还是包装容量及其单位；未确认时 quality_status 不得为 COMPLETE。"),
            F("amount", "金额", "numeric(18,4)", "来源订货行金额。", "采购核对。", nullable=True, example="5000.00"),
            F("currency", "币种", "char(3)", "金额币种。", "正确汇总。", default="'MYR'", example="MYR"),
            F("quality_status", "质量状态", "text", "COMPLETE、UNMAPPED_SUPPLIER、UNMAPPED_MATERIAL、PARTIAL 或 REJECTED。", "未映射历史行不伪装成 SCM PO。", example="PARTIAL"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "source_row_ref"),),
    ),
    T(
        "finance_inventory_snapshot_line", "财务月库存快照行", "finance",
        "保存财务模板月末现存、在途、用量、规格和采购类型。",
        "财务批次 × 地点 × 月份 × 来源物料一行", "财务网站",
        ("财务网站", "供应链", "分析/BI"), "财务库存模板", "REQUIRED",
        [
            ID("finance_inventory_snapshot_line_id", "财务库存快照ID", "一条财务库存快照稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生该事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            F("source_row_ref", "来源行定位符", "text", "导入文件中的稳定行定位，例如工作表名与原始行号或来源记录号。", "与批次共同实现重跑幂等，同时保留内容相同的真实重复行。", example="Inventory!R33"),
            F("source_row_fingerprint", "来源行内容指纹", "char(64)", "按版本化规范对来源行原值计算的 SHA-256。", "检测同一来源位置内容变化，不作为唯一业务身份。", example="7ac4...64位十六进制"),
            ID("location_id", "地点ID", "库存归属地点。", fk="ops_location.location_id"),
            ID("material_id", "原料ID", "确认映射的统一原料；未知为空。", fk="scm_material.material_id", nullable=True),
            F("business_month", "业务月份", "date", "月末快照所属月份第一日。", "与 SCM 盘点核对。", example="2026-07-01"),
            F("source_item_name", "来源物料名称", "text", "财务模板原始名称。", "保留证据。", example="Dark Chocolate 70%"),
            F("specification", "规格", "text", "模板中的包装规格。", "辅助映射和采购分析。", nullable=True, example="5kg/case"),
            F("source_category", "来源类别", "text", "财务库存模板中的类别原文。", "无损承接 finance_stock.category；正式类别需治理后再分析。", nullable=True, example="巧克力"),
            F("on_hand_quantity", "现存数量", "numeric(18,6)", "模板口径月末现存量。", "与 SCM 批准盘点独立核对。", nullable=True, example="12"),
            F("in_transit_quantity", "在途数量", "numeric(18,6)", "模板口径在途量。", "与 SCM 开放 PO 核对。", nullable=True, example="4"),
            F("monthly_usage_quantity", "当月用量", "numeric(18,6)", "模板口径当月耗用。", "与生产需求和库存移动核对。", nullable=True, example="18"),
            F("source_unit", "来源单位", "text", "财务模板数量单位。", "解释数量。", nullable=True, example="case"),
            F("source_unit_volume", "来源单位容量数值", "numeric(18,6)", "财务库存模板 unit_volume 的原始数值；来源为空时保持为空。", "保留旧模板包装换算线索；因旧字段没有单位，确认语义前不得作为正式换算系数。", nullable=True, example="5.000000", notes="只有在来源合同确认其量纲和单位，并建立 scm_material_unit_conversion 后，才能用于正式数量换算。"),
            F("purchase_type", "采购类型", "text", "LOCAL、IMPORT 或 UNKNOWN。", "采购结构分析。", nullable=True, example="LOCAL"),
            F("quality_status", "质量状态", "text", "COMPLETE、UNMAPPED_MATERIAL、UNIT_UNMAPPED、PARTIAL 或 REJECTED。", "正式物料核对门禁。", example="COMPLETE"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "source_row_ref"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
    ),
    T(
        "finance_inventory_flow_line", "财务月进销存行", "finance",
        "保存财务模板按仓别的期初、入库、领用和期末数量。",
        "财务批次 × 地点 × 月份 × 仓别 × 来源物料一行", "财务网站",
        ("财务网站", "供应链", "分析/BI"), "财务进销存模板", "REQUIRED",
        [
            ID("finance_inventory_flow_line_id", "财务进销存ID", "一条月进销存稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生该事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            F("source_row_ref", "来源行定位符", "text", "导入文件中的稳定行定位，例如工作表名与原始行号或来源记录号。", "与批次共同实现重跑幂等，同时保留内容相同的真实重复行。", example="StockFlow!R51"),
            F("source_row_fingerprint", "来源行内容指纹", "char(64)", "按版本化规范对来源行原值计算的 SHA-256。", "检测同一来源位置内容变化，不作为唯一业务身份。", example="7ac4...64位十六进制"),
            ID("location_id", "地点ID", "进销存归属地点。", fk="ops_location.location_id"),
            ID("material_id", "原料ID", "确认映射的统一原料；未知为空。", fk="scm_material.material_id", nullable=True),
            F("business_month", "业务月份", "date", "月份第一日。", "月度库存桥接。", example="2026-07-01"),
            F("warehouse_type", "仓别", "text", "AMBIENT、FROZEN、CHILLED 或 OTHER。", "库存条件分析。", example="FROZEN"),
            F("source_item_name", "来源物料名称", "text", "模板原始物料名称。", "保留映射证据。", example="Butter"),
            F("opening_quantity", "期初数量", "numeric(18,6)", "模板口径期初库存。", "进销存恒等式。", example="20"),
            F("received_quantity", "入库数量", "numeric(18,6)", "模板口径本月入库。", "采购核对。", example="15"),
            F("issued_quantity", "领用数量", "numeric(18,6)", "模板口径本月领用。", "生产消耗核对。", example="18"),
            F("closing_quantity", "期末数量", "numeric(18,6)", "模板口径期末库存。", "与次月期初核对。", example="17"),
            F("source_unit", "来源单位", "text", "模板数量单位。", "解释数量。", nullable=True, example="kg"),
            F("quality_status", "质量状态", "text", "COMPLETE、BALANCE_MISMATCH、UNMAPPED_MATERIAL 或 REJECTED。", "不平衡行进入质量队列。", example="COMPLETE"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "source_row_ref"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
    ),
    T(
        "finance_supplier_purchase_monthly", "财务供应商月采购", "finance",
        "保存财务模板按月、供应商、物料和规格聚合的采购数量、单价和金额。",
        "财务批次 × 地点 × 月份 × 来源供应商 × 来源物料 × 规格一行", "财务网站",
        ("财务网站", "供应链", "分析/BI"), "财务供应价格与进销存模板", "REQUIRED",
        [
            ID("finance_supplier_purchase_monthly_id", "供应商月采购ID", "一条月采购聚合稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生该事实的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            F("source_row_ref", "来源行定位符", "text", "导入文件中的稳定行定位，例如工作表名与原始行号或来源记录号。", "与批次共同实现重跑幂等，同时保留内容相同的真实重复行。", example="SupplierPrice!R27"),
            F("source_row_fingerprint", "来源行内容指纹", "char(64)", "按版本化规范对来源行原值计算的 SHA-256。", "检测同一来源位置内容变化，不作为唯一业务身份。", example="7ac4...64位十六进制"),
            ID("location_id", "地点ID", "采购服务地点。", fk="ops_location.location_id"),
            ID("supplier_id", "供应商ID", "确认映射的供应商；未知为空。", fk="scm_supplier.supplier_id", nullable=True),
            ID("material_id", "原料ID", "确认映射的原料；未知为空。", fk="scm_material.material_id", nullable=True),
            F("business_month", "业务月份", "date", "月份第一日。", "月采购核对。", example="2026-07-01"),
            F("source_supplier_name", "来源供应商名称", "text", "财务模板原始供应商名称。", "保留证据。", example="ABC Ingredients"),
            F("source_item_name", "来源物料名称", "text", "财务模板原始物料名称。", "保留证据。", example="Dark Chocolate"),
            F("specification", "规格", "text", "模板原始规格。", "辅助映射和价格解释。", nullable=True, example="5kg/case"),
            F("quantity", "采购数量", "numeric(18,6)", "模板口径月采购数量。", "与 SCM 收货聚合比较。", example="10"),
            F("source_unit", "来源数量单位", "text", "模板原样提供的采购单位；未提供时为空。", "数量、单价和规格只有在该单位下才可解释。", nullable=True, example="case"),
            F("unit_price", "模板单价", "numeric(18,6)", "模板口径单价。", "与收货实际价比较。", example="630"),
            F("amount", "采购金额", "numeric(18,4)", "模板口径月采购金额。", "采购财务核对。", example="6300"),
            F("currency", "币种", "char(3)", "金额币种。", "正确汇总。", default="'MYR'", example="MYR"),
            F("quality_status", "质量状态", "text", "COMPLETE、UNMAPPED_SUPPLIER、UNMAPPED_MATERIAL、PARTIAL 或 REJECTED。", "映射不足时不伪装正式 SCM 事实。", example="COMPLETE"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "source_row_ref"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
    ),
    T(
        "finance_target", "财务经营目标", "finance",
        "保存地点、月份和指标的目标值及版本。",
        "地点 × 月份 × 指标代码 × 版本一行", "财务网站",
        ("财务网站", "BakeryOps", "分析/BI"), "管理层批准目标", "REQUIRED",
        [
            ID("finance_target_id", "目标ID", "一版财务目标稳定主键。"),
            ID("location_id", "地点ID", "目标适用地点；公司总目标为空。", fk="ops_location.location_id", nullable=True),
            F("business_month", "目标月份", "date", "月份第一日。", "月度计划对比。", example="2026-08-01"),
            F("metric_code", "指标代码", "text", "REVENUE、GROSS_MARGIN、LABOR_COST_RATE 等标准指标。", "定义 target_value 含义。", example="REVENUE"),
            F("version_no", "版本号", "integer", "同地点、月份、指标内递增版本。", "预算调整不覆盖历史。", example="2", checks=("version_no > 0",)),
            F("target_value", "目标值", "numeric(24,8)", "目标数值。", "与 metric_code/unit 共同解释。", example="1600000"),
            F("unit", "目标单位", "text", "MYR、PERCENT、COUNT 等。", "避免数值歧义。", example="MYR"),
            F("status", "目标状态", "text", "DRAFT、APPROVED、ACTIVE 或 SUPERSEDED。", "只有 ACTIVE 进入正式对比。", example="ACTIVE"),
            ID("approved_by_user_id", "批准账号", "批准目标的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "目标批准时间。", "审计。", nullable=True, example="2026-07-28T10:00:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("location_id", "business_month", "metric_code", "version_no"),),
        nulls_not_distinct_uniques=(("location_id", "business_month", "metric_code", "version_no"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
        notes="DRAFT 可编辑；APPROVED、ACTIVE 或 SUPERSEDED 后本版本冻结。正式读取通过 v_finance_target_current 确定唯一当前版本，调整目标新增 version_no。",
    ),
    T(
        "finance_monthly_metric", "财务月度指标值", "finance",
        "保存财务模板提供的营业利润、净利润、摊销费、储值净额等标准月指标。",
        "财务批次 × 地点 × 月份 × 指标代码一行", "财务网站",
        ("财务网站", "分析/BI"), "财务利润表模板", "REQUIRED",
        [
            ID("finance_monthly_metric_id", "月指标ID", "一条财务月指标稳定主键。"),
            ID("finance_import_batch_id", "财务批次ID", "产生指标的导入批次。", fk="finance_import_batch.finance_import_batch_id"),
            ID("location_id", "地点ID", "指标归属地点。", fk="ops_location.location_id"),
            F("business_month", "业务月份", "date", "月份第一日。", "月度报表连接。", example="2026-07-01"),
            F("metric_code", "指标代码", "text", "财务指标稳定代码。", "避免把中文标签当键。", example="NET_PROFIT_WITH_STORED_VALUE"),
            F("metric_name_snapshot", "指标名称快照", "text", "导入时模板指标名称。", "模板改名后仍可解释。", example="净利润(含储值)"),
            F("metric_value", "指标值", "numeric(24,8)", "该指标月度数值。", "财务展示和目标对比。", example="125000"),
            F("unit", "单位", "text", "MYR、PERCENT、COUNT 等。", "解释指标值。", example="MYR"),
            F("quality_status", "质量状态", "text", "COMPLETE、UNCLASSIFIED、PARTIAL 或 REJECTED。", "正式财务输出门禁。", example="COMPLETE"),
        ], standard="immutable", uniques=(("finance_import_batch_id", "location_id", "business_month", "metric_code"),), checks=("EXTRACT(DAY FROM business_month) = 1",),
        notes="这里只保存财务模板或已批准管理报表明确给出的来源指标，不把可由本库销售、成本行或工时确定性计算的 KPI 再复制进来。即使同名指标可由运营事实估算，两侧仍作为独立来源用于核对，禁止相加或互相覆盖。",
    ),
    T(
        "finance_period_category_map", "期间费用归类规则", "finance",
        "版本化维护财务来源类别到销售、管理、财务、研发等期间费用口径的映射。",
        "来源大类 × 来源子类 × 生效区间一行", "财务网站",
        ("财务网站", "分析/BI"), "财务人员批准", "REQUIRED",
        [
            ID("period_category_map_id", "归类规则ID", "一条费用归类稳定主键。"),
            F("source_major", "来源大类", "text", "财务模板原始费用大类。", "匹配 finance_monthly_cost_line。", example="其他费用"),
            F("source_sub", "来源子类", "text", "财务模板原始费用子类。", "更细归类；通配规则需显式代码。", nullable=True, example="市场活动"),
            F("target_category", "目标期间费用类别", "text", "SELLING、ADMINISTRATIVE、FINANCE、R_AND_D 或 EXCLUDED。", "正式利润表分层。", example="SELLING"),
            F("valid_from", "生效日期", "date", "规则开始生效日期。", "历史月份按当时规则重现。", example="2026-01-01"),
            F("valid_to", "失效日期上界", "date", "规则停止生效的日期上界，该日期本身不再适用。", "以左闭右开区间保留历史并避免相邻规则重复命中。", nullable=True, example="2027-01-01"),
            F("status", "规则状态", "text", "DRAFT、ACTIVE 或 RETIRED。", "未命中或非 ACTIVE 规则进入待归类。", example="ACTIVE"),
            ID("approved_by_user_id", "批准账号", "批准归类规则的账号。", fk="app_user.user_id", nullable=True),
            F("note", "规则说明", "text", "特殊归类和边界说明。", "避免口径误解。", nullable=True, example="仅达人券相关活动"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("source_major", "source_sub", "valid_from"),),
        nulls_not_distinct_uniques=(("source_major", "source_sub", "valid_from"),), checks=(
            "valid_to IS NULL OR valid_to > valid_from",
            "source_sub IS NULL OR source_sub <> '__HOTCRUSH_ALL__'",
        ),
        exclusions=("NO_OVERLAP(source_major, COALESCE(source_sub, WILDCARD), daterange(valid_from, valid_to, '[)')) WHERE status = 'ACTIVE'",),
        notes="DRAFT 可编辑；ACTIVE 或 RETIRED 后冻结。归类变化新增生效区间，不能回写改变已出具期间的历史口径。",
    ),
]
