"""Operations planning/execution plus HR, training, shifts, and timesheets."""

from __future__ import annotations

from .model_types import F, ID, T


TABLES = [
    # ------------------------------------------------------------------
    # Operations: external context, forecast, plan, workload, execution
    # ------------------------------------------------------------------
    T(
        "ops_calendar_event", "日历事件", "ops",
        "保存已解析的节假日、学校假期和其他可验证日历事件。",
        "辖区 × 日期 × 事件一行", "BakeryOps 日历任务",
        ("BakeryOps", "分析/BI"), "已完成并获准使用的日历抓取任务", "REQUIRED",
        [
            ID("calendar_event_id", "日历事件ID", "一条日历事件稳定主键。"),
            ID("job_run_id", "任务运行ID", "产生事件的日历抓取任务；来源网址、内容哈希、解析器版本和批准证据放在该运行的 input_manifest 与审计事件。", fk="app_job_run.job_run_id"),
            F("jurisdiction_code", "辖区代码", "text", "事件适用辖区。", "与地点国家和地区匹配。", example="MY-14"),
            F("event_date", "事件日期", "date", "事件在当地日历发生的日期。", "与营业日期连接。", example="2026-08-31"),
            F("event_type", "事件类型", "text", "PUBLIC_HOLIDAY、SCHOOL_HOLIDAY、EVENT 或 CLOSURE。", "预测可按类型采用不同因子。", example="PUBLIC_HOLIDAY"),
            F("event_code", "事件代码", "text", "跨年份或来源可识别的标准事件代码。", "比较同类事件历史影响。", nullable=True, example="MY_NATIONAL_DAY"),
            F("event_name", "事件名称", "text", "来源确认的事件名称。", "业务展示和人工核对。", example="National Day"),
            F("is_paid_holiday", "是否法定带薪假", "boolean", "该地点员工是否按批准规则视为带薪公共假日。", "供班表和薪资接口参考，不替代劳动规则引擎。", nullable=True, example="true"),
            F("status", "事件状态", "text", "ACTIVE、CANCELLED 或 SUPERSEDED。", "来源修正时保留旧事件。", default="'ACTIVE'", example="ACTIVE"),
        ], standard="mutable", mutation_policy="CONTROLLED_WORKFLOW", uniques=(("job_run_id", "jurisdiction_code", "event_date", "event_name"),),
        notes="R6 不再另建日历导入批次表：一次抓取就是 app_job_run；需求因子由销售事实、日历事件和算法版本视图计算，预测实际采用值冻结在 forecast_run/line。",
    ),
    T(
        "ops_operational_event", "运营突发事件", "ops",
        "记录停电、设备故障、人流异常、促销或其他当日突发情况及人工证据。",
        "一个地点的一次连续运营事件一行", "门店或区域运营",
        ("BakeryOps", "分析/BI"), "人工确认；部分事件可由系统建议", "REQUIRED",
        [
            ID("operational_event_id", "运营事件ID", "一次运营突发稳定主键。"),
            ID("location_id", "地点ID", "事件发生地点。", fk="ops_location.location_id"),
            F("event_type", "事件类型", "text", "POWER_OUTAGE、EQUIPMENT_FAILURE、PROMOTION、FOOTFALL_SURGE、STAFF_SHORTAGE 或 OTHER。", "支持标准化影响分析。", example="EQUIPMENT_FAILURE"),
            F("event_title", "事件标题", "text", "简短可读的事件概述。", "供复盘和时间线展示。", example="烤箱2号故障"),
            F("started_at", "开始时间", "timestamptz", "事件实际或估计开始时间。", "判断受影响销售和生产时段。", example="2026-08-08T13:20:00+08:00"),
            F("ended_at", "结束时间", "timestamptz", "事件恢复时间；仍持续时为空。", "计算影响持续时间。", nullable=True, example="2026-08-08T15:10:00+08:00"),
            F("impact_direction", "影响方向", "text", "INCREASE、DECREASE、MIXED 或 UNKNOWN。", "区分需求上涨和产能下降。", example="DECREASE"),
            F("impact_summary", "影响说明", "text", "对产能、销售、人员或服务的可读说明。", "保留人工判断但不替代量化事实。", example="黑巧产能下降约30%"),
            F("evidence", "事件证据", "jsonb", "照片链接哈希、设备工单或销售差异等脱敏证据。", "支持审核。", default="'{}'::jsonb", example='{"ticket":"EQ-20260808-2"}'),
            F("status", "事件状态", "text", "OPEN、CONFIRMED、RESOLVED 或 REJECTED。", "只有确认事件影响正式复盘。", default="'OPEN'", example="CONFIRMED"),
        ], standard="manual", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL", checks=("ended_at IS NULL OR ended_at > started_at",),
        notes="OPEN 阶段允许补充证据和结束时间；CONFIRMED、RESOLVED 或 REJECTED 后事件冻结，更正追加新事件或审计冲销，不原地改写历史。",
    ),
    T(
        "ops_operational_event_product", "运营事件受影响产品", "ops",
        "明确运营事件影响哪些产品以及影响方向和数量。",
        "运营事件 × 产品一行", "门店或区域运营",
        ("BakeryOps", "分析/BI"), "人工确认", "REQUIRED",
        [
            ID("operational_event_product_id", "关系ID", "事件产品影响稳定主键。"),
            ID("operational_event_id", "运营事件ID", "所属运营事件。", fk="ops_operational_event.operational_event_id"),
            ID("product_id", "产品ID", "受影响统一产品。", fk="ops_product.product_id"),
            F("impact_direction", "影响方向", "text", "INCREASE、DECREASE、UNAVAILABLE 或 UNKNOWN。", "决定预测和复盘解释。", example="DECREASE"),
            F("estimated_quantity_impact", "估计数量影响", "numeric(18,4)", "按事件发生时 product.base_unit 估计的少产或多卖数量，未知为空。", "只能作为估算，不冒充实际销售或产出。", nullable=True, example="-20"),
            F("note", "补充说明", "text", "产品层面的人工说明。", "解释无法量化的影响。", nullable=True, example="15:10后恢复"),
        ], standard="manual", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL", uniques=(("operational_event_id", "product_id"),),
        notes="只允许在父事件 OPEN 阶段补充；父事件进入终态后本行冻结。",
    ),
    T(
        "ops_forecast_run", "需求预测运行", "ops",
        "冻结一次预测使用的目标日期、算法、输入清单和结果状态。",
        "地点 × 目标营业日 × 一次算法运行一行", "BakeryOps 预测任务",
        ("BakeryOps", "分析/BI"), "POS历史、日历、突发事件和业务规则", "REQUIRED",
        [
            ID("forecast_run_id", "预测运行ID", "一次预测运行稳定身份。"),
            ID("job_run_id", "任务运行ID", "执行预测的自动任务。", fk="app_job_run.job_run_id"),
            ID("location_id", "地点ID", "预测目标门店或生产地点。", fk="ops_location.location_id"),
            F("target_business_date", "目标营业日", "date", "预测要回答的营业日期。", "连接预估单和实际销售。", example="2026-08-10"),
            F("algorithm_version", "算法版本", "text", "预测算法和参数版本。", "使结果可重现和比较。", example="forecast-v4.2"),
            F("input_manifest", "输入版本清单", "jsonb", "销售批次、日历批次、规则版本和人工事件 ID。", "证明预测使用了哪些事实。", example='{"sales_batch":"...","calendar_batch":"..."}'),
            F("status", "运行状态", "text", "RUNNING、SUCCEEDED、PARTIAL、FAILED 或 REJECTED。", "控制结果能否生成计划。", example="SUCCEEDED"),
            F("started_at", "开始时间", "timestamptz", "预测计算开始时间。", "运行监控。", example="2026-08-09T08:00:00+08:00"),
            F("completed_at", "完成时间", "timestamptz", "预测计算结束时间。", "判断新鲜度。", nullable=True, example="2026-08-09T08:00:12+08:00"),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL",
    ),
    T(
        "ops_forecast_line", "产品预测行", "ops",
        "保存一次预测对每个产品的数量区间和解释。",
        "预测运行 × 产品一行", "BakeryOps 预测任务",
        ("BakeryOps", "分析/BI"), "预测运行输出", "REQUIRED",
        [
            ID("forecast_line_id", "预测行ID", "产品预测行稳定主键。"),
            ID("forecast_run_id", "预测运行ID", "所属预测运行。", fk="ops_forecast_run.forecast_run_id"),
            ID("product_id", "产品ID", "被预测产品。", fk="ops_product.product_id"),
            F("forecast_quantity", "预测数量", "numeric(18,4)", "按 forecast_run 执行时 product.base_unit 计算的中心预测数量。", "计划量的建议起点，不是人工批准计划；产品基础单位变更必须形成新产品或受控版本。", example="86", checks=("forecast_quantity >= 0",)),
            F("lower_bound", "预测下界", "numeric(18,4)", "批准置信水平下的需求下界。", "表达不确定性。", nullable=True, example="72"),
            F("upper_bound", "预测上界", "numeric(18,4)", "批准置信水平下的需求上界。", "表达不确定性。", nullable=True, example="101"),
            F("model_explanation", "模型解释", "jsonb", "主要特征、日历因子和异常说明。", "让运营理解建议来源；不得编造因果。", default="'{}'::jsonb", example='{"holiday_factor":1.1}'),
            F("quality_status", "质量状态", "text", "COMPLETE、LOW_HISTORY、UNMAPPED_INPUT 或 REJECTED。", "低质量预测必须在计划界面显式提示。", default="'COMPLETE'", example="COMPLETE"),
        ], standard="immutable", uniques=(("forecast_run_id", "product_id"),),
        checks=("lower_bound IS NULL OR lower_bound >= 0", "upper_bound IS NULL OR upper_bound >= forecast_quantity"),
    ),
    T(
        "ops_production_plan_version", "生产预估单版本", "ops",
        "直接保留某地点某营业日每次预测建议、人工调整、审批、发布或取消，不再为同一自然键另建空壳主单。",
        "生产地点 × 计划营业日 × 版本号一行", "BakeryOps；审批人改变状态",
        ("BakeryOps", "供应链", "分析/BI"), "预测或人工复制调整", "REQUIRED",
        [
            ID("production_plan_version_id", "预估单版本ID", "一版预估单稳定身份。"),
            ID("location_id", "生产地点ID", "执行生产的门店或中央厨房。", fk="ops_location.location_id"),
            F("plan_business_date", "计划营业日", "date", "该版本计划产出服务的营业日期。", "与销售、物料需求和班表使用同一 location_id + business_date 连接。", example="2026-08-10"),
            ID("forecast_run_id", "预测运行ID", "该版本起点的预测运行；纯人工版本可以为空。", fk="ops_forecast_run.forecast_run_id", nullable=True),
            ID("based_on_version_id", "基础版本ID", "本版本从哪一旧版本复制或调整。", fk="ops_production_plan_version.production_plan_version_id", nullable=True),
            F("version_no", "版本号", "integer", "同一生产地点和计划营业日内从 1 递增的版本号。", "清晰排序版本。", example="3", checks=("version_no > 0",)),
            F("status", "版本状态", "text", "DRAFT、SUBMITTED、APPROVED、PUBLISHED、SUPERSEDED、REJECTED 或 CANCELLED。", "只有 PUBLISHED 可触发正式物料需求和班表；取消计划必须追加 CANCELLED 版本。", example="PUBLISHED"),
            F("change_summary", "改动摘要", "text", "相对基础版本的人工或系统改动说明。", "帮助审批者快速理解变化。", nullable=True, example="黑巧+12，草莓塔-6"),
            F("approved_at", "批准时间", "timestamptz", "审批完成时间。", "区分提交与批准。", nullable=True, example="2026-08-09T12:00:00+08:00"),
            ID("approved_by_user_id", "批准账号", "批准该版本的账号。", fk="app_user.user_id", nullable=True),
            F("published_at", "发布时间", "timestamptz", "版本成为正式下游输入的时间。", "物料需求和班表读取的版本门禁。", nullable=True, example="2026-08-09T12:05:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("location_id", "plan_business_date", "version_no"),),
        notes="R6 终审将 ops_production_plan 合并到本表：location_id + plan_business_date 就是跨版本自然身份，另存主单 UUID 和可变头状态只会重复。草稿可受控修改；PUBLISHED、REJECTED、CANCELLED 或 SUPERSEDED 后冻结。任何数量调整或整单取消都追加新版本，产品级来源与理由保存在新版本的 ops_production_plan_line。",
    ),
    T(
        "ops_production_plan_line", "生产预估单产品行", "ops",
        "保存某版本每个产品的计划数量和人工判断来源。",
        "预估单版本 × 产品一行", "BakeryOps",
        ("BakeryOps", "供应链", "分析/BI"), "预测行加人工调整", "REQUIRED",
        [
            ID("production_plan_line_id", "计划行ID", "一条产品计划行稳定主键。"),
            ID("production_plan_version_id", "预估单版本ID", "所属预估单版本。", fk="ops_production_plan_version.production_plan_version_id"),
            ID("product_id", "产品ID", "计划生产的统一产品。", fk="ops_product.product_id"),
            ID("forecast_line_id", "预测行ID", "该计划行采用的预测建议；纯人工添加可为空。", fk="ops_forecast_line.forecast_line_id", nullable=True),
            ID("based_on_plan_line_id", "基础计划行ID", "本产品行从上一版本哪一行复制或调整；首次或新增产品为空。", fk="ops_production_plan_line.production_plan_line_id", nullable=True),
            F("planned_quantity", "计划数量", "numeric(18,4)", "该版本按本行 unit_id 批准准备的总数量。", "物料需求、工作量和计划偏差的基准。", example="96", checks=("planned_quantity >= 0",)),
            ID("unit_id", "计划单位ID", "计划数量采用的受控单位，发布时必须等于产品基础单位。", fk="app_unit.unit_id"),
            F("adjustment_reason_code", "调整原因代码", "text", "若偏离预测，记录批准原因。", "分析人工判断效果。", nullable=True, example="HOLIDAY_UPLIFT"),
            F("adjustment_note", "调整依据说明", "text", "本产品相对基础行发生变化时的必要理由。", "保留产品级人工判断，不把多个产品原因压到版本头。", nullable=True, example="公共假日前一日客流通常上升"),
            ID("suggested_by_ai_call_id", "建议AI调用ID", "若该产品数量来自 AI 建议，连接产生建议的调用。", fk="ai_call.ai_call_id", nullable=True),
            ID("confirmed_by_user_id", "确认账号", "确认采用该产品数量的应用账号。", fk="app_user.user_id", nullable=True),
            F("note", "计划备注", "text", "产品层面的简短执行说明。", "传递不能结构化的必要信息。", nullable=True, example="首批提前30分钟"),
        ], standard="immutable", uniques=(("production_plan_version_id", "product_id"),),
        notes="before quantity 和 delta 由 based_on_plan_line_id 与 planned_quantity 确定性派生；这里只保存不可派生的产品级决定、理由和来源。",
    ),
    T(
        "ops_production_plan_slot", "生产时段计划", "ops",
        "把产品总计划拆到具体生产时段，解决总量正确但时段断货的问题。",
        "计划产品行 × 生产时段一行", "BakeryOps",
        ("BakeryOps", "分析/BI"), "运营排产", "REQUIRED",
        [
            ID("production_plan_slot_id", "时段计划ID", "一条时段计划稳定主键。"),
            ID("production_plan_line_id", "计划行ID", "所属产品计划行。", fk="ops_production_plan_line.production_plan_line_id"),
            F("slot_start", "时段开始", "time", "当地营业日内生产时段开始时间。", "决定实际生产顺序。", example="08:00:00"),
            F("slot_end", "时段结束", "time", "生产时段结束时间。", "定义时段边界。", example="10:00:00"),
            F("planned_quantity", "时段计划数量", "numeric(18,4)", "按父计划行 unit_id 统计的本时段应完成数量。", "与实际产出和断货时点比较；所有时段合计由视图核对父行数量。", example="36", checks=("planned_quantity >= 0",)),
            F("sequence_no", "执行顺序", "integer", "同产品时段的显示和执行顺序。", "稳定排序。", example="1", checks=("sequence_no > 0",)),
        ], standard="immutable", uniques=(("production_plan_line_id", "sequence_no"),), checks=("slot_end > slot_start",),
    ),
    T(
        "ops_workload_run", "工作量计算运行", "ops",
        "把已发布生产计划和预测销售转换为岗位/工位所需分钟，作为班表显式上游。",
        "地点 × 营业日 × 一次工作量计算一行", "BakeryOps 工作量任务",
        ("BakeryOps", "分析/BI"), "已发布预估单、历史服务量和标准工时", "REQUIRED",
        [
            ID("workload_run_id", "工作量运行ID", "一次工作量计算稳定身份。"),
            ID("job_run_id", "任务运行ID", "执行计算的自动任务。", fk="app_job_run.job_run_id"),
            ID("location_id", "地点ID", "工作量目标地点。", fk="ops_location.location_id"),
            ID("production_plan_version_id", "预估单版本ID", "工作量采用的已发布生产计划。", fk="ops_production_plan_version.production_plan_version_id", nullable=True),
            F("business_date", "营业日期", "date", "需要安排人员的日期。", "连接班表主单。", example="2026-08-10"),
            F("algorithm_version", "算法版本", "text", "标准工时和转换规则版本。", "支持重算和解释需求变化。", example="workload-v1"),
            F("input_manifest", "输入清单", "jsonb", "计划版本、销售预测、营业时段和规则版本。", "证明班表需求来源。", example='{"plan_version":"..."}'),
            F("status", "运行状态", "text", "RUNNING、SUCCEEDED、PARTIAL、FAILED 或 REJECTED。", "只有合格结果可进入班表。", example="SUCCEEDED"),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL",
    ),
    T(
        "ops_workload_line", "岗位工作量行", "ops",
        "保存某工作量运行对岗位、工位及可选产品的需求分钟和数量依据。",
        "工作量运行 × 岗位 × 工位 × 可选产品一行", "BakeryOps 工作量任务",
        ("BakeryOps", "分析/BI"), "工作量计算输出", "REQUIRED",
        [
            ID("workload_line_id", "工作量行ID", "一条工作量需求稳定主键。"),
            ID("workload_run_id", "工作量运行ID", "所属工作量运行。", fk="ops_workload_run.workload_run_id"),
            ID("role_id", "岗位ID", "需要人员履行的标准岗位。", fk="ops_role.role_id"),
            ID("station_id", "工位ID", "工作发生工位；无具体工位可为空。", fk="ops_station.station_id", nullable=True),
            ID("product_id", "产品ID", "该工作量由特定产品产生时记录。", fk="ops_product.product_id", nullable=True),
            F("workload_unit", "工作量单位", "text", "PRODUCT_EA、ORDER、CUSTOMER、OPEN_HOUR 或 MANUAL。", "解释 workload_quantity。", example="PRODUCT_EA"),
            F("workload_quantity", "工作量数量", "numeric(18,4)", "计划产品数、预测订单数等输入数量。", "与标准分钟相乘。", example="96"),
            F("standard_minutes_per_unit", "单位标准分钟", "numeric(18,6)", "每单位工作量所需标准分钟。", "将业务量转换为用工需求。", example="1.250000", checks=("standard_minutes_per_unit >= 0",)),
            F("required_work_minutes", "需求工作分钟", "numeric(18,4)", "该行计算出的总需求分钟。", "班表人数和时长的直接依据。", example="120", checks=("required_work_minutes >= 0",)),
            F("explanation", "计算说明", "jsonb", "取整、并行、最低开岗等规则明细。", "让排班者理解算法。", default="'{}'::jsonb", example='{"minimum_staff":1}'),
        ], standard="immutable",
        uniques=(("workload_run_id", "role_id", "station_id", "product_id", "workload_unit"),),
        nulls_not_distinct_uniques=(("workload_run_id", "role_id", "station_id", "product_id", "workload_unit"),),
        notes="required_work_minutes 是按 algorithm_version 冻结的运行输出；因最低开岗、并行和取整不一定等于简单乘法，具体公式必须在 explanation 中可复算。",
    ),
    T(
        "ops_production_run", "实际生产批次", "ops",
        "记录一次真实生产执行，不用计划数量冒充实际产出。",
        "生产地点 × 营业日 × 一次生产批次一行", "门店/厨房执行流程",
        ("BakeryOps", "供应链", "分析/BI"), "生产人员确认或设备数据", "REQUIRED",
        [
            ID("production_run_id", "生产批次ID", "一次实际生产批次稳定身份。"),
            ID("location_id", "生产地点ID", "实际执行生产的地点。", fk="ops_location.location_id"),
            ID("production_plan_version_id", "预估单版本ID", "该批次执行的已发布计划版本；临时生产可为空并说明。", fk="ops_production_plan_version.production_plan_version_id", nullable=True),
            F("business_date", "营业日期", "date", "生产产出服务的营业日。", "与销售和成本连接。", example="2026-08-10"),
            F("source_run_code", "执行批次代码", "text", "现场或设备使用的可读批次编号。", "现场追踪和幂等。", nullable=True, example="PAV-20260810-01"),
            F("started_at", "开始时间", "timestamptz", "实际开工时间。", "分析延迟和产能。", example="2026-08-10T06:30:00+08:00"),
            F("completed_at", "完成时间", "timestamptz", "本批生产完成时间。", "计算工时和及时率。", nullable=True, example="2026-08-10T08:20:00+08:00"),
            F("status", "执行状态", "text", "IN_PROGRESS、COMPLETED、CANCELLED 或 REJECTED。", "只有完成批次进入实际产出。", example="COMPLETED"),
            F("note", "执行备注", "text", "异常或临时加产说明。", "解释偏差。", nullable=True, example="烤箱预热延迟10分钟"),
        ], standard="manual", uniques=(("location_id", "source_run_code"),),
        nulls_distinct_uniques=(("location_id", "source_run_code"),), checks=("completed_at IS NULL OR completed_at >= started_at",),
    ),
    T(
        "ops_production_run_line", "实际生产产品行", "ops",
        "保存实际生产的合格、报废和返工数量，并可追溯到计划行。",
        "生产批次 × 产品一行", "门店/厨房执行流程",
        ("BakeryOps", "供应链", "分析/BI"), "生产人员确认或设备数据", "REQUIRED",
        [
            ID("production_run_line_id", "生产行ID", "一条实际产出稳定主键。"),
            ID("production_run_id", "生产批次ID", "所属实际生产批次。", fk="ops_production_run.production_run_id"),
            ID("product_id", "产品ID", "实际生产产品。", fk="ops_product.product_id"),
            ID("production_plan_line_id", "计划行ID", "对应计划产品行；临时加产可为空。", fk="ops_production_plan_line.production_plan_line_id", nullable=True),
            F("good_quantity", "合格数量", "numeric(18,4)", "按本行 unit_id 记录的可销售或可配送合格产出数量。", "计划达成和库存增加。", example="94", checks=("good_quantity >= 0",)),
            F("scrap_quantity", "报废数量", "numeric(18,4)", "按本行 unit_id 记录的生产阶段无法使用数量。", "生产损耗和成本。", default="0", example="2", checks=("scrap_quantity >= 0",)),
            F("rework_quantity", "返工数量", "numeric(18,4)", "按本行 unit_id 记录的需要返工但尚未报废数量。", "避免把返工算作合格产出。", default="0", example="0", checks=("rework_quantity >= 0",)),
            ID("unit_id", "数量单位ID", "实际产出采用的受控单位，必须与产品基础单位一致。", fk="app_unit.unit_id"),
        ], standard="immutable", uniques=(("production_run_id", "product_id"),),
    ),
    T(
        "ops_dispatch", "地点间配送", "ops",
        "记录成品从中央厨房或门店发往另一地点的一次配送。",
        "发出地点 × 接收地点 × 一次配送批次一行", "配送执行流程",
        ("BakeryOps", "供应链", "分析/BI"), "人工确认或物流系统", "REQUIRED",
        [
            ID("dispatch_id", "配送ID", "一次地点间配送稳定身份。"),
            ID("from_location_id", "发出地点ID", "成品发出地点。", fk="ops_location.location_id"),
            ID("to_location_id", "接收地点ID", "成品接收地点。", fk="ops_location.location_id"),
            ID("production_run_id", "生产批次ID", "配送主要来自的生产批次；混批可为空并由行级追踪。", fk="ops_production_run.production_run_id", nullable=True),
            F("dispatch_code", "配送单号", "text", "现场或物流使用的唯一单号。", "幂等和业务沟通。", unique=True, example="DSP-20260810-01"),
            F("business_date", "营业日期", "date", "配送服务的营业日。", "连接门店销售和计划。", example="2026-08-10"),
            F("dispatched_at", "发出时间", "timestamptz", "货物离开发出地点的时间。", "计算在途和及时性。", example="2026-08-10T09:00:00+08:00"),
            F("received_at", "接收时间", "timestamptz", "接收地点确认到货时间。", "闭环配送。", nullable=True, example="2026-08-10T09:35:00+08:00"),
            F("status", "配送状态", "text", "PLANNED、DISPATCHED、RECEIVED、PARTIAL、CANCELLED。", "区分计划、在途和实收。", example="RECEIVED"),
        ], standard="manual", uniques=(("dispatch_code",),), checks=("from_location_id <> to_location_id", "received_at IS NULL OR received_at >= dispatched_at"),
    ),
    T(
        "ops_dispatch_line", "配送产品行", "ops",
        "保存配送中每个产品的发出、接收、拒收和差异数量。",
        "配送单 × 产品一行", "配送执行流程",
        ("BakeryOps", "供应链", "分析/BI"), "发出与接收确认", "REQUIRED",
        [
            ID("dispatch_line_id", "配送行ID", "一条配送产品行稳定主键。"),
            ID("dispatch_id", "配送ID", "所属配送单。", fk="ops_dispatch.dispatch_id"),
            ID("product_id", "产品ID", "配送产品。", fk="ops_product.product_id"),
            ID("production_run_line_id", "生产行ID", "来源生产行；无法唯一分配时为空。", fk="ops_production_run_line.production_run_line_id", nullable=True),
            F("dispatched_quantity", "发出数量", "numeric(18,4)", "按本行 unit_id 记录的发出地点确认数量。", "在途和发出事实。", example="48", checks=("dispatched_quantity >= 0",)),
            F("received_quantity", "接收数量", "numeric(18,4)", "按本行 unit_id 记录的接收地点确认合格数量。", "实际可售数量。", nullable=True, example="47", checks=("received_quantity IS NULL OR received_quantity >= 0",)),
            F("rejected_quantity", "拒收数量", "numeric(18,4)", "按本行 unit_id 记录的接收时拒收或损坏数量。", "配送损耗和责任分析。", default="0", example="1", checks=("rejected_quantity >= 0",)),
            F("variance_reason", "差异原因", "text", "发出与接收不一致的原因。", "闭环异常。", nullable=True, example="TRANSPORT_DAMAGE"),
            ID("unit_id", "数量单位ID", "配送数量采用的受控单位，必须与产品基础单位一致。", fk="app_unit.unit_id"),
        ], standard="immutable", uniques=(("dispatch_id", "product_id"),),
    ),
    T(
        "ops_daily_review", "每日运营复盘", "ops",
        "保存某地点营业日的结构化复盘版本，区分人工事实、AI总结和采纳状态。",
        "地点 × 营业日 × 复盘版本一行", "BakeryOps 复盘流程",
        ("BakeryOps", "分析/BI"), "POS、计划、生产、班表、突发与人工输入", "REQUIRED",
        [
            ID("daily_review_id", "复盘ID", "一版每日复盘稳定主键。"),
            ID("location_id", "地点ID", "复盘地点。", fk="ops_location.location_id"),
            F("business_date", "营业日期", "date", "被复盘的营业日。", "与全部经营事实连接。", example="2026-08-08"),
            F("version_no", "版本号", "integer", "同地点同日期的复盘版本。", "人工修正不覆盖旧内容。", example="2", checks=("version_no > 0",)),
            ID("ai_call_id", "AI调用ID", "生成或辅助该复盘的 AI 调用。", fk="ai_call.ai_call_id", nullable=True),
            F("manager_revenue", "店长录入营收", "numeric(18,4)", "店长对该营业日确认或录入的营收金额。", "与 POS 营收独立保存并用于差异核对，不能藏在 JSON 中。", nullable=True, example="18520.40", checks=("manager_revenue IS NULL OR manager_revenue >= 0",)),
            F("manager_transaction_count", "店长录入交易数", "integer", "店长确认的该营业日交易笔数。", "与 POS 交易数核对。", nullable=True, example="312", checks=("manager_transaction_count IS NULL OR manager_transaction_count >= 0",)),
            F("manager_avg_transaction", "店长报告平均客单", "numeric(18,4)", "店长或现有来源独立报告的平均每笔交易金额；若只是 manager_revenue ÷ manager_transaction_count 的系统计算结果则必须留空。", "无损保留历史独立观察值并与可派生客单核对，禁止重复存同一计算结果。", nullable=True, example="59.36", checks=("manager_avg_transaction IS NULL OR manager_avg_transaction >= 0",)),
            F("manager_avg_transaction_source", "店长客单来源", "text", "manager_avg_transaction 非空时必须说明 INDEPENDENT_MANAGER_REPORT、INDEPENDENT_SOURCE_REPORT 或 MIGRATED_LEGACY。", "用机器约束证明该值是独立观察而不是系统重复计算。", nullable=True, example="INDEPENDENT_MANAGER_REPORT", checks=("manager_avg_transaction_source IS NULL OR manager_avg_transaction_source IN ('INDEPENDENT_MANAGER_REPORT','INDEPENDENT_SOURCE_REPORT','MIGRATED_LEGACY')",)),
            F("manager_revenue_at", "店长营收录入时间", "timestamptz", "店长营收数字被确认的绝对时间。", "判断录入新鲜度和版本来源；不是营业日。", nullable=True, example="2026-08-09T09:15:00+08:00"),
            F("manager_currency", "店长金额币种", "char(3)", "店长录入营收和平均客单的币种。", "防止跨币种错误核对。", default="'MYR'", example="MYR"),
            F("manager_input_schema_version", "店长补充输入结构版本", "text", "manager_input JSON 的批准结构版本。", "允许新增低频原因时仍能解释历史 JSON。", default="'daily-review-manager-v1'", example="daily-review-manager-v1"),
            F("manager_input", "店长补充输入", "jsonb", "店长确认的突发事件、原因、备注和暂未升格的低频信息。", "补充结构化列；不得再次放入营收、交易数、客单价等稳定分析字段。", default="'{}'::jsonb", example='{"event":"rain","tomorrow_action":"reduce_first_batch"}'),
            F("review_summary_schema_version", "复盘摘要结构版本", "text", "review_summary JSON 采用的批准结构版本。", "保证历史复盘在结构升级后仍可验证和解释。", default="'daily-review-summary-v1'", example="daily-review-summary-v1"),
            F("review_summary", "结构化复盘", "jsonb", "按批准 schema 保存结论、指标和证据引用。", "支持稳定分析，不依赖自由文本解析。", example='{"forecast_accuracy":0.82}'),
            F("status", "复盘状态", "text", "DRAFT、SUBMITTED、APPROVED 或 SUPERSEDED。", "只有批准复盘进入正式改进行动。", example="APPROVED"),
            ID("approved_by_user_id", "批准账号", "批准复盘的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "复盘批准时间。", "审计决策。", nullable=True, example="2026-08-09T10:00:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("location_id", "business_date", "version_no"),),
        checks=("(manager_avg_transaction IS NULL AND manager_avg_transaction_source IS NULL) OR (manager_avg_transaction IS NOT NULL AND manager_avg_transaction_source IS NOT NULL)",),
        notes="保存只修改 DRAFT；提交/批准后冻结。若店长或 POS 后续更正，复制为 version_no+1 并将旧版标为 SUPERSEDED。manager_input 与 review_summary 必须分别按其 schema version 通过受控写函数校验，未知键拒绝。manager_avg_transaction 只承接带明确 source 的历史或人工独立报告值；新系统计算值由视图从 manager_revenue / manager_transaction_count 派生。正式 current 读取按 v_ops_daily_review_current 的确定性规则选版。",
    ),
    T(
        "ops_review_action", "复盘改进行动", "ops",
        "把复盘建议变成有负责人、期限和完成状态的动作。",
        "复盘 × 一项改进行动一行", "门店或区域运营",
        ("BakeryOps", "分析/BI"), "已批准复盘或人工创建", "REQUIRED",
        [
            ID("review_action_id", "行动ID", "一项改进行动稳定主键。"),
            ID("daily_review_id", "复盘ID", "行动来源复盘。", fk="ops_daily_review.daily_review_id"),
            F("action_type", "行动类型", "text", "PLAN_ADJUSTMENT、TRAINING、MAINTENANCE、SUPPLY、STAFFING 或 OTHER。", "路由到正确业务模块。", example="PLAN_ADJUSTMENT"),
            F("action_description", "行动说明", "text", "具体、可验证的下一步。", "避免只保存泛泛建议。", example="明日黑巧首批增加12个"),
            ID("owner_employment_id", "负责人雇佣ID", "负责完成行动的员工。", fk="hr_employment.employment_id", nullable=True),
            F("due_at", "截止时间", "timestamptz", "行动应完成时间。", "跟踪逾期。", nullable=True, example="2026-08-09T18:00:00+08:00"),
            F("status", "行动状态", "text", "OPEN、IN_PROGRESS、COMPLETED、CANCELLED 或 REJECTED。", "形成复盘闭环。", default="'OPEN'", example="OPEN"),
            F("completed_at", "完成时间", "timestamptz", "行动实际完成时间。", "计算执行及时率。", nullable=True, example="2026-08-09T17:20:00+08:00"),
            F("completion_evidence", "完成证据", "jsonb", "相关新计划版本、培训结果或工单 ID。", "证明行动真正落地。", default="'{}'::jsonb", example='{"plan_version_id":"..."}'),
        ], standard="manual",
    ),
    T(
        "ops_business_rule", "运营业务规则", "ops",
        "版本化保存企业级、地点级、产品级或地点产品级的排产阈值、产品策略、招聘可预约窗口和断货排除等低频配置。",
        "适用地点/产品组合或企业全局 × 规则代码 × 版本一行", "BakeryOps 设置流程",
        ("BakeryOps", "分析/BI"), "管理员配置", "REQUIRED",
        [
            ID("business_rule_id", "规则ID", "一版业务规则稳定主键。"),
            ID("scope_location_id", "适用地点ID", "规则只适用于某门店、厨房或仓库时填写；企业全局规则为空。", fk="ops_location.location_id", nullable=True),
            ID("scope_product_id", "适用产品ID", "规则只适用于某企业产品时填写；非产品规则或全产品规则为空。", fk="ops_product.product_id", nullable=True),
            F("rule_code", "规则代码", "text", "程序读取的稳定规则名称。", "避免散落硬编码。", example="STOCKOUT_EXCLUDE_PRODUCTS"),
            F("version_no", "版本号", "integer", "规则代码内递增版本。", "追溯历史计算。", example="4", checks=("version_no > 0",)),
            F("rule_value", "规则值", "jsonb", "符合 schema_version 所指固定 JSON Schema 的结构化规则内容；不接受未登记键。", "承载低频、形状随 rule_code 变化但必须整体版本化的配置，避免为每种规则建一张表或把多门店配置塞入产品主档。", example='{"planning_reference_price":28,"currency":"MYR","display_full_quantity":24,"positioning_code":"TOP","target_sales_mix_ratio":0.3,"legacy_target_tc_value":120,"audience_code":"ALL","stockout_target_time":"18:00:00","display_sort_order":10,"fixed_shipment_times":["10:00:00","14:00:00"]}', notes="PRODUCT_LOCATION_PLANNING_POLICY v1 必须逐键校验：价格/陈列量/旧TC值非负，currency 为 ISO 4217，positioning_code 为 TOP/POTENTIAL_TOP/OTHER，占比 0..1，时刻为地点本地 HH24:MI:SS，出货时刻升序去重。legacy_target_tc_value 只保留旧 target_tc 原值；周期和分母未确认前禁止参与自动决策。"),
            F("schema_version", "结构版本", "text", "rule_value 的 JSON Schema 版本。", "升级结构时保证解析。", example="stockout-exclude-v1"),
            F("valid_from", "生效时间", "timestamptz", "规则开始用于新计算的时间。", "历史计算使用当时版本。", example="2026-08-09T00:00:00+08:00"),
            F("valid_to", "失效时间", "timestamptz", "规则停止生效时间。", "保留历史。", nullable=True, example="2026-09-01T00:00:00+08:00"),
            F("status", "规则状态", "text", "DRAFT、APPROVED、ACTIVE 或 RETIRED。", "只有 ACTIVE 可被运行任务读取。", example="ACTIVE"),
            ID("approved_by_user_id", "批准账号", "批准规则的账号。", fk="app_user.user_id", nullable=True),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("scope_location_id", "scope_product_id", "rule_code", "version_no"),), nulls_not_distinct_uniques=(("scope_location_id", "scope_product_id", "rule_code", "version_no"),), checks=("valid_to IS NULL OR valid_to > valid_from",),
        exclusions=("NO_OVERLAP(COALESCE(scope_location_id, NIL_UUID), COALESCE(scope_product_id, NIL_UUID), rule_code, tstzrange(valid_from, valid_to, '[)')) WHERE status = 'ACTIVE'",),
        notes="DRAFT 可编辑；APPROVED 或 ACTIVE 后适用地点/产品、规则值、schema、版本号和生效起点冻结，修改必须发布新版本。同 rule_code 同时命中时按 地点+产品 > 地点 > 产品 > 企业全局 取最具体一条；同一具体范围禁止有效期重叠。ops_store.interview_windows/trial_windows 迁为地点级 HR_INTERVIEW_WINDOWS/HR_TRIAL_WINDOWS。现有 product 的地点敏感策略迁为 PRODUCT_LOCATION_PLANNING_POLICY；旧 product 行没有地点字段，只有来源部署/导入合同能唯一证明地点时才填 scope_location_id，不能默认扩散到新门店。",
    ),

    # ------------------------------------------------------------------
    # HR recruitment, employment events, training, shifts, timesheets
    # ------------------------------------------------------------------
    T(
        "hr_job_requisition", "招聘需求", "hr",
        "记录某地点、岗位所需人数、期限和批准状态，作为候选申请的业务来源。",
        "一个招聘需求一行", "HR 招聘流程",
        ("BakeryOps", "分析/BI"), "业务部门提交并审批", "REQUIRED",
        [
            ID("job_requisition_id", "招聘需求ID", "招聘需求稳定主键。"),
            ID("location_id", "地点ID", "需求所属地点。", fk="ops_location.location_id"),
            ID("role_id", "岗位ID", "计划招聘的标准岗位。", fk="ops_role.role_id", nullable=True),
            F("requisition_code", "需求代码", "text", "业务可读唯一需求编号。", "连接外部招聘平台和申请。", unique=True, example="REQ-PAV-KITCHEN-202608"),
            F("headcount_requested", "需求人数", "integer", "批准前提出的招聘人数。", "衡量缺口。", example="3", checks=("headcount_requested > 0",)),
            F("employment_type", "用工类型", "text", "FULL_TIME、PART_TIME、CONTRACTOR、INTERN 或 CASUAL。", "筛选候选和 Offer。", example="FULL_TIME"),
            F("target_start_date", "目标到岗日", "date", "希望新员工开始工作的日期。", "招聘优先级和进度。", nullable=True, example="2026-09-01"),
            F("status", "需求状态", "text", "DRAFT、APPROVED、OPEN、ON_HOLD、FILLED 或 CANCELLED。", "只有 OPEN 可接受新申请。", example="OPEN"),
            F("approved_at", "批准时间", "timestamptz", "招聘需求获批时间。", "区分业务意向和正式需求。", nullable=True, example="2026-08-09T10:00:00+08:00"),
            ID("approved_by_user_id", "批准账号", "批准需求的账号。", fk="app_user.user_id", nullable=True),
        ], standard="manual", mutation_policy="CONTROLLED_WORKFLOW", uniques=(("requisition_code",),),
        notes="本表是招聘需求生命周期而不是版本表；重大人数或岗位变更应关闭旧需求并新建 requisition_code，普通状态推进进入审计。",
    ),
    T(
        "hr_application", "候选申请", "hr",
        "记录自然人对一个招聘需求的一次申请身份和来源；阶段变化只追加到 hr_application_stage_event。",
        "人员 × 招聘需求 × 一次申请一行", "HR 招聘流程",
        ("BakeryOps", "分析/BI"), "JobStreet、WhatsApp、人工录入或其他渠道", "REQUIRED",
        [
            ID("application_id", "申请ID", "一次候选申请稳定主键。"),
            ID("person_id", "人员ID", "申请人自然人身份。", fk="hr_person.person_id"),
            ID("job_requisition_id", "招聘需求ID", "申请对应正式需求。", fk="hr_job_requisition.job_requisition_id"),
            ID("source_system_id", "来源系统ID", "提供申请的招聘渠道。", fk="app_source_system.source_system_id"),
            F("source_application_id", "外部申请ID", "text", "招聘平台或来源中的稳定申请编号。", "实现同步幂等。", nullable=True, sensitive="internal", example="js_998120"),
            F("applied_at", "申请时间", "timestamptz", "候选人提交或被录入的时间。", "招聘漏斗计时起点。", example="2026-08-08T15:00:00+08:00"),
        ], standard="manual", uniques=(("source_system_id", "source_application_id"),),
        nulls_distinct_uniques=(("source_system_id", "source_application_id"),),
        notes="当前招聘阶段由 v_hr_application_current_stage 确定性派生；录用关系由 hr_employment.origin_application_id 单向连接，避免双向冗余外键。",
    ),
    T(
        "hr_application_stage_event", "候选申请阶段事件", "hr",
        "只追加保存候选申请每次进入新阶段的时间、原因、来源和操作者，使漏斗和停留时长可以重建。",
        "候选申请 × 一次阶段迁移一行", "HR 招聘流程或渠道同步",
        ("BakeryOps", "分析/BI"), "HR操作、候选人动作或招聘渠道回执", "REQUIRED",
        [
            ID("application_stage_event_id", "阶段事件ID", "一次阶段迁移稳定主键。"),
            ID("application_id", "申请ID", "阶段变化所属候选申请。", fk="hr_application.application_id"),
            ID("source_system_id", "来源系统ID", "阶段回执来自外部招聘平台时记录；内部人工动作可为空。", fk="app_source_system.source_system_id", nullable=True),
            ID("job_run_id", "任务运行ID", "自动同步或规则推进阶段时连接具体任务运行。", fk="app_job_run.job_run_id", nullable=True),
            ID("actor_user_id", "操作账号ID", "人工确认阶段变化的应用账号；外部自动回执可为空。", fk="app_user.user_id", nullable=True),
            F("event_key", "阶段事件幂等键", "text", "写入方为本次业务迁移生成的全局唯一稳定键。", "重试不重复制造阶段事件。", unique=True, example="application:...:stage:INTERVIEW:20260810T090000Z"),
            F("from_stage", "原阶段", "text", "迁移前阶段；申请建立时的首个 NEW 事件可为空。", "验证状态机顺序。", nullable=True, example="CONTACTING"),
            F("to_stage", "新阶段", "text", "NEW、CONTACTING、INTERVIEW、TRIAL、OFFER、HIRED、REJECTED、WITHDRAWN 或 TALENT_POOL。", "形成唯一可重建的招聘漏斗事实。", example="INTERVIEW"),
            F("reason_code", "阶段原因", "text", "拒绝、退出、停滞或人工推进的标准原因代码。", "分析流程问题而不依赖自由文本。", nullable=True, example="NO_RESPONSE"),
            F("occurred_at", "阶段发生时间", "timestamptz", "候选申请实际进入新阶段的时间。", "计算各阶段停留时长。", example="2026-08-10T09:00:00+08:00"),
            F("evidence", "阶段证据", "jsonb", "不含非必要敏感信息的渠道回执、预约或审批引用。", "支持复核而不把自由文本当连接键。", default="'{}'::jsonb", sensitive="internal", example='{"appointment_id":"..."}'),
        ], standard="immutable", mutation_policy="APPEND_ONLY_DECISION_RECORD", uniques=(("event_key",),),
        notes="from_stage 保存写入当刻声明的前置状态，用来检测并发或非法迁移；它不是当前阶段副本。v_hr_application_current_stage 从 to_stage 事件序列派生当前阶段，并核对相邻事件的 from_stage。",
        checks=("from_stage IS NULL OR from_stage <> to_stage", "num_nonnulls(source_system_id, job_run_id, actor_user_id) >= 1"),
        retention="按招聘隐私政策保留；分析可去标识，原始阶段事件不可覆盖",
    ),
    T(
        "hr_appointment", "面试试工预约", "hr",
        "记录候选人面试、试工或文件办理的一次预约及其实际执行结果；试工不再另建一对一结果表。",
        "申请 × 一次预约一行", "HR 招聘流程",
        ("BakeryOps",), "HR与候选人确认", "REQUIRED",
        [
            ID("appointment_id", "预约ID", "一次预约稳定主键。"),
            ID("application_id", "申请ID", "预约所属申请。", fk="hr_application.application_id"),
            ID("location_id", "地点ID", "预约发生地点；线上预约可为空。", fk="ops_location.location_id", nullable=True),
            F("appointment_type", "预约类型", "text", "INTERVIEW、TRIAL、DOCUMENT 或 OTHER。", "决定后续表和提醒。", example="TRIAL"),
            F("scheduled_start", "计划开始", "timestamptz", "预约开始时间。", "提醒和准时率。", example="2026-08-12T10:00:00+08:00"),
            F("scheduled_end", "计划结束", "timestamptz", "预约结束时间。", "资源安排。", nullable=True, example="2026-08-12T14:00:00+08:00"),
            F("status", "预约状态", "text", "PROPOSED、CONFIRMED、COMPLETED、NO_SHOW、STOPPED、CANCELLED 或 RESCHEDULED。", "招聘漏斗和到场率。", example="CONFIRMED"),
            F("confirmed_at", "确认时间", "timestamptz", "候选人或HR确认时间。", "区分已安排与已确认。", nullable=True, example="2026-08-10T10:00:00+08:00"),
            ID("confirmed_by_user_id", "确认账号", "内部确认该预约的账号。", fk="app_user.user_id", nullable=True),
            F("actual_start", "实际开始", "timestamptz", "候选人实际到场开始时间；尚未开始为空。", "计算准时率和实际时长。", nullable=True, example="2026-08-12T10:05:00+08:00"),
            F("actual_end", "实际结束", "timestamptz", "预约或试工实际结束时间。", "计算执行时长。", nullable=True, example="2026-08-12T14:00:00+08:00"),
            F("trial_outcome", "试工结论", "text", "仅 TRIAL 类型使用：PASS、CONDITIONAL_PASS、FAIL 或 INCOMPLETE。", "保留试工最终结果；结构化评分仍写 hr_assessment。", nullable=True, example="PASS"),
            F("safety_incident", "是否安全事件", "boolean", "TRIAL 类型期间是否发生安全或重大红线。", "触发人工升级；非试工默认为 false。", default="false", example="false"),
            F("execution_note", "执行说明", "text", "实际到场、异常或试工结论的必要补充。", "保留执行证据，不重复结构化评分。", nullable=True, sensitive="personal", example="按SOP完成全部工序"),
        ], standard="manual", checks=(
            "scheduled_end IS NULL OR scheduled_end > scheduled_start",
            "actual_end IS NULL OR actual_start IS NULL OR actual_end >= actual_start",
            "trial_outcome IS NULL OR appointment_type = 'TRIAL'",
        ),
        notes="预约与实际执行是同一一对一生命周期；评估仍通过 hr_assessment.appointment_id 一对多连接。",
    ),
    T(
        "hr_assessment", "候选人评估", "hr",
        "保存一次结构化评估的建议、红线结论、评估者和模板版本；总分由明细视图派生。",
        "申请 × 评估类型 × 一次评估一行", "HR或业务面试官",
        ("BakeryOps", "分析/BI"), "面试、试工或审核", "REQUIRED",
        [
            ID("assessment_id", "评估ID", "一次候选评估稳定主键。"),
            ID("application_id", "申请ID", "被评估候选申请。", fk="hr_application.application_id"),
            ID("appointment_id", "预约ID", "对应面试/试工预约；无预约评估可为空。", fk="hr_appointment.appointment_id", nullable=True),
            ID("assessor_employment_id", "评估人雇佣ID", "执行评估的员工。", fk="hr_employment.employment_id"),
            F("assessment_type", "评估类型", "text", "SCREENING、INTERVIEW、TRIAL、KPA 或 OTHER。", "选择评分模板和口径。", example="TRIAL"),
            F("template_version", "评分模板版本", "text", "本次使用的评分项模板版本。", "历史分数可解释。", example="trial-kitchen-v3"),
            F("recommendation", "评估建议", "text", "STRONG_HIRE、HIRE、HOLD、NO_HIRE 或 INCOMPLETE。", "形成标准化建议。", example="HIRE"),
            F("red_flag", "是否触发红线", "boolean", "是否存在必须人工处理的红线项。", "红线应阻断自动推进。", default="false", example="false"),
            F("summary", "评估总结", "text", "评估者的必要总结。", "解释分数和建议。", nullable=True, sensitive="personal", example="操作规范，速度需提升"),
            F("assessed_at", "评估时间", "timestamptz", "评估完成时间。", "招聘流程时长。", example="2026-08-12T14:00:00+08:00"),
        ], standard="immutable",
    ),
    T(
        "hr_assessment_score", "评估项目得分", "hr",
        "逐项保存评分、权重、红线和证据，避免只有总分无法解释。",
        "评估 × 评分项目一行", "HR或业务面试官",
        ("BakeryOps", "分析/BI"), "评估模板和评估者输入", "REQUIRED",
        [
            ID("assessment_score_id", "评分行ID", "一条评分项目稳定主键。"),
            ID("assessment_id", "评估ID", "所属候选评估。", fk="hr_assessment.assessment_id"),
            F("criterion_code", "评分项代码", "text", "模板内稳定评分项代码。", "跨评估比较同一能力。", example="FOOD_SAFETY"),
            F("criterion_name", "评分项名称", "text", "评估时的评分项名称快照。", "模板改名后保留历史含义。", example="食品安全意识"),
            F("score", "得分", "numeric(9,4)", "该评分项实际得分。", "形成总分和能力画像。", nullable=True, example="8"),
            F("max_score", "满分", "numeric(9,4)", "该项可得最高分。", "跨模板归一化。", example="10", checks=("max_score > 0",)),
            F("weight", "权重", "numeric(9,6)", "该项进入总分的权重。", "复现总分计算。", default="1", example="1.5", checks=("weight >= 0",)),
            F("is_red_flag", "是否红线项", "boolean", "该项是否触发红线。", "即使总分高也可阻断。", default="false", example="false"),
            F("evidence_note", "评分证据", "text", "支持该分数的具体观察。", "提高评分可审计性。", nullable=True, sensitive="personal", example="洗手流程完整"),
        ], standard="immutable", uniques=(("assessment_id", "criterion_code"),), checks=("score IS NULL OR (score >= 0 AND score <= max_score)",),
    ),
    T(
        "hr_offer", "Offer版本", "hr",
        "版本化保存候选人的岗位、地点、薪酬摘要、有效期和接受状态。",
        "申请 × Offer版本一行", "HR 招聘流程",
        ("BakeryOps", "授权财务"), "招聘审批", "REQUIRED",
        [
            ID("offer_id", "Offer ID", "一版 Offer 稳定主键。"),
            ID("application_id", "申请ID", "Offer 对应候选申请。", fk="hr_application.application_id"),
            ID("supersedes_offer_id", "被替代Offer ID", "本版替代的上一版 Offer。", fk="hr_offer.offer_id", nullable=True),
            ID("location_id", "地点ID", "Offer 主要工作地点。", fk="ops_location.location_id"),
            ID("role_id", "岗位ID", "Offer 标准岗位。", fk="ops_role.role_id", nullable=True),
            F("version_no", "版本号", "integer", "申请内 Offer 递增版本。", "不覆盖谈判历史。", example="2", checks=("version_no > 0",)),
            F("employment_type", "用工类型", "text", "拟议用工类型。", "创建 employment 时继承。", example="FULL_TIME"),
            F("proposed_start_date", "拟入职日", "date", "Offer 中拟定的开始日期。", "入职计划。", example="2026-09-01"),
            F("compensation_schema_version", "薪酬结构版本", "text", "compensation_summary 对应的固定 JSON Schema 版本。", "冻结币种、薪酬项目、周期和金额类型，避免合同与预算解释漂移。", default="'offer-compensation-v1'", sensitive="internal", example="offer-compensation-v1"),
            F("compensation_summary", "薪酬摘要", "jsonb", "按 compensation_schema_version 校验的结构化薪酬项目和币种；未知键拒绝且仅授权人员可见。", "支持合同和预算，但不把自由文本薪酬散落。", sensitive="restricted", example='{"currency":"MYR","monthly_base":2500}'),
            F("expires_at", "Offer到期时间", "timestamptz", "候选人最迟接受时间。", "自动判断失效。", nullable=True, example="2026-08-20T23:59:59+08:00"),
            F("status", "Offer状态", "text", "DRAFT、SENT、ACCEPTED、DECLINED、EXPIRED、WITHDRAWN 或 SUPERSEDED。", "招聘漏斗和入职门禁。", example="SENT"),
            F("responded_at", "候选回应时间", "timestamptz", "接受或拒绝时间。", "招聘时长。", nullable=True, example="2026-08-15T10:00:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("application_id", "version_no"),),
        retention="按劳动与招聘隐私政策保留",
        notes="DRAFT 只能通过受控函数按 compensation_schema_version 校验 compensation_summary，拒绝未知键和无币种金额；SENT 后岗位、地点、薪酬、版本号和到期时间冻结，只允许受控写入终态回应；条款变化必须新建 Offer 版本。",
    ),
    T(
        "hr_onboarding_task", "入职任务", "hr",
        "逐项跟踪合同、证件、系统账号、培训和门店准备等入职事项。",
        "雇佣关系 × 入职任务代码一行", "HR 入职流程",
        ("BakeryOps",), "Offer接受后按模板生成", "REQUIRED",
        [
            ID("onboarding_task_id", "入职任务ID", "一项入职任务稳定主键。"),
            ID("employment_id", "雇佣ID", "任务所属新雇佣关系。", fk="hr_employment.employment_id"),
            F("task_code", "任务代码", "text", "标准化入职任务代码。", "跨员工统计完成率。", example="FOOD_HANDLER_CERT"),
            F("task_name", "任务名称", "text", "任务显示名称快照。", "便于执行。", example="食品处理证书核验"),
            F("due_at", "截止时间", "timestamptz", "任务应完成时间。", "判断是否阻断上岗。", nullable=True, example="2026-08-31T18:00:00+08:00"),
            F("is_blocking", "是否阻断上岗", "boolean", "未完成时是否禁止正式排班。", "形成清晰上岗门禁。", default="false", example="true"),
            F("status", "任务状态", "text", "PENDING、IN_PROGRESS、COMPLETED、WAIVED 或 CANCELLED。", "跟踪入职准备。", default="'PENDING'", example="COMPLETED"),
            F("completed_at", "完成时间", "timestamptz", "任务完成或豁免时间。", "计算及时率。", nullable=True, example="2026-08-28T10:00:00+08:00"),
            ID("completed_by_user_id", "确认账号", "确认完成或豁免的账号。", fk="app_user.user_id", nullable=True),
            F("evidence", "完成证据", "jsonb", "文件哈希、证书编号或系统账号引用。", "证明任务完成且限制敏感附件暴露。", default="'{}'::jsonb", sensitive="restricted", example='{"certificate_ref":"..."}'),
        ], standard="manual", uniques=(("employment_id", "task_code"),),
    ),
    T(
        "hr_employee_event", "员工事件", "hr",
        "记录转正、调动、停职、奖惩、离职等不可变人事事件。",
        "雇佣关系 × 一次事件一行", "HR 人事流程",
        ("BakeryOps", "授权财务", "分析/BI"), "HR人工确认或批准流程", "REQUIRED",
        [
            ID("employee_event_id", "员工事件ID", "一次人事事件稳定主键。"),
            ID("employment_id", "雇佣ID", "事件所属雇佣关系。", fk="hr_employment.employment_id"),
            F("event_type", "事件类型", "text", "CONFIRMATION、TRANSFER、PROMOTION、DISCIPLINE、SUSPENSION、RESIGNATION、TERMINATION 或 OTHER。", "统一人事历史口径。", example="TRANSFER"),
            F("effective_date", "生效日期", "date", "事件业务生效日期。", "与排班、组织和成本按有效期连接。", example="2026-09-01"),
            ID("from_location_id", "原地点ID", "调动前地点；不适用为空。", fk="ops_location.location_id", nullable=True),
            ID("to_location_id", "新地点ID", "调动后地点；不适用为空。", fk="ops_location.location_id", nullable=True),
            F("event_schema_version", "事件结构版本", "text", "event_data 对应的事件类型结构版本。", "保证批准的人事事件在字段扩展后仍可验证和解释。", default="'hr-employee-event-v1'", example="hr-employee-event-v1"),
            F("event_data", "事件结构数据", "jsonb", "按事件类型保存批准后的非通用字段。", "避免无意义宽表，同时要求对应 JSON Schema。", default="'{}'::jsonb", sensitive="restricted", example='{"new_title":"Shift Lead"}'),
            F("reason_code", "原因代码", "text", "离职、处分等标准原因。", "汇总分析且减少自由文本。", nullable=True, sensitive="personal", example="VOLUNTARY_RESIGNATION"),
            F("note", "事件说明", "text", "必要的受限说明。", "审计例外。", nullable=True, sensitive="restricted", example="Approved transfer"),
            ID("recorded_by_user_id", "登记账号", "确认并登记该不可变人事事件的应用账号。", fk="app_user.user_id"),
        ], standard="immutable", mutation_policy="APPEND_ONLY_DECISION_RECORD", retention="按劳动法规永久或长期保留",
        notes="已批准的人事事件不可修改；错误通过新的纠正或冲销事件表达，禁止覆盖原事件。event_data 必须按 event_type + event_schema_version 的固定 schema 经受控写函数校验，未知键拒绝。",
    ),
    T(
        "hr_screening_rule", "招聘筛选规则", "hr",
        "保存经人工批准、带证据和适用范围的招聘筛选规则。",
        "一个规则版本一行", "HR规则审核流程",
        ("BakeryOps", "分析/BI"), "历史员工结果分析和人工批准", "REQUIRED",
        [
            ID("screening_rule_id", "筛选规则ID", "一版筛选规则稳定主键。"),
            F("rule_code", "规则代码", "text", "稳定规则标识。", "程序执行和版本管理。", example="RETENTION_AVAILABILITY"),
            F("version_no", "版本号", "integer", "规则代码内递增版本。", "历史决策可解释。", example="2", checks=("version_no > 0",)),
            ID("role_id", "适用岗位ID", "规则只适用某岗位时记录。", fk="ops_role.role_id", nullable=True),
            F("rule_type", "规则类型", "text", "ELIGIBILITY、RISK_SIGNAL 或 QUESTION_PROMPT。", "禁止把弱相关信号变成自动拒绝。", example="RISK_SIGNAL"),
            F("rule_schema_version", "筛选规则结构版本", "text", "rule_definition 对应的固定 JSON Schema 版本。", "冻结允许的输入字段、操作符和输出结构。", default="'hr-screening-rule-v1'", example="hr-screening-rule-v1"),
            F("rule_definition", "规则定义", "jsonb", "按 rule_type + rule_schema_version 校验的条件和输出；未知键及受保护歧视字段拒绝。", "可测试执行；不得包含受保护歧视条件。", example='{"field":"availability","operator":"contains"}'),
            F("evidence_summary", "证据摘要", "text", "规则依据、样本和限制。", "明确相关不等于因果。", example="样本15，需人工复核"),
            F("sample_size", "样本量", "integer", "提炼规则使用的样本数。", "低样本警示。", nullable=True, example="15", checks=("sample_size IS NULL OR sample_size > 0",)),
            F("confidence", "置信度", "numeric(5,4)", "规则证据的 0 至 1 评分。", "只决定提示强度。", nullable=True, example="0.7200"),
            F("status", "规则状态", "text", "DRAFT、APPROVED、ACTIVE 或 RETIRED。", "只有 ACTIVE 才可提示。", example="ACTIVE"),
            ID("approved_by_user_id", "批准账号", "人工批准规则的账号。", fk="app_user.user_id", nullable=True),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("rule_code", "version_no"),),
        notes="DRAFT 写入函数必须按 rule_type + rule_schema_version 校验 rule_definition、拒绝未知键和受保护歧视字段；APPROVED 或 ACTIVE 后规则定义、证据与版本号冻结，新结论必须新建版本。",
    ),
    T(
        "hr_training_course", "培训课程", "hr",
        "维护课程稳定身份，内容和考核规则放在版本表。",
        "一个培训课程一行", "HR培训管理",
        ("BakeryOps", "分析/BI"), "培训负责人配置", "REQUIRED",
        [
            ID("training_course_id", "课程ID", "培训课程稳定身份。"),
            F("course_code", "课程代码", "text", "企业内部唯一课程代码。", "岗位要求和培训指派的连接键。", unique=True, example="FOOD_SAFETY_L1"),
            F("course_name", "课程名称", "text", "当前显示名称。", "界面和证书展示。", example="食品安全一级"),
            F("course_type", "课程类型", "text", "MANDATORY、ROLE_SKILL、LEADERSHIP 或 OTHER。", "培训计划分层。", example="MANDATORY"),
            F("status", "课程状态", "text", "DRAFT、ACTIVE 或 RETIRED。", "停用课程不删除历史结果。", default="'DRAFT'", example="ACTIVE"),
        ], standard="manual", uniques=(("course_code",),),
    ),
    T(
        "hr_training_course_version", "培训课程版本", "hr",
        "冻结课程内容、及格线、有效期和考核规则版本。",
        "课程 × 版本号一行", "HR培训管理",
        ("BakeryOps", "分析/BI"), "培训负责人发布", "REQUIRED",
        [
            ID("training_course_version_id", "课程版本ID", "一版课程稳定身份。"),
            ID("training_course_id", "课程ID", "所属稳定课程。", fk="hr_training_course.training_course_id"),
            F("version_no", "版本号", "integer", "课程内递增版本。", "保留旧员工当时所学内容。", example="3", checks=("version_no > 0",)),
            F("content_uri", "课程内容地址", "text", "受控文档或学习内容地址。", "课程交付；访问权限另行控制。", nullable=True, sensitive="internal", example="lark://doc/..."),
            F("content_sha256", "内容校验值", "char(64)", "课程内容文件或规范化文本的校验值。", "证明员工完成的是哪个版本。", nullable=True, example="09fd...64位十六进制"),
            F("pass_score", "及格分", "numeric(9,4)", "本版本考核及格线。", "自动判定培训结果。", nullable=True, example="80"),
            F("validity_days", "资格有效天数", "integer", "通过后资格有效天数；永久有效为空。", "岗位资格到期判断。", nullable=True, example="365", checks=("validity_days IS NULL OR validity_days > 0",)),
            F("effective_from", "生效时间", "timestamptz", "新指派开始使用该版本的时间。", "版本门禁。", example="2026-08-01T00:00:00+08:00"),
            F("effective_to", "失效时间", "timestamptz", "停止新指派的时间。", "保留历史结果。", nullable=True, example="2027-01-01T00:00:00+08:00"),
            F("status", "版本状态", "text", "DRAFT、PUBLISHED 或 RETIRED。", "只有 PUBLISHED 可指派。", example="PUBLISHED"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("training_course_id", "version_no"),), checks=("effective_to IS NULL OR effective_to > effective_from",),
        exclusions=("NO_OVERLAP(training_course_id, tstzrange(effective_from, effective_to, '[)')) WHERE status = 'PUBLISHED'",),
        notes="DRAFT 可编辑；PUBLISHED 后课程内容哈希、及格线、资格有效期和生效起点冻结，更新必须新建版本。",
    ),
    T(
        "hr_training_assignment", "培训指派", "hr",
        "记录员工被要求完成的具体课程版本、期限和原因。",
        "雇佣关系 × 课程版本 × 一次指派一行", "HR或门店培训负责人",
        ("BakeryOps", "分析/BI"), "岗位要求、入职任务或人工安排", "REQUIRED",
        [
            ID("training_assignment_id", "培训指派ID", "一次培训指派稳定主键。"),
            ID("employment_id", "雇佣ID", "被指派员工。", fk="hr_employment.employment_id"),
            ID("training_course_version_id", "课程版本ID", "必须完成的具体课程版本。", fk="hr_training_course_version.training_course_version_id"),
            F("assignment_reason", "指派原因", "text", "ONBOARDING、ROLE_REQUIREMENT、RENEWAL、REMEDIAL 或 MANUAL。", "解释为什么需要培训。", example="ROLE_REQUIREMENT"),
            F("assigned_at", "指派时间", "timestamptz", "培训要求产生时间。", "计算培训周期。", default="now()", example="2026-08-20T09:00:00+08:00"),
            F("due_at", "截止时间", "timestamptz", "培训应完成时间。", "资格门禁和逾期提醒。", nullable=True, example="2026-08-31T18:00:00+08:00"),
            F("status", "指派状态", "text", "ASSIGNED、IN_PROGRESS、COMPLETED、WAIVED、EXPIRED 或 CANCELLED。", "培训进度。", default="'ASSIGNED'", example="ASSIGNED"),
            ID("assigned_by_user_id", "指派账号", "发起指派的账号；系统生成可为空并追踪 job_run。", fk="app_user.user_id", nullable=True),
        ], standard="mutable", mutation_policy="CONTROLLED_WORKFLOW",
    ),
    T(
        "hr_training_result", "培训结果", "hr",
        "保存一次课程学习或考试的分数、结果和资格有效期。",
        "培训指派 × 一次尝试一行", "培训系统或负责人",
        ("BakeryOps", "分析/BI"), "考试、实操或人工核验", "REQUIRED",
        [
            ID("training_result_id", "培训结果ID", "一次培训尝试稳定主键。"),
            ID("training_assignment_id", "培训指派ID", "所属培训指派。", fk="hr_training_assignment.training_assignment_id"),
            F("attempt_no", "尝试次数", "integer", "该指派内从 1 开始的尝试序号。", "保留补考历史。", example="1", checks=("attempt_no > 0",)),
            F("score", "得分", "numeric(9,4)", "考试或实操分数。", "与课程版本及格线比较。", nullable=True, example="86"),
            F("result", "结果", "text", "PASS、FAIL、INCOMPLETE 或 WAIVED。", "岗位资格判断。", example="PASS"),
            F("completed_at", "完成时间", "timestamptz", "本次尝试完成时间。", "资格生效起点。", example="2026-08-25T15:00:00+08:00"),
            F("valid_from", "资格生效时间", "timestamptz", "通过后资格开始有效时间。", "班表资格门禁。", nullable=True, example="2026-08-25T15:00:00+08:00"),
            F("valid_to", "资格失效时间", "timestamptz", "通过资格到期时间。", "到期后不能继续安排关键岗位。", nullable=True, example="2027-08-25T15:00:00+08:00"),
            ID("verified_by_user_id", "核验账号", "人工核验结果的账号；自动考试可为空。", fk="app_user.user_id", nullable=True),
            F("evidence", "结果证据", "jsonb", "证书编号、答题摘要或实操核验引用。", "支持资格审计。", default="'{}'::jsonb", sensitive="restricted", example='{"certificate":"FS-2026-129"}'),
        ], standard="immutable", uniques=(("training_assignment_id", "attempt_no"),), checks=("valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from",),
    ),
    T(
        "ops_role", "标准岗位", "ops",
        "维护排班、招聘和培训共同使用的标准岗位身份。",
        "一个标准岗位一行", "BakeryOps 运营主数据",
        ("BakeryOps", "HR", "分析/BI"), "运营与HR共同批准", "REQUIRED",
        [
            ID("role_id", "岗位ID", "跨招聘、培训和班表稳定岗位身份。"),
            F("role_code", "岗位代码", "text", "程序和业务共同使用的唯一代码。", "跨模块连接。", unique=True, example="KITCHEN_BAKER"),
            F("role_name", "岗位名称", "text", "当前岗位显示名称。", "界面展示。", example="烘焙师"),
            F("role_family", "岗位族", "text", "KITCHEN、FRONT、LOGISTICS、MANAGEMENT 或 SUPPORT。", "组织分析和默认规则。", example="KITCHEN"),
            F("is_critical", "是否默认关键岗位", "boolean", "该岗位是否通常属于必须明确覆盖的关键岗位。", "班表发布门禁的默认值，具体班次可覆盖。", default="false", example="true"),
            F("status", "岗位状态", "text", "ACTIVE 或 RETIRED。", "保留历史岗位。", default="'ACTIVE'", example="ACTIVE"),
        ], standard="manual", uniques=(("role_code",),),
    ),
    T(
        "ops_station", "标准工位", "ops",
        "维护地点内可排班的工位或工作区域。",
        "一个标准工位定义一行", "BakeryOps 运营主数据",
        ("BakeryOps", "分析/BI"), "运营配置", "REQUIRED",
        [
            ID("station_id", "工位ID", "工位稳定身份。"),
            F("station_code", "工位代码", "text", "企业范围唯一或按批准规则唯一的工位代码。", "班表和工时连接。", unique=True, example="PAV_OVEN_1"),
            F("station_name", "工位名称", "text", "当前工位显示名称。", "班表展示。", example="烤箱一号位"),
            F("station_type", "工位类型", "text", "PRODUCTION、SERVICE、CASHIER、CLEANING、LOGISTICS 或 OTHER。", "工作量和人效分组。", example="PRODUCTION"),
            ID("default_location_id", "默认地点ID", "工位固定在某地点时记录；可复用标准工位为空。", fk="ops_location.location_id", nullable=True),
            F("capacity", "并发容量", "integer", "该工位可同时安排的最大人数。", "防止超排。", nullable=True, example="2", checks=("capacity IS NULL OR capacity > 0",)),
            F("status", "工位状态", "text", "ACTIVE、MAINTENANCE 或 RETIRED。", "维护期间不能排班。", default="'ACTIVE'", example="ACTIVE"),
        ], standard="manual", uniques=(("station_code",),),
    ),
    T(
        "ops_role_training_requirement", "岗位培训要求", "ops",
        "定义岗位需要哪些课程、是否强制和有效期规则。",
        "岗位 × 课程 × 生效区间一行", "运营与HR共同维护",
        ("BakeryOps", "HR", "分析/BI"), "岗位资格政策", "REQUIRED",
        [
            ID("role_training_requirement_id", "要求ID", "一条岗位培训要求稳定主键。"),
            ID("role_id", "岗位ID", "被约束岗位。", fk="ops_role.role_id"),
            ID("training_course_id", "课程ID", "岗位要求课程。", fk="hr_training_course.training_course_id"),
            F("is_mandatory", "是否强制", "boolean", "未满足时是否禁止排班到该岗位。", "关键岗位资格门禁。", default="true", example="true"),
            F("minimum_result", "最低结果", "text", "通常 PASS；允许政策定义其他结果。", "资格视图判断。", default="'PASS'", example="PASS"),
            F("valid_from", "生效日期", "date", "要求开始生效日期。", "历史班表按当时规则判断。", example="2026-08-01"),
            F("valid_to", "失效日期上界", "date", "要求停止生效的日期上界，该日期本身不再适用。", "以左闭右开区间保留历史并避免相邻规则重复命中。", nullable=True, example="2027-01-01"),
        ], standard="manual", uniques=(("role_id", "training_course_id", "valid_from"),), checks=("valid_to IS NULL OR valid_to > valid_from",),
        exclusions=("NO_OVERLAP(role_id, training_course_id, daterange(valid_from, valid_to, '[)'))",),
    ),
    T(
        "ops_shift_plan_version", "班表版本", "ops",
        "直接保留某地点某营业日班表每次草稿、资格校验、批准、发布或取消，不再另建空壳班表主单。",
        "地点 × 营业日 × 版本号一行", "BakeryOps；审批人改变状态",
        ("BakeryOps", "HR", "财务网站", "分析/BI"), "工作量运行或上一版本", "REQUIRED",
        [
            ID("shift_plan_version_id", "班表版本ID", "一版班表稳定身份。"),
            ID("location_id", "地点ID", "班表覆盖地点。", fk="ops_location.location_id"),
            F("business_date", "营业日期", "date", "班表服务的营业日。", "与销售、生产计划和实际工时连接。", example="2026-08-10"),
            ID("source_job_run_id", "来源导入任务ID", "班表由 Excel/Lark/其他批量来源导入时连接记录文件哈希、解析器版本和完成时间的任务运行；纯人工建立时为空。", fk="app_job_run.job_run_id", nullable=True),
            ID("workload_run_id", "工作量运行ID", "班表需求采用的工作量计算。", fk="ops_workload_run.workload_run_id", nullable=True),
            ID("based_on_version_id", "基础版本ID", "本版从哪一旧版复制。", fk="ops_shift_plan_version.shift_plan_version_id", nullable=True),
            F("version_no", "版本号", "integer", "同一地点和营业日内递增版本。", "版本排序。", example="2", checks=("version_no > 0",)),
            F("status", "版本状态", "text", "DRAFT、VALIDATING、APPROVED、PUBLISHED、SUPERSEDED、REJECTED 或 CANCELLED。", "只有 PUBLISHED 才是正式班表；整日取消必须追加 CANCELLED 版本。", example="PUBLISHED"),
            F("validation_summary", "校验摘要", "jsonb", "关键岗位缺口、资格违规和人数差异。", "发布前清楚展示门禁。", default="'{}'::jsonb", example='{"critical_gaps":0}'),
            ID("approved_by_user_id", "批准账号", "批准班表的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "班表批准时间。", "审计。", nullable=True, example="2026-08-09T16:00:00+08:00"),
            F("published_at", "发布时间", "timestamptz", "班表正式对员工生效时间。", "通知和后续实际对比起点。", nullable=True, example="2026-08-09T16:05:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("location_id", "business_date", "version_no"),),
        notes="R6 终审将 ops_shift_plan 合并到本表：location_id + business_date 就是跨版本自然身份，另存主单 UUID 与可变头状态没有新增事实。草稿和校验阶段可受控修改；PUBLISHED、REJECTED、CANCELLED 或 SUPERSEDED 后版本、需求和指派冻结，任何变更复制为新版本。",
    ),
    T(
        "ops_shift_requirement", "班次岗位需求", "ops",
        "明确每个时段需要的岗位、工位、人数和关键岗位属性。",
        "班表版本 × 时段 × 岗位 × 工位一行", "BakeryOps 排班流程",
        ("BakeryOps", "HR", "分析/BI"), "工作量行加人工调整", "REQUIRED",
        [
            ID("shift_requirement_id", "班次需求ID", "一条岗位需求稳定主键。"),
            ID("shift_plan_version_id", "班表版本ID", "所属班表版本。", fk="ops_shift_plan_version.shift_plan_version_id"),
            ID("workload_line_id", "工作量行ID", "产生该需求的工作量行；纯人工需求可为空。", fk="ops_workload_line.workload_line_id", nullable=True),
            ID("role_id", "岗位ID", "必须覆盖的岗位。", fk="ops_role.role_id"),
            ID("station_id", "工位ID", "具体工作工位；岗位级需求可为空。", fk="ops_station.station_id", nullable=True),
            F("shift_start", "班次开始", "timestamptz", "需求时段绝对开始时间。", "跨午夜不歧义。", example="2026-08-10T06:00:00+08:00"),
            F("shift_end", "班次结束", "timestamptz", "需求时段绝对结束时间。", "计算需求工时。", example="2026-08-10T14:00:00+08:00"),
            F("required_headcount", "需求人数", "integer", "该时段岗位所需人数。", "班表人员缺口。", example="2", checks=("required_headcount > 0",)),
            F("required_work_minutes", "需求分钟", "numeric(18,4)", "该需求行总工作分钟。", "与分配和实际工时比较。", example="960", checks=("required_work_minutes >= 0",)),
            F("is_critical", "是否关键岗位", "boolean", "本次班表中是否必须明确有人且满足资格。", "发布硬门禁。", default="false", example="true"),
            F("note", "需求说明", "text", "人工调整或特殊要求。", "解释偏离工作量结果。", nullable=True, example="开店前必须两人"),
        ], standard="immutable",
        uniques=(("shift_plan_version_id", "shift_start", "shift_end", "role_id", "station_id"),),
        nulls_not_distinct_uniques=(("shift_plan_version_id", "shift_start", "shift_end", "role_id", "station_id"),),
        checks=("shift_end > shift_start",),
    ),
    T(
        "ops_shift_assignment", "班次员工指派", "ops",
        "把合资格员工明确指派到班表时段、岗位和工位。",
        "班次需求 × 雇佣关系 × 一段指派一行", "BakeryOps 排班流程",
        ("BakeryOps", "HR", "财务网站", "分析/BI"), "人工排班或批准算法", "REQUIRED",
        [
            ID("shift_assignment_id", "班次指派ID", "一段员工班次指派稳定主键。"),
            ID("shift_requirement_id", "班次需求ID", "被覆盖的岗位需求。", fk="ops_shift_requirement.shift_requirement_id"),
            ID("employment_id", "雇佣ID", "被安排员工。", fk="hr_employment.employment_id"),
            F("assigned_start", "指派开始", "timestamptz", "员工在该岗位实际计划开始时间。", "允许一人分段多岗位。", example="2026-08-10T06:00:00+08:00"),
            F("assigned_end", "指派结束", "timestamptz", "员工在该岗位计划结束时间。", "计算计划工时。", example="2026-08-10T10:00:00+08:00"),
            F("break_minutes", "休息分钟", "integer", "该指派内不计工作时间的计划休息。", "计划净工时。", default="0", example="30", checks=("break_minutes >= 0",)),
            F("eligibility_status", "资格状态", "text", "ELIGIBLE、MISSING_TRAINING、EXPIRED_TRAINING、INACTIVE_EMPLOYMENT 或 OVERRIDDEN。", "关键岗位发布门禁。", example="ELIGIBLE"),
            F("override_reason", "资格例外原因", "text", "经批准绕过资格时的原因。", "不得静默忽略培训要求。", nullable=True, example="紧急支援，主管现场监督"),
            ID("override_approved_by_user_id", "例外批准账号", "批准资格例外的账号。", fk="app_user.user_id", nullable=True),
            F("note", "指派说明", "text", "只属于该员工本段指派的来源备注或人工说明。", "承接旧班表逐人 notes，避免误放到多人共享的岗位需求说明。", nullable=True, sensitive="internal", example="临时换到收银台支援"),
            F("status", "指派状态", "text", "PLANNED、CONFIRMED、CANCELLED、NO_SHOW 或 COMPLETED。", "计划与实际对比。", default="'PLANNED'", example="CONFIRMED"),
        ], standard="manual",
        uniques=(("shift_requirement_id", "employment_id", "assigned_start", "assigned_end"),),
        checks=("assigned_end > assigned_start",),
        notes="同一班表版本内，一个 employment_id 的有效指派不得时间重叠；由于 shift_plan_version_id 可经 requirement 确定，为避免重复外键，本表不再复制该字段，实施时由延迟约束触发器跨 requirement 校验。已发布版本冻结，改班必须生成新版本。",
    ),
    T(
        "hr_timesheet_sync_batch", "工时同步批次", "hr",
        "记录一次 Lark 或其他工时来源同步的窗口、解析版本和完整性。",
        "来源 × 时间窗口 × 一次同步一行", "BakeryOps 工时同步任务",
        ("BakeryOps", "财务网站", "分析/BI"), "Lark工时或批准来源", "REQUIRED",
        [
            ID("timesheet_sync_batch_id", "工时批次ID", "一次工时同步稳定身份。"),
            ID("job_run_id", "任务运行ID", "执行同步的自动任务。", fk="app_job_run.job_run_id"),
            ID("source_system_id", "来源系统ID", "提供工时记录的来源。", fk="app_source_system.source_system_id"),
            F("window_start", "同步窗口开始", "timestamptz", "请求工时数据的起点。", "解释覆盖范围。", example="2026-08-01T00:00:00+08:00"),
            F("window_end", "同步窗口结束", "timestamptz", "请求工时数据的终点。", "避免漏数或重复。", example="2026-08-09T00:00:00+08:00"),
            F("source_batch_id", "外部批次ID", "text", "来源提供的稳定导出、报表或同步批次ID。", "来源具备批次身份时直接用于跨重跑幂等。", nullable=True, sensitive="internal", example="lark-attendance-export-20260808"),
            F("payload_sha256", "来源内容校验值", "char(64)", "本次工时响应或规范化文件的 SHA-256。", "来源无稳定批次ID时识别同一内容，并检测同窗口内容更正。", nullable=True, example="4c1a...64位十六进制"),
            F("idempotency_key", "批次幂等键", "char(64)", "按来源、窗口、外部批次ID或内容校验值及解析版本规范化计算的 SHA-256。", "同一输入重跑必须恢复同一批次，不能让工时行数增长。", unique=True, example="91da...64位十六进制"),
            F("parser_version", "解析版本", "text", "把来源工时转成标准分钟的代码版本。", "历史重现。", example="lark-timesheet-v2"),
            F("loaded_row_count", "落库行数", "bigint", "成功写入或确认幂等的工时行数。", "完整性监控。", default="0", example="220", checks=("loaded_row_count >= 0",)),
            F("status", "批次状态", "text", "RUNNING、SUCCEEDED、PARTIAL、FAILED 或 REJECTED。", "下游只读取合格批次。", example="SUCCEEDED"),
            F("completed_at", "完成时间", "timestamptz", "同步完成时间。", "数据新鲜度。", nullable=True, example="2026-08-09T01:05:00+08:00"),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL",
        uniques=(("source_system_id", "source_batch_id"), ("idempotency_key",)),
        nulls_distinct_uniques=(("source_system_id", "source_batch_id"),),
        checks=("window_end > window_start", "source_batch_id IS NOT NULL OR payload_sha256 IS NOT NULL"),
        notes="与 POS 增量相同，完全相同的来源输入和 parser_version 必须命中同一 idempotency_key；来源内容变化或解析规则变化才创建新批次。终态后冻结，重跑不得新增重复 entry。",
    ),
    T(
        "hr_timesheet_entry", "实际工时事实", "hr",
        "保存员工在地点、日期和工作区域的实际净工时原值与来源，不把班表当实际工时。",
        "来源工时记录 × 雇佣关系 × 地点 × 工作时段一行", "BakeryOps 工时同步任务",
        ("BakeryOps", "财务网站", "分析/BI"), "Lark工时或批准人工更正", "REQUIRED",
        [
            ID("timesheet_entry_id", "工时记录ID", "一条实际工时稳定主键。"),
            ID("timesheet_sync_batch_id", "工时批次ID", "采集该记录的同步批次。", fk="hr_timesheet_sync_batch.timesheet_sync_batch_id"),
            ID("employment_id", "雇佣ID", "实际工作的员工雇佣关系。", fk="hr_employment.employment_id"),
            ID("location_id", "地点ID", "实际工作地点。", fk="ops_location.location_id"),
            ID("shift_assignment_id", "班次指派ID", "能唯一匹配计划班次时记录；班表扩展包启用前必须为空且不创建该外键。", fk="ops_shift_assignment.shift_assignment_id", fk_activation="EXTENSION_PACK:SHIFT_AND_WORKFORCE", nullable=True),
            ID("role_id", "实际岗位ID", "来源能确认的实际岗位；未知为空。", fk="ops_role.role_id", nullable=True),
            ID("station_id", "实际工位ID", "来源能确认的工作区域；未知为空；班表扩展包启用前必须为空且不创建该外键。", fk="ops_station.station_id", fk_activation="EXTENSION_PACK:SHIFT_AND_WORKFORCE", nullable=True),
            F("source_entry_id", "外部工时ID", "text", "来源系统稳定工时记录ID。", "同步幂等。", sensitive="internal", example="lark_attendance_8812"),
            F("business_date", "营业日期", "date", "按地点切点归属的工作日期。", "与销售和班表连接。", example="2026-08-08"),
            F("clock_in_at", "上班打卡时间", "timestamptz", "来源记录的开始时间。", "核对时段和迟到。", nullable=True, sensitive="personal", example="2026-08-08T08:01:00+08:00"),
            F("clock_out_at", "下班打卡时间", "timestamptz", "来源记录的结束时间。", "核对时段和早退。", nullable=True, sensitive="personal", example="2026-08-08T17:00:00+08:00"),
            F("reported_minutes", "来源报告分钟", "integer", "来源系统返回的原始净工时分钟。", "保留来源原值。", example="480", checks=("reported_minutes >= 0",)),
            F("net_work_minutes", "标准净工时分钟", "integer", "按批准解析规则标准化后的净工作分钟。", "人效和财务人工核对的正式实际工时。", example="480", checks=("net_work_minutes >= 0",)),
            F("break_minutes", "实际休息分钟", "integer", "来源明确报告或批准解析规则能够确定的休息分钟；来源没有该值时为 NULL。", "解释打卡跨度与净工时差，同时区分真实 0 分钟和来源缺失。", nullable=True, example="60", checks=("break_minutes IS NULL OR break_minutes >= 0",)),
            F("quality_status", "质量状态", "text", "COMPLETE、MISSING_IDENTITY、MISSING_CLOCK、OVERLAP 或 MANUAL_OVERRIDE。", "问题记录进入质量队列。", example="COMPLETE"),
            F("source_payload_ref", "来源原值引用", "text", "外部加密文件或对象存储中的原始记录引用。", "需要时复核，不在表内复制整份 PII。", nullable=True, sensitive="restricted", example="s3://.../hash"),
        ], standard="immutable", uniques=(("timesheet_sync_batch_id", "source_entry_id"),),
        checks=("clock_out_at IS NULL OR clock_in_at IS NULL OR clock_out_at >= clock_in_at",),
        retention="按劳动法规保留；普通分析只读取去标识字段",
        notes="同一幂等批次内 (timesheet_sync_batch_id, source_entry_id) 唯一；完全相同输入重跑会复用批次，因此总行数不增长。来源同一 entry 后续被更正时，新 payload_sha256 产生新批次，由只读 current 视图按来源系统、source_entry_id 和获准批次选版。",
    ),
]
