"""Marketing/HBTI, messaging, and AI platform tables."""

from __future__ import annotations

from .model_types import F, ID, T, TableForeignKey


TABLES = [
    # ------------------------------------------------------------------
    # Marketing campaigns, HBTI survey history, rewards
    # ------------------------------------------------------------------
    T(
        "mkt_campaign_version", "营销活动版本", "mkt",
        "一行冻结一个活动代码版本的名称、类型、时间窗、适用地点、参与规则、问卷算法和奖励政策；不再为只有版本表引用的活动另建主档。",
        "活动代码 × 版本号一行", "营销/HBTI后台",
        ("HBTI", "财务网站", "BakeryOps", "分析/BI"), "营销配置和批准", "REQUIRED",
        [
            ID("campaign_version_id", "活动版本ID", "一版活动稳定身份。"),
            F("campaign_code", "活动代码", "text", "跨版本稳定且不可复用的活动代码。", "与 version_no 共同选择版本；会员参与直接引用 campaign_version_id。", example="HBTI_2026_PAV"),
            F("campaign_name", "活动名称快照", "text", "本版本发布时展示的活动名称。", "名称变化不重写旧参与和结果。", example="HBTI 会员偏好调研"),
            F("campaign_type", "活动类型", "text", "SURVEY、PROMOTION、LOYALTY、COUPON 或 OTHER。", "决定本版本允许的规则和事实要求。", example="SURVEY"),
            ID("location_id", "地点ID", "活动只适用某地点时填写；全企业活动为空。", fk="ops_location.location_id", nullable=True),
            F("version_no", "版本号", "integer", "活动内递增版本。", "参与和作答永远引用具体版本。", example="3", checks=("version_no > 0",)),
            F("starts_at", "开始时间", "timestamptz", "活动版本允许参与的开始时间；只有无法证明开始时点的历史归档版本可为空。", "资格判断；历史缺失必须显式保留未知，不能猜日期。", nullable=True, example="2026-08-01T00:00:00+08:00"),
            F("ends_at", "结束时间", "timestamptz", "活动版本停止接受新参与的时间。", "资格判断。", nullable=True, example="2026-08-31T23:59:59+08:00"),
            F("rule_schema_version", "活动规则结构版本", "text", "audience_rule、participation_rule 和 reward_rule 共用的固定 JSON Schema 版本。", "冻结三类行为规则的键、类型和范围，升级结构时必须新建活动版本。", default="'campaign-rules-v1'", example="campaign-rules-v1"),
            F("audience_rule", "受众规则", "jsonb", "按 rule_schema_version 校验的会员状态、地点或邀请条件；未知键拒绝。", "复现某会员为何有资格。", default="'{}'::jsonb", example='{"member_status":"ACTIVE"}'),
            F("participation_rule", "参与规则", "jsonb", "按 rule_schema_version 校验的次数限制、完成条件和重复参与政策；未知键拒绝。", "HBTI 锁和完成状态依据。", default="'{}'::jsonb", example='{"max_responses":1}'),
            F("result_algorithm_version", "测评算法版本", "text", "本活动版本正式采用的答案到 result_code 算法版本；非测评活动可为空。", "使奖励、展示和分析只选择活动批准的结果版本。", nullable=True, example="hbti-score-v2"),
            F("result_schema_version", "测评结果结构版本", "text", "result_dimensions 和展示字段遵循的结构版本；非测评活动可为空。", "防止同名 JSON 字段在算法升级后含义漂移。", nullable=True, example="hbti-result-schema-v1"),
            F("reward_rule", "奖励规则", "jsonb", "按 rule_schema_version 校验的奖励选择和库存扣减规则；未知键拒绝。", "奖励发放可重现。", default="'{}'::jsonb", example='{"reward_required":true}'),
            F("status", "版本状态", "text", "DRAFT、APPROVED、PUBLISHED、PAUSED、COMPLETED、ARCHIVED、SUPERSEDED 或 CANCELLED。", "只有 PUBLISHED 接受新参与；暂停、完成或归档均追加新版本状态。", example="PUBLISHED"),
            ID("approved_by_user_id", "批准账号", "批准该活动版本的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "活动版本获批时间。", "审计。", nullable=True, example="2026-07-28T10:00:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("campaign_code", "version_no"),), checks=(
            "ends_at IS NULL OR ends_at > starts_at",
            "starts_at IS NOT NULL OR (status = 'ARCHIVED' AND ends_at IS NULL)",
        ),
        exclusions=("NO_OVERLAP(campaign_code, tstzrange(starts_at, ends_at, '[)')) WHERE status = 'PUBLISHED'",),
        retention="永久保留活动版本、参与、作答、结果和奖励连接",
        notes="R6 终审将 mkt_campaign 合并到本表：没有任何业务事实只引用活动主档，所有参与、问卷与奖励都必须引用具体 campaign_version_id；campaign_code 已足够跨版本分组。只有历史迁移且无法证明开始时点的 ARCHIVED 版本允许 starts_at=NULL 且 ends_at=NULL，活跃或可参与版本必须有开始时点。DRAFT 写入函数必须按 campaign_type + rule_schema_version 校验三类规则并拒绝未知键；DRAFT 以外规则冻结，任何规则变化都新增 version_no。",
    ),
    T(
        "mkt_campaign_member", "活动会员参与", "mkt",
        "记录会员在某活动版本中的资格、邀请、开始、完成和取消历史，不再把活动状态覆盖在 pos_member 当前快照上。",
        "活动版本 × 会员一行", "营销/HBTI后台",
        ("HBTI", "财务网站", "分析/BI"), "资格评估、邀请链接和会员操作", "REQUIRED",
        [
            ID("campaign_member_id", "活动会员ID", "一次会员活动参与稳定身份。"),
            ID("campaign_version_id", "活动版本ID", "会员参与的具体活动版本。", fk="mkt_campaign_version.campaign_version_id"),
            ID("member_id", "会员ID", "参与活动的 POS 会员。", fk="pos_member.member_id"),
            F("eligibility_status", "资格状态", "text", "ELIGIBLE、INELIGIBLE、PENDING 或 OVERRIDDEN。", "解释是否允许参与。", example="ELIGIBLE"),
            F("eligibility_evidence", "资格证据", "jsonb", "资格规则结果和输入快照。", "重现资格判断。", default="'{}'::jsonb", example='{"member_status":"ACTIVE"}'),
            F("invited_at", "邀请时间", "timestamptz", "首次发送活动邀请时间。", "转化漏斗。", nullable=True, example="2026-08-05T10:00:00+08:00"),
            F("started_at", "开始时间", "timestamptz", "会员首次进入并开始活动的时间。", "完成时长。", nullable=True, example="2026-08-06T11:00:00+08:00"),
            F("completed_at", "完成时间", "timestamptz", "满足活动完成条件的时间。", "奖励资格和转化。", nullable=True, example="2026-08-06T11:05:00+08:00"),
            F("status", "参与状态", "text", "INVITED、STARTED、COMPLETED、EXPIRED、CANCELLED 或 BLOCKED。", "活动流程当前状态。", default="'INVITED'", example="COMPLETED"),
            F("completion_version", "完成逻辑版本", "text", "判定完成时使用的服务或规则版本。", "历史完成判定可解释。", nullable=True, example="hbti-completion-v2"),
        ], standard="mutable", mutation_policy="CONTROLLED_WORKFLOW", uniques=(("campaign_version_id", "member_id"),),
        notes="本表保存参与流程的当前状态，因此允许受控状态更新；每次作答和测评结果分别在 response/result 表追加，不覆盖历史结果。",
    ),
    T(
        "mkt_survey_question", "问卷题目", "mkt",
        "版本化保存活动问卷题目、类型、顺序和必答规则。",
        "活动版本 × 题目代码一行", "营销/HBTI后台",
        ("HBTI", "分析/BI"), "活动问卷配置", "REQUIRED",
        [
            ID("survey_question_id", "题目ID", "一条活动版本题目稳定身份。"),
            ID("campaign_version_id", "活动版本ID", "题目所属具体活动版本。", fk="mkt_campaign_version.campaign_version_id"),
            F("question_code", "题目代码", "text", "活动内稳定题目代码。", "跨语言展示和答题连接。", example="Q01_FLAVOR"),
            F("question_text", "题目文本", "text", "发布时展示的题目文本。", "保留会员实际看到的内容。", example="你更喜欢哪种口味？"),
            F("question_type", "题目类型", "text", "SINGLE_CHOICE、MULTIPLE_CHOICE、RATING、TEXT 或 BOOLEAN。", "决定答案校验。", example="SINGLE_CHOICE"),
            F("sequence_no", "题目顺序", "integer", "问卷中的展示顺序。", "重现交互。", example="1", checks=("sequence_no > 0",)),
            F("is_required", "是否必答", "boolean", "完成问卷是否必须回答该题。", "完成门禁。", default="true", example="true"),
            F("validation_schema_version", "答案校验结构版本", "text", "validation_rule 对应的固定 JSON Schema 版本。", "让同一 question_type 的规则结构升级可追溯。", default="'survey-validation-v1'", example="survey-validation-v1"),
            F("validation_rule", "答案校验规则", "jsonb", "按 question_type + validation_schema_version 校验的分值范围、最大选择数或文本长度；未知键拒绝。", "服务端验证。", default="'{}'::jsonb", example='{"max_choices":1}'),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("campaign_version_id", "question_code"), ("campaign_version_id", "sequence_no")),
        notes="所属 campaign_version 处于 DRAFT 时可编辑；受控写入函数按 question_type + validation_schema_version 校验 validation_rule 并拒绝未知键；发布后题目冻结，任何改文案、类型、顺序或校验规则都必须创建新的活动版本。",
    ),
    T(
        "mkt_survey_question_option", "问卷选项", "mkt",
        "保存选择题选项代码、文本、顺序和可选分析标签。",
        "题目 × 选项代码一行", "营销/HBTI后台",
        ("HBTI", "分析/BI"), "活动问卷配置", "REQUIRED",
        [
            ID("survey_question_option_id", "选项ID", "一条题目选项稳定身份。"),
            ID("survey_question_id", "题目ID", "选项所属题目。", fk="mkt_survey_question.survey_question_id"),
            F("option_code", "选项代码", "text", "题目内稳定选项代码。", "答案连接和跨语言分析。", example="DARK_CHOCOLATE"),
            F("option_text", "选项文本", "text", "会员看到的选项文本。", "保留发布内容。", example="黑巧克力"),
            F("sequence_no", "选项顺序", "integer", "题目内展示顺序。", "重现交互。", example="1", checks=("sequence_no > 0",)),
            F("analysis_tags", "分析标签", "text[]", "批准的产品偏好或分群标签。", "避免后续从自由文本猜标签。", default="'{}'::text[]", example="{chocolate,dark}"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("survey_question_id", "option_code"), ("survey_question_id", "sequence_no")),
        notes="所属 campaign_version 处于 DRAFT 时可编辑；发布后选项冻结，避免历史答案连接到被改写的选项。",
    ),
    T(
        "mkt_survey_response", "问卷作答", "mkt",
        "保存会员对某活动版本的一次完整、部分或仅有历史结果锚点的问卷尝试。",
        "活动会员 × 尝试次数一行", "HBTI应用",
        ("HBTI", "分析/BI"), "会员提交", "REQUIRED",
        [
            ID("survey_response_id", "作答ID", "一次问卷尝试稳定身份。"),
            ID("campaign_member_id", "活动会员ID", "作答所属会员参与。", fk="mkt_campaign_member.campaign_member_id"),
            ID("source_system_id", "来源系统ID", "外部作答ID所属的来源命名空间；纯内部首次作答也登记 HBTI 应用来源。", fk="app_source_system.source_system_id"),
            F("source_response_id", "来源作答或迁移锚点ID", "text", "真实作答保存来源 attempt_id；只有历史 result-only 迁移允许保存 migration-only:<typed-JCS UUIDv5> 锚点，并在迁移清单标明它不是来源观察。", "跨抓取和迁移实现幂等；迁移锚点不得冒充来源作答尝试，也不得据此反推答案。", example="migration-only:3e1d9b19-31f4-5a6c-b5dd-27d40c61c674"),
            F("attempt_no", "尝试次数", "integer", "真实来源作答在同一参与中的正整数尝试序号；只有没有来源作答事实的 result-only 历史迁移锚点为空。", "保留真实重试而非覆盖，并让无作答事实的迁移记录保持未知。", nullable=True, example="1", checks=("attempt_no IS NULL OR attempt_no > 0",)),
            F("started_at", "开始时间", "timestamptz", "本次作答开始时间；历史终态记录未保存开始时点时可为空。", "完成时长；缺失时保持未知，不能用访问类别或结果时间倒推。", nullable=True, example="2026-08-06T11:00:00+08:00"),
            F("submitted_at", "提交时间", "timestamptz", "会员提交本次答案的时间。", "完成判定。", nullable=True, example="2026-08-06T11:05:00+08:00"),
            F("status", "作答状态", "text", "IN_PROGRESS、SUBMITTED、VALIDATED、REJECTED 或 ABANDONED。", "只有 VALIDATED 进入正式活动分析。", example="VALIDATED"),
            F("validation_result", "校验结果", "jsonb", "必答题、选项和重复提交检查。", "解释拒绝或部分作答。", default="'{}'::jsonb", example='{"required_complete":true}'),
            F("client_context", "客户端上下文", "jsonb", "非敏感的应用版本、语言和流程版本。", "排查交互问题；不得保存IP或设备指纹。", default="'{}'::jsonb", example='{"app_version":"1.3"}'),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL", uniques=(("campaign_member_id", "attempt_no"), ("source_system_id", "source_response_id")),
        nulls_not_distinct_uniques=(("campaign_member_id", "attempt_no"),),
        checks=("started_at IS NOT NULL OR (submitted_at IS NOT NULL AND status IN ('SUBMITTED','VALIDATED','REJECTED'))",),
        notes="新作答必须记录真实 started_at、真实来源作答ID和正数 attempt_no。历史迁移若只有已提交或已计算结果，可保留 started_at=NULL、attempt_no=NULL，并使用登记 legacy source_system + migration-only:typed-JCS UUIDv5 锚点；迁移清单必须保存公式、哈希和非来源观察标志。result-only 响应固定 SUBMITTED、validation_result=SOURCE_ANSWERS_UNAVAILABLE；它不等于证明完整问卷答案存在。",
    ),
    T(
        "mkt_survey_answer", "问卷题目答案", "mkt",
        "逐个原子值保存选项、评分、布尔或文本答案；多选题每个被选选项各占一行，不把多个外键塞进数组。",
        "作答 × 题目 × 原子答案值一行", "HBTI应用",
        ("HBTI", "分析/BI"), "会员提交", "REQUIRED",
        [
            ID("survey_answer_id", "答案ID", "一个原子答案值的稳定主键。"),
            ID("survey_response_id", "作答ID", "所属问卷作答。", fk="mkt_survey_response.survey_response_id"),
            ID("survey_question_id", "题目ID", "被回答的具体版本题目。", fk="mkt_survey_question.survey_question_id"),
            F("value_index", "答案值序号", "integer", "同一次作答同一题内从 1 递增的原子值序号；单值题固定为 1。", "让多选题可以逐个保存、逐个外键校验并保持稳定顺序。", default="1", example="1", checks=("value_index > 0",)),
            ID("selected_option_id", "所选选项ID", "单选或多选题本行选择的一个选项。", fk="mkt_survey_question_option.survey_question_option_id", nullable=True),
            F("rating_value", "评分值", "numeric(9,4)", "评分题的数值答案。", "偏好和满意度分析。", nullable=True, example="4"),
            F("boolean_value", "布尔答案", "boolean", "是非题答案。", "结构化分析。", nullable=True, example="true"),
            F("text_value", "文本答案", "text", "开放题回答；必须经过内容和 PII 策略。", "定性分析，不应默认展示给所有分析用户。", nullable=True, sensitive="restricted", example="希望增加低糖选择"),
            F("answered_at", "回答时间", "timestamptz", "该题答案最后确认时间。", "分析作答节奏。", example="2026-08-06T11:03:00+08:00"),
        ], standard="immutable", uniques=(("survey_response_id", "survey_question_id", "value_index"),),
        checks=("num_nonnulls(selected_option_id, rating_value, boolean_value, text_value) = 1",),
        notes="多选题按 value_index 写多行；单选、评分、布尔和文本题只能写 value_index=1。受控写入函数还必须确认 selected_option_id 属于 survey_question_id，并按 question_type 限制允许的值类型。",
    ),
    T(
        "mkt_survey_result", "问卷测评结果", "mkt",
        "保存一次问卷作答锚点经具体算法版本计算或由历史来源迁入的 HBTI 类型及其他测评结果；历史结果可能缺少原答案，不能冒充可复算。",
        "问卷作答 × 结果类型 × 算法版本一行", "HBTI结果计算服务",
        ("HBTI", "财务网站", "分析/BI"), "已验证问卷答案、批准的评分算法或明确标记不完整的历史结果", "REQUIRED",
        [
            ID("survey_result_id", "测评结果ID", "一次问卷测评结果稳定主键。"),
            ID("survey_response_id", "作答ID", "产生该结果或承接历史结果的问卷作答锚点；不自动证明答案完整。", fk="mkt_survey_response.survey_response_id"),
            F("result_type", "结果类型", "text", "HBTI_PROFILE 或未来批准的其他测评类型。", "同一作答可以产生不同业务定义的结果，但不可混用。", example="HBTI_PROFILE"),
            F("result_code", "结果代码", "text", "算法输出的稳定类别代码；现有 hbti_code 迁入此列。", "支持活动分群和历史分析，不依赖颜色或展示名称。", example="HBTI_DARK_EXPLORER"),
            F("result_label", "结果展示名称", "text", "计算时面向用户显示的结果名称快照。", "保留当时文案；分析连接使用 result_code。", nullable=True, example="Dark Explorer"),
            F("result_color", "结果展示颜色", "text", "计算时使用的颜色代码或名称快照。", "重现 HBTI 结果页，不作为结果身份。", nullable=True, example="#5A3825"),
            F("algorithm_version", "结果算法版本", "text", "将答案转换为 result_code 的批准算法版本。", "算法修改后可以重算并与旧结果并存。", example="hbti-score-v2"),
            F("input_sha256", "输入答案校验值", "char(64)", "按固定顺序规范化真实答案后的 SHA-256；历史来源没有答案时为空。", "有值时证明结果对应哪组答案；不得从结果字段反推伪造答案哈希。", nullable=True, example="a91f...64位十六进制"),
            F("result_dimensions", "结果维度", "jsonb", "算法输出的分数、维度或解释标签。", "保存可扩展测评明细；稳定主类别仍使用 result_code。", default="'{}'::jsonb", example='{"chocolate":0.82,"adventure":0.64}'),
            F("quality_status", "结果质量状态", "text", "VALID、INCOMPLETE_INPUT、ALGORITHM_ERROR 或 REJECTED。", "只有 VALID 且算法版本等于 campaign_version.result_algorithm_version 的结果可触发正式分群或奖励。", example="VALID", checks=("quality_status IN ('VALID','INCOMPLETE_INPUT','ALGORITHM_ERROR','REJECTED')",)),
            F("calculated_at", "计算时间", "timestamptz", "该算法完成结果计算的绝对时间。", "排序重算并审计延迟。", example="2026-08-06T11:05:02+08:00"),
            ID("source_system_id", "历史来源系统ID", "迁移既有结果时标明旧结果ID所属命名空间；本系统新计算结果为空。", fk="app_source_system.source_system_id", nullable=True),
            F("source_result_id", "历史来源结果ID", "text", "迁移现有 HBTI 结果时保存旧记录稳定标识；新结果可为空。", "旧新结果逐行核对并保证幂等。", nullable=True, sensitive="internal", example="fact_hbti_response:8812"),
        ],
        standard="immutable",
        uniques=(("survey_response_id", "result_type", "algorithm_version"), ("source_system_id", "source_result_id")),
        nulls_distinct_uniques=(("source_system_id", "source_result_id"),),
        checks=(
            "(source_system_id IS NULL) = (source_result_id IS NULL)",
            "input_sha256 IS NOT NULL OR quality_status = 'INCOMPLETE_INPUT'",
        ),
        retention="按活动分析与会员隐私政策保留；删除联系信息不应破坏去标识结果统计",
        notes="结果是不可变事实，不反写 pos_member 当前列。只有存在真实答案且 input_sha256 非空的结果才可称为可复算；历史 result-only 迁移必须使用 quality_status='INCOMPLETE_INPUT'、input_sha256=NULL 和明确的历史算法版本，且不得反推答案。算法重跑追加新 algorithm_version；当前业务结果由 campaign_version.result_algorithm_version 明确选择，不回写旧结果为 SUPERSEDED。若新算法要改变会员展示或奖励规则，必须发布新活动版本。",
    ),
    T(
        "mkt_reward", "活动奖励主数据", "mkt",
        "维护礼品、优惠券或权益的稳定身份。",
        "一个可发放奖励一行", "营销后台",
        ("HBTI", "财务网站", "分析/BI"), "营销配置", "REQUIRED",
        [
            ID("reward_id", "奖励ID", "奖励稳定身份。"),
            F("reward_code", "奖励代码", "text", "企业内部唯一奖励代码。", "活动规则和库存连接。", unique=True, example="GIFT_COOKIE_BOX"),
            F("reward_name", "奖励名称", "text", "当前显示名称。", "会员选择和报表。", example="曲奇礼盒"),
            F("reward_type", "奖励类型", "text", "PHYSICAL_GIFT、COUPON、POINTS 或 BENEFIT。", "决定库存和发放流程。", example="PHYSICAL_GIFT"),
            ID("product_id", "关联产品ID", "奖励本身是企业产品时关联。", fk="ops_product.product_id", nullable=True),
            F("status", "奖励状态", "text", "ACTIVE、SUSPENDED 或 RETIRED。", "控制新活动可选。", default="'ACTIVE'", example="ACTIVE"),
        ], standard="manual", uniques=(("reward_code",),),
    ),
    T(
        "mkt_reward_stock", "活动奖励库存", "mkt",
        "保存活动版本、地点和奖励的可用、预留和已发数量。",
        "活动版本 × 地点 × 奖励一行", "HBTI/营销库存服务",
        ("HBTI", "财务网站", "分析/BI"), "营销分配和奖励发放", "REQUIRED",
        [
            ID("reward_stock_id", "奖励库存ID", "一条活动奖励库存稳定主键。"),
            ID("campaign_version_id", "活动版本ID", "库存分配给的活动版本。", fk="mkt_campaign_version.campaign_version_id"),
            ID("location_id", "地点ID", "奖励可领取地点；数字权益可为空。", fk="ops_location.location_id", nullable=True),
            ID("reward_id", "奖励ID", "库存对应奖励。", fk="mkt_reward.reward_id"),
            F("allocated_quantity", "分配数量", "integer", "活动版本最初或追加分配的总数量。", "库存上限。", example="100", checks=("allocated_quantity >= 0",)),
            F("unit_cost_estimate", "批准单位成本估算", "numeric(18,4)", "本活动版本和地点分配奖励时批准的单位预算成本。", "冻结活动预算口径，避免奖励主档后来改价重写历史活动成本。", nullable=True, example="8.00", checks=("unit_cost_estimate IS NULL OR unit_cost_estimate >= 0",)),
            F("currency", "成本估算币种", "char(3)", "本次分配单位成本估算的 ISO 4217 币种；没有单位成本证据时为空。", "仅在 unit_cost_estimate 存在时解释活动预算金额，不能因缺失成本自动制造 MYR。", nullable=True, example="MYR"),
            F("reserved_quantity", "预留数量", "integer", "已被会员选择但尚未发放的数量。", "防止超卖。", default="0", example="12", checks=("reserved_quantity >= 0",)),
            F("redeemed_quantity", "已发数量", "integer", "已完成发放的数量。", "活动消耗。", default="0", example="45", checks=("redeemed_quantity >= 0",)),
            F("damaged_quantity", "损坏数量", "integer", "不可发放的损坏或调整数量。", "可用库存扣减。", default="0", example="1", checks=("damaged_quantity >= 0",)),
            F("version_no", "并发版本", "integer", "每次原子库存变更递增的乐观锁版本。", "防止并发超发。", default="1", example="58", checks=("version_no > 0",)),
        ], standard="mutable", mutation_policy="CONTROLLED_WORKFLOW", uniques=(("campaign_version_id", "location_id", "reward_id"), ("reward_stock_id", "reward_id")),
        nulls_not_distinct_uniques=(("campaign_version_id", "location_id", "reward_id"),),
        checks=("reserved_quantity + redeemed_quantity + damaged_quantity <= allocated_quantity", "(unit_cost_estimate IS NULL) = (currency IS NULL)"),
        notes="unit_cost_estimate 是活动分配时不可反推的批准预算快照，因此放在本粒度，不放奖励主档；没有成本时 currency 也必须为空。四个数量虽可由分配/领取事实核算，但本表是并发预留的事务控制行，不是分析快照；更新必须使用 version_no 乐观锁并与有 reward_stock_id 的 reward_claim 同事务。stockless 外部履约不扣本表库存。v_mkt_reward_stock_reconciliation 持续检查缓存计数与有库存领取事实是否漂移。",
    ),
    T(
        "mkt_reward_claim", "活动奖励领取", "mkt",
        "记录会员选择、预留、发放、到期或取消一份奖励的完整状态。",
        "活动会员 × 一次奖励领取一行", "HBTI/营销库存服务",
        ("HBTI", "财务网站", "分析/BI"), "会员选择和现场核销", "REQUIRED",
        [
            ID("reward_claim_id", "领取ID", "一次奖励领取稳定主键。"),
            ID("campaign_member_id", "活动会员ID", "领取奖励的会员参与。", fk="mkt_campaign_member.campaign_member_id"),
            F("reward_stock_id", "奖励库存ID", "uuid", "本次领取确实来自目标活动库存时填写；外部独立发券且没有可证明库存行时为空。", "与 reward_id 共同通过复合外键证明库存身份；为空时必须以外部履约身份保证可追溯。", nullable=True, example="7173f2bb-2398-525d-acea-8023de261b97"),
            ID("reward_id", "奖励ID", "本次领取或外部履约的直接奖励身份。", fk="mkt_reward.reward_id"),
            ID("survey_result_id", "测评结果ID", "奖励由具体问卷结果触发或选择时记录；与结果无关的活动可为空。", fk="mkt_survey_result.survey_result_id", nullable=True),
            F("idempotency_key", "领取幂等键", "char(64)", "按活动参与、奖励、触发结果或客户端请求号规范化计算的 SHA-256。", "库存预留重试必须恢复同一 claim，防止重复扣减和重复发奖。", unique=True, sensitive="internal", example="d72a...64位十六进制"),
            F("quantity", "领取数量", "integer", "本次领取数量。", "库存原子扣减。", default="1", example="1", checks=("quantity > 0",)),
            F("status", "领取状态", "text", "RESERVED、REDEEMED、EXPIRED、CANCELLED 或 REJECTED；REDEEMED 只表示奖励履约完成，数字券已发放，不证明会员已在 POS 消费。", "区分预留和奖励履约结果，禁止把发券误读成消费。", example="REDEEMED"),
            F("reserved_at", "预留时间", "timestamptz", "来源明确保存库存成功预留时间时填写；外部来源没有真实预留时刻时为空。", "并发和到期计时；不能用 completed_at、confirmedAt 或 redeemed_at 回填。", nullable=True, example="2026-08-06T11:05:00+08:00"),
            F("expires_at", "预留到期时间", "timestamptz", "未核销预留自动释放时间。", "避免永久占库存。", nullable=True, example="2026-08-13T23:59:59+08:00"),
            F("redeemed_at", "履约完成时间", "timestamptz", "现场实物发放或数字权益/新券实例成功发出的时间；RES confirmedAt 迁入这里。", "确认奖励履约发生；不证明该券后来被 POS 消费。", nullable=True, example="2026-08-08T15:00:00+08:00"),
            ID("redeemed_by_user_id", "核销账号", "现场确认发放的账号。", fk="app_user.user_id", nullable=True),
            ID("source_system_id", "履约来源系统ID", "外部系统完成奖励履约时标明 source_fulfillment_id 所属命名空间；内部库存领取可为空。", fk="app_source_system.source_system_id", nullable=True),
            F("source_fulfillment_id", "外部履约ID", "text", "外部奖励履约或新券实例的来源内稳定ID，例如 RES newCouponId；绝不表示 POS 消费或券核销。", "跨系统发奖幂等和履约对账。", nullable=True, example="new_coupon_8812", checks=("source_fulfillment_id IS NULL OR btrim(source_fulfillment_id) <> ''",)),
        ], standard="mutable", mutation_policy="CONTROLLED_WORKFLOW",
        foreign_keys=(TableForeignKey(("reward_stock_id", "reward_id"), "mkt_reward_stock", ("reward_stock_id", "reward_id")),),
        uniques=(("idempotency_key",), ("source_system_id", "source_fulfillment_id")),
        nulls_distinct_uniques=(("source_system_id", "source_fulfillment_id"),),
        checks=(
            "expires_at IS NULL OR (reserved_at IS NOT NULL AND expires_at > reserved_at)",
            "(source_system_id IS NULL) = (source_fulfillment_id IS NULL)",
            "reward_stock_id IS NOT NULL OR (source_system_id IS NOT NULL AND source_fulfillment_id IS NOT NULL)",
            "status <> 'REDEEMED' OR redeemed_at IS NOT NULL",
        ),
        notes="有 reward_stock_id 的 claim 必须通过 (reward_stock_id,reward_id) 复合外键证明库存与奖励一致，并与 reward_stock 预留计数在同一事务内用 version_no 乐观锁更新；stockless 外部履约必须保存 source_system_id + source_fulfillment_id。REDEEMED 只证明实物/数字权益已发放，绝不证明 POS 消费。同一 idempotency_key 重跑只返回原 claim。",
    ),

    # ------------------------------------------------------------------
    # Messaging and conversational workflow
    # ------------------------------------------------------------------
    T(
        "msg_conversation", "消息会话", "msg",
        "统一表示内部助手、候选人 WhatsApp 或会员活动的一段会话，并用类型化外键连接业务对象。",
        "一个渠道会话一行", "BakeryOps消息服务",
        ("BakeryOps", "HBTI", "分析/BI"), "WhatsApp、应用聊天或活动入口", "REQUIRED",
        [
            ID("conversation_id", "会话ID", "跨消息和状态稳定的会话身份。"),
            F("channel_code", "渠道代码", "text", "WHATSAPP、WEB_CHAT、LARK 或 OTHER。", "路由发送和解析。", example="WHATSAPP"),
            F("external_conversation_id", "外部会话ID", "text", "渠道提供的稳定会话或号码哈希标识。", "同步幂等；不得保存明文手机号作为主键。", nullable=True, sensitive="restricted", example="wa_hash_..."),
            ID("application_id", "候选申请ID", "招聘会话对应申请；不适用为空。", fk="hr_application.application_id", nullable=True),
            ID("person_id", "人员ID", "内部或候选人会话对应自然人；不适用为空。", fk="hr_person.person_id", nullable=True),
            ID("member_id", "会员ID", "会员活动会话对应会员；不适用为空。", fk="pos_member.member_id", nullable=True),
            ID("app_user_id", "应用账号ID", "内部用户助手会话对应账号；不适用为空。", fk="app_user.user_id", nullable=True),
            F("status", "会话状态", "text", "OPEN、WAITING_USER、WAITING_AGENT、CLOSED、OPTED_OUT 或 BLOCKED。", "路由和合规。", default="'OPEN'", example="WAITING_USER"),
            F("opened_at", "开始时间", "timestamptz", "会话首次创建时间。", "响应时长。", example="2026-08-09T10:00:00+08:00"),
            F("closed_at", "关闭时间", "timestamptz", "会话结束时间。", "生命周期。", nullable=True, example="2026-08-09T10:30:00+08:00"),
        ], standard="mutable",
        uniques=(("channel_code", "external_conversation_id"),),
        nulls_distinct_uniques=(("channel_code", "external_conversation_id"),),
        checks=("closed_at IS NULL OR closed_at >= opened_at", "num_nonnulls(application_id, person_id, member_id, app_user_id) >= 1"),
        notes="last_message_at 不重复保存；待跟进排序从 msg_message.occurred_at 的最大值派生并按性能证据决定是否建立物化索引视图。",
    ),
    T(
        "msg_message", "会话消息", "msg",
        "只追加保存会话中的入站、出站和系统消息及经过审核的正文。",
        "会话 × 一条消息一行", "BakeryOps消息服务",
        ("BakeryOps", "HBTI"), "渠道入站或应用生成", "REQUIRED",
        [
            ID("message_id", "消息ID", "一条消息稳定主键。"),
            ID("conversation_id", "会话ID", "消息所属会话。", fk="msg_conversation.conversation_id"),
            ID("outbound_message_id", "外发消息ID", "该消息由队列发送时连接原外发任务；入站或系统消息为空。", fk="msg_outbound_message.outbound_message_id", nullable=True),
            F("external_message_id", "外部消息ID", "text", "渠道提供的稳定消息ID。", "同步幂等。", nullable=True, example="wamid.HBg..."),
            F("direction", "方向", "text", "INBOUND、OUTBOUND 或 SYSTEM。", "区分用户和系统内容。", example="INBOUND"),
            F("sender_type", "发送者类型", "text", "PERSON、MEMBER、APP_USER、SERVICE 或 CHANNEL。", "解释发送主体。", example="PERSON"),
            F("content_type", "内容类型", "text", "TEXT、IMAGE、FILE、AUDIO、TEMPLATE 或 EVENT。", "选择存储和展示方式。", example="TEXT"),
            F("content_text", "消息文本", "text", "经过保留政策和必要脱敏的文本内容。", "对话和流程理解；访问受限。", nullable=True, sensitive="restricted", example="我可以周三面试"),
            F("content_ref", "媒体引用", "text", "受控对象存储中的媒体或文件引用。", "避免把大文件和秘密直接存数据库。", nullable=True, sensitive="restricted", example="s3://.../hash"),
            F("occurred_at", "消息发生时间", "timestamptz", "渠道认定的发送或接收时间。", "会话排序。", example="2026-08-09T10:20:00+08:00"),
            F("acceptance_status", "首次接收状态", "text", "RECEIVED、QUEUED、SENT、FAILED 或 REJECTED。", "冻结消息首次进入本系统或渠道时的状态；后续 DELIVERED、READ 等变化写 delivery_event。", example="RECEIVED"),
            F("metadata", "消息元数据", "jsonb", "模板代码、语言和不含秘密的渠道属性。", "保留必要渠道信息。", default="'{}'::jsonb", example='{"language":"zh"}'),
        ], standard="immutable",
        uniques=(("conversation_id", "external_message_id"), ("outbound_message_id",)),
        nulls_distinct_uniques=(("conversation_id", "external_message_id"), ("outbound_message_id",)),
        retention="按招聘、会员和内部会话类型分别设置；普通聊天不能无限期保留",
        notes="conversation_id 已提供渠道命名空间，因此 (conversation_id, external_message_id) 阻止重复入站；同一 outbound_message_id 只形成一条语义消息，渠道重试只写 msg_delivery_attempt，不复制正文。两种外键为空的内部 SYSTEM 消息仍由 message_id 区分。",
    ),
    T(
        "msg_conversation_state", "会话流程状态", "msg",
        "保存招聘或助手多轮流程的当前节点、已收集参数和到期时间；完成后仍保留最终状态摘要。",
        "会话 × 工作流代码一行", "BakeryOps编排器",
        ("BakeryOps",), "会话状态机", "REQUIRED",
        [
            ID("conversation_state_id", "流程状态ID", "一条会话工作流状态稳定主键。"),
            ID("conversation_id", "会话ID", "状态所属会话。", fk="msg_conversation.conversation_id"),
            F("workflow_code", "工作流代码", "text", "RECRUITMENT、DAILY_REVIEW、ORDERING 等稳定流程代码。", "选择状态机定义。", example="RECRUITMENT"),
            F("workflow_version", "工作流版本", "text", "状态机结构版本。", "升级后仍可恢复旧会话。", example="recruit-v4"),
            F("state_code", "当前状态", "text", "工作流内当前节点代码。", "决定下一步允许动作。", example="WAITING_TRIAL_DATE"),
            F("collected_data", "已收集参数", "jsonb", "已通过 schema 校验的非敏感或受限参数。", "跨轮次继续流程。", default="'{}'::jsonb", sensitive="restricted", example='{"preferred_date":"2026-08-12"}'),
            F("pending_action", "待确认动作", "jsonb", "需要用户确认后才执行的结构化动作。", "防止未经确认直接写业务事实。", nullable=True, sensitive="internal", example='{"action":"BOOK_TRIAL"}'),
            F("expires_at", "状态到期时间", "timestamptz", "无活动时状态自动失效时间。", "清理临时流程。", nullable=True, example="2026-08-09T10:40:00+08:00"),
            F("status", "状态记录状态", "text", "ACTIVE、COMPLETED、EXPIRED、CANCELLED 或 ERROR。", "流程生命周期。", default="'ACTIVE'", example="ACTIVE"),
        ], standard="mutable", mutation_policy="CONTROLLED_WORKFLOW", uniques=(("conversation_id", "workflow_code"),),
        notes="这是为恢复多轮会话而保存的当前检查点，不是完整状态历史；业务事实仍写各自业务表，消息过程写 msg_message，关键状态变更写 app_audit_event。",
    ),
    T(
        "msg_outbound_message", "外发消息队列", "msg",
        "保存待发送消息、业务推送自然键、最早发送时间、幂等键和队列状态；投递次数、最后错误和成功去重结论从投递事实派生。",
        "一次计划外发消息一行", "BakeryOps消息服务",
        ("BakeryOps", "HBTI"), "招聘、运营推送或活动通知", "REQUIRED",
        [
            ID("outbound_message_id", "外发消息ID", "一次外发任务稳定主键。"),
            ID("conversation_id", "会话ID", "消息所属会话；一次性广播可为空并由 recipient_ref 指定。", fk="msg_conversation.conversation_id", nullable=True),
            ID("job_run_id", "任务运行ID", "由定时或批处理任务产生时连接具体运行。", fk="app_job_run.job_run_id", nullable=True),
            ID("review_action_id", "复盘行动ID", "消息用于推动某项复盘改进行动时连接该行动。", fk="ops_review_action.review_action_id", nullable=True),
            ID("ai_call_id", "AI调用ID", "消息内容由某次 AI 调用建议或生成时连接该调用。", fk="ai_call.ai_call_id", nullable=True),
            ID("appointment_id", "预约ID", "招聘面试或试工提醒连接具体预约。", fk="hr_appointment.appointment_id", nullable=True),
            ID("campaign_member_id", "活动会员ID", "营销或 HBTI 通知连接具体会员活动参与。", fk="mkt_campaign_member.campaign_member_id", nullable=True),
            ID("queued_by_user_id", "入队账号", "人工创建消息时记录操作账号；系统任务可为空并使用 job_run_id。", fk="app_user.user_id", nullable=True),
            F("channel_code", "渠道代码", "text", "WHATSAPP、LARK、EMAIL 或 OTHER。", "选择发送适配器。", example="WHATSAPP"),
            F("recipient_ref", "接收者引用", "text", "受控联系方式ID、渠道用户ID或哈希引用，不保存散落明文手机号。", "发送器解析真实目标。", sensitive="restricted", example="person_contact:..."),
            F("push_kind", "业务推送类型", "text", "MORNING_BRIEF、PRODUCTION_PLAN、ORDER_REMINDER 等稳定代码；非按日业务推送为空。", "与 recipient_ref、business_date 构成可读业务自然键，不从幂等字符串反向解析。", nullable=True, example="MORNING_BRIEF"),
            F("business_date", "推送业务日期", "date", "该业务推送针对的营业或日历日期；非按日消息为空。", "保证同一类每日推送可按结构化字段核对和去重。", nullable=True, example="2026-08-10"),
            F("template_code", "消息模板代码", "text", "批准模板代码；自由文本消息可为空。", "内容治理和多语言。", nullable=True, example="TRIAL_REMINDER_V2"),
            F("template_version", "消息模板版本", "integer", "payload 校验与渲染采用的批准模板版本；自由文本消息为空。", "冻结历史消息的参数结构，避免同一 template_code 升级后旧 payload 失去解释。", nullable=True, example="2", checks=("template_version IS NULL OR template_version > 0",)),
            F("payload", "模板参数", "jsonb", "通过模板 schema 校验的参数。", "渲染消息；敏感值最小化。", default="'{}'::jsonb", sensitive="restricted", example='{"date":"2026-08-12"}'),
            F("idempotency_key", "幂等键", "text", "业务生成的唯一去重键。", "服务重启或重跑不重复发送。", unique=True, example="trial-reminder:appointment:...:24h"),
            F("earliest_send_at", "最早发送时间", "timestamptz", "消息允许发送的最早时间。", "遵守业务时间窗和延迟。", example="2026-08-11T10:00:00+08:00"),
            F("expires_at", "消息到期时间", "timestamptz", "超过此时间不再发送。", "避免过期提醒。", nullable=True, example="2026-08-12T09:00:00+08:00"),
            F("priority", "优先级", "smallint", "数字越小优先级越高。", "队列排序。", default="100", example="50"),
            F("status", "队列状态", "text", "QUEUED、PROCESSING、SENT、FAILED、CANCELLED 或 EXPIRED。", "发送生命周期。", default="'QUEUED'", example="QUEUED"),
        ], standard="mutable", mutation_policy="CONTROLLED_QUEUE_STATE", uniques=(("idempotency_key",), ("push_kind", "recipient_ref", "business_date")),
        nulls_distinct_uniques=(("push_kind", "recipient_ref", "business_date"),),
        checks=("expires_at IS NULL OR expires_at > earliest_send_at", "(push_kind IS NULL) = (business_date IS NULL)", "(template_code IS NULL) = (template_version IS NULL)", "num_nonnulls(conversation_id, job_run_id, review_action_id, ai_call_id, appointment_id, campaign_member_id, queued_by_user_id) >= 1"),
        notes="R6 终审将 msg_push_deduplication 合并到本表：push_kind + recipient_ref + business_date 是业务去重自然键，idempotency_key 是执行去重键；是否成功、尝试次数和最后错误分别从 msg_delivery_attempt 与可选 msg_delivery_event 确定性派生。payload 必须按 template_code + template_version 的固定 schema 经受控入队函数校验，未知键拒绝。失败重跑必须恢复同一 outbound_message，不新增重复消息。新模块要发消息时必须先增加明确 UUID 外键或专用关联表；禁止使用 extension_source_type/id 多态文本绕过稳定关系。",
    ),
    T(
        "msg_delivery_attempt", "消息投递尝试", "msg",
        "只追加记录外发消息每次调用渠道、结果、外部消息ID和脱敏错误。",
        "外发消息 × 一次发送尝试一行", "BakeryOps消息worker",
        ("BakeryOps", "分析/BI"), "渠道发送结果", "REQUIRED",
        [
            ID("delivery_attempt_id", "投递尝试ID", "一次发送尝试稳定主键。"),
            ID("outbound_message_id", "外发消息ID", "所属队列消息。", fk="msg_outbound_message.outbound_message_id"),
            F("attempt_no", "尝试序号", "integer", "消息内从1递增的尝试次数。", "重试排序。", example="1", checks=("attempt_no > 0",)),
            F("started_at", "开始时间", "timestamptz", "调用渠道开始时间。", "渠道延迟。", example="2026-08-11T10:00:01+08:00"),
            F("finished_at", "结束时间", "timestamptz", "渠道调用结束时间。", "耗时和卡死检测。", nullable=True, example="2026-08-11T10:00:02+08:00"),
            F("result", "投递结果", "text", "SENT、RETRYABLE_FAILURE、PERMANENT_FAILURE 或 UNKNOWN。", "决定重试。", example="SENT"),
            F("external_message_id", "渠道消息ID", "text", "渠道成功返回的消息标识。", "后续送达回执关联。", nullable=True, example="wamid.HBg..."),
            F("http_status", "HTTP状态", "integer", "渠道 API HTTP 状态码。", "排障。", nullable=True, example="200"),
            F("error_code", "错误代码", "text", "渠道或适配器标准错误代码。", "重试分类。", nullable=True, example="RATE_LIMITED"),
            F("error_detail", "错误摘要", "text", "经过脱敏的错误信息。", "排障，不得保存令牌或完整消息正文。", nullable=True, sensitive="internal", example="429 from provider"),
        ], standard="immutable", uniques=(("outbound_message_id", "attempt_no"),), checks=("finished_at IS NULL OR finished_at >= started_at",),
    ),
    T(
        "msg_delivery_event", "消息投递状态事件", "msg",
        "只追加保存渠道回执中的 SENT、DELIVERED、READ、FAILED 等状态变化，避免覆盖消息历史状态。",
        "外发消息 × 一次渠道状态事件一行", "BakeryOps消息回执服务",
        ("BakeryOps", "HBTI", "分析/BI"), "WhatsApp、邮件或其他渠道 webhook/轮询回执", "REQUIRED",
        [
            ID("delivery_event_id", "投递事件ID", "一次渠道投递状态事件稳定主键。"),
            ID("outbound_message_id", "外发消息ID", "状态所属外发队列任务。", fk="msg_outbound_message.outbound_message_id"),
            ID("message_id", "会话消息ID", "对应已持久化会话消息；回执早于消息落库时可为空。", fk="msg_message.message_id", nullable=True),
            ID("delivery_attempt_id", "投递尝试ID", "能确定由哪次发送尝试产生时连接；渠道未提供时为空。", fk="msg_delivery_attempt.delivery_attempt_id", nullable=True),
            ID("source_system_id", "来源系统ID", "返回状态的注册消息渠道。", fk="app_source_system.source_system_id"),
            F("source_event_id", "来源事件ID", "text", "渠道 webhook 或回执的稳定事件编号。", "与来源系统共同保证重复回调不会重复入库。", sensitive="internal", example="wa-status-998812"),
            F("external_message_id", "渠道消息ID", "text", "渠道给该消息的稳定标识。", "无法关联 attempt 时辅助进入映射/质量队列，但不单独作为跨域连接键。", nullable=True, example="wamid.HBg..."),
            F("event_type", "投递事件类型", "text", "SENT、DELIVERED、READ、FAILED、REJECTED 或 UNKNOWN。", "按时间重建送达状态和失败漏斗。", example="DELIVERED"),
            F("occurred_at", "渠道发生时间", "timestamptz", "渠道声明状态发生的绝对时间。", "送达耗时和事件排序。", example="2026-08-11T10:00:04+08:00"),
            F("received_at", "本系统接收时间", "timestamptz", "本系统收到回执的绝对时间。", "区分渠道延迟和摄取延迟。", default="now()", example="2026-08-11T10:00:05+08:00"),
            F("payload_sha256", "回执载荷哈希", "char(64)", "规范化渠道回执的 SHA-256，不保存秘密或完整原始载荷。", "证明去重和排查解析差异。", example="b82e...64位十六进制"),
        ],
        standard="immutable",
        uniques=(("source_system_id", "source_event_id"),),
        checks=("received_at >= occurred_at",),
        retention="按消息类型的保留策略保存；不得因清理正文而破坏投递审计",
        notes="当前状态由事件时间、状态优先级和 delivery_event_id 确定性派生；迟到回执不会覆盖或删除旧事件。",
    ),
    # ------------------------------------------------------------------
    # AI prompt versioning and call evidence
    # ------------------------------------------------------------------
    T(
        "ai_prompt_segment", "Prompt片段版本", "ai",
        "一行冻结一个可复用 Prompt 片段版本的内容、变量结构和校验值；不在每个模板关联中重复复制内容。",
        "Prompt片段代码 × 版本号一行", "BakeryOps AI配置",
        ("BakeryOps", "分析/BI"), "AI管理员配置", "REQUIRED",
        [
            ID("prompt_segment_id", "片段版本ID", "一版 Prompt 片段稳定身份。"),
            F("segment_code", "片段代码", "text", "程序引用的稳定片段代码。", "与 version_no 共同选择具体内容。", example="DAILY_REVIEW_RULES"),
            F("version_no", "片段版本号", "integer", "同一片段代码内从 1 递增的版本号。", "内容改变时新增版本，不覆盖旧模板所用内容。", example="3", checks=("version_no > 0",)),
            F("segment_name", "片段名称", "text", "该版本发布时的显示名称。", "配置界面和历史审计。", example="每日复盘规则"),
            F("segment_category", "片段类别", "text", "ROLE、RULE、KNOWLEDGE、CONTEXT 或 FORMAT。", "控制组合顺序和审查。", example="RULE"),
            F("content", "片段内容", "text", "本片段版本冻结的 Prompt 文本。", "多个模板通过外键复用同一内容，旧调用不受后续版本影响。", sensitive="internal", example="你是每日复盘助手..."),
            F("content_sha256", "内容校验值", "char(64)", "片段内容 SHA-256。", "验证部署和调用采用同一版本。", example="21b0...64位十六进制"),
            F("variable_schema", "变量Schema", "jsonb", "本片段允许注入的变量及类型。", "防止未声明变量和提示注入。", default="'{}'::jsonb", example='{"business_date":{"type":"string"}}'),
            F("status", "版本状态", "text", "DRAFT、APPROVED、ACTIVE、RETIRED 或 REJECTED。", "只有 ACTIVE 可加入新模板；旧模板仍可引用已退役版本。", default="'DRAFT'", example="ACTIVE"),
            ID("approved_by_user_id", "批准账号", "批准该片段版本的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "该片段版本获批时间。", "审计内容何时可用于生产。", nullable=True, example="2026-08-01T09:30:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("segment_code", "version_no"),),
        notes="同一 segment_code 的内容变化只新增 version_no；模板关联只保存片段版本外键和组合顺序，不重复存 content、hash 或 variable_schema。",
    ),
    T(
        "ai_prompt_template", "Prompt模板版本", "ai",
        "一行冻结一个 AI 场景模板版本的模型、参数、输出 schema 和安全策略；不再为稳定模板头另拆版本表。",
        "AI场景代码 × 版本号一行", "BakeryOps AI配置",
        ("BakeryOps", "分析/BI"), "AI管理员发布", "REQUIRED",
        [
            ID("prompt_template_id", "模板版本ID", "一版 Prompt 模板稳定身份。"),
            F("template_code", "模板代码", "text", "程序调用的稳定 AI 场景代码。", "与 version_no 共同选择具体版本。", example="DAILY_REVIEW"),
            F("version_no", "版本号", "integer", "场景代码内递增版本。", "历史调用可重现。", example="4", checks=("version_no > 0",)),
            F("template_name", "模板名称", "text", "该版本发布时的显示名称。", "配置界面和审计。", example="每日复盘"),
            F("purpose", "模板用途", "text", "该版本允许生成的内容和禁止用途。", "降低场景误用。", example="总结已确认经营事实并提出可验证行动"),
            F("model_provider", "模型提供方", "text", "OPENAI、OPENROUTER、GEMINI 或批准提供方。", "调用路由和成本。", example="OPENROUTER"),
            F("model_name", "模型名称", "text", "发布时批准的具体模型标识。", "历史调用解释。", example="openai/gpt-5"),
            F("temperature", "温度", "numeric(5,4)", "模型采样温度。", "重现和风险控制。", default="0", example="0.2"),
            F("top_p", "Top P", "numeric(5,4)", "核采样参数。", "重现。", default="1", example="1"),
            F("output_schema", "输出Schema", "jsonb", "要求模型输出的 JSON Schema。", "结构化结果验证。", default="'{}'::jsonb", example='{"type":"object"}'),
            F("safety_policy_version", "安全策略版本", "text", "PII、秘密、提示注入和输出使用限制版本。", "证明调用采用的治理规则。", example="ai-safety-v3"),
            F("status", "版本状态", "text", "DRAFT、APPROVED、ACTIVE、RETIRED 或 REJECTED。", "只有 ACTIVE 可用于新调用。", example="ACTIVE"),
            ID("approved_by_user_id", "批准账号", "批准模板版本的账号。", fk="app_user.user_id", nullable=True),
            F("approved_at", "批准时间", "timestamptz", "模板版本获批时间。", "审计。", nullable=True, example="2026-08-01T10:00:00+08:00"),
        ], standard="manual", mutation_policy="DRAFT_MUTABLE_THEN_FROZEN", uniques=(("template_code", "version_no"),),
        notes="同一 template_code 的新配置只新增 version_no；ai_call 与片段行直接引用本版本主键。",
    ),
    T(
        "ai_prompt_template_segment", "模板片段组合", "ai",
        "按顺序连接模板版本和已冻结片段版本，只保存组合关系及消息角色。",
        "模板版本 × 顺序一行", "BakeryOps AI配置",
        ("BakeryOps", "分析/BI"), "批准的Prompt片段内容", "REQUIRED",
        [
            ID("prompt_template_segment_id", "模板片段行ID", "一条模板片段版本稳定主键。"),
            ID("prompt_template_id", "模板版本ID", "所属 Prompt 模板版本。", fk="ai_prompt_template.prompt_template_id"),
            ID("prompt_segment_id", "片段版本ID", "引用的已冻结 Prompt 片段版本。", fk="ai_prompt_segment.prompt_segment_id"),
            F("sequence_no", "组合顺序", "integer", "片段进入最终 Prompt 的顺序。", "重现完整 Prompt。", example="2", checks=("sequence_no > 0",)),
            F("role", "消息角色", "text", "SYSTEM、DEVELOPER、USER 或 CONTEXT。", "构造模型消息。", example="SYSTEM"),
        ], standard="immutable", uniques=(("prompt_template_id", "sequence_no"),),
        notes="最终 Prompt 内容由本行顺序连接 ai_prompt_segment.content 确定；禁止在关联表再复制片段文本、哈希或变量结构。",
    ),
    T(
        "ai_call", "AI调用流水", "ai",
        "记录一次模型调用的模板版本、调用方、输入引用、输出、token、成本、延迟和验证结果。",
        "一次模型请求一行", "BakeryOps AI服务",
        ("BakeryOps", "安全管理员", "分析/BI"), "应用AI调用", "REQUIRED",
        [
            ID("ai_call_id", "AI调用ID", "一次模型调用稳定主键。"),
            ID("prompt_template_id", "模板版本ID", "调用使用的已批准模板版本。", fk="ai_prompt_template.prompt_template_id"),
            ID("job_run_id", "任务运行ID", "自动任务触发时对应运行。", fk="app_job_run.job_run_id", nullable=True),
            ID("actor_user_id", "操作账号", "人工触发调用的账号。", fk="app_user.user_id", nullable=True),
            F("caller_code", "调用方代码", "text", "发起调用的模块或函数稳定代码。", "定位责任和成本。", example="daily_review_chat"),
            F("request_id", "请求ID", "text", "贯穿应用和数据库的请求追踪号。", "关联日志。", nullable=True, example="req_01J4..."),
            F("model_provider", "模型提供方", "text", "实际调用的提供方。", "与模板批准值核对。", example="OPENROUTER"),
            F("model_name", "实际模型", "text", "提供方最终返回的模型标识。", "识别路由替换。", example="openai/gpt-5"),
            F("prompt_redacted", "脱敏Prompt", "text", "经过批准规则脱敏后的最终 Prompt 或可审计摘要。", "排查结果但不长期复制 PII 和秘密。", sensitive="restricted", example="<redacted prompt>"),
            F("input_manifest", "输入引用清单", "jsonb", "业务对象ID、版本和字段摘要。", "优先引用事实而非复制全量敏感内容。", default="'{}'::jsonb", sensitive="internal", example='{"daily_review_id":"..."}'),
            F("response_redacted", "脱敏响应", "text", "经过策略处理的模型原始输出。", "离线复核。", nullable=True, sensitive="restricted", example="<redacted response>"),
            F("parsed_output", "结构化输出", "jsonb", "通过输出 Schema 解析的结果。", "供下游建议界面使用；仍须人工门禁。", nullable=True, example='{"actions":[]}' ),
            F("validation_status", "输出校验状态", "text", "VALID、INVALID_SCHEMA、SAFETY_BLOCKED、INCOMPLETE 或 NOT_APPLICABLE。", "无效输出不得写业务事实。", example="VALID"),
            F("input_tokens", "输入Token", "integer", "提供方报告的输入 token 数。", "成本分析。", nullable=True, example="4200", checks=("input_tokens IS NULL OR input_tokens >= 0",)),
            F("output_tokens", "输出Token", "integer", "提供方报告的输出 token 数。", "成本分析。", nullable=True, example="620", checks=("output_tokens IS NULL OR output_tokens >= 0",)),
            F("cost_usd", "调用成本USD", "numeric(18,8)", "本次调用估算或实际美元成本。", "AI成本监控。", nullable=True, example="0.01850000", checks=("cost_usd IS NULL OR cost_usd >= 0",)),
            F("latency_ms", "延迟毫秒", "integer", "从请求到完整响应的耗时。", "性能监控。", nullable=True, example="8420", checks=("latency_ms IS NULL OR latency_ms >= 0",)),
            F("status", "调用状态", "text", "RUNNING、SUCCEEDED、FAILED、CANCELLED 或 BLOCKED。", "识别未终态调用。", example="SUCCEEDED"),
            F("started_at", "开始时间", "timestamptz", "AI请求开始时间。", "运行时长。", example="2026-08-09T10:00:00+08:00"),
            F("completed_at", "结束时间", "timestamptz", "调用进入终态时间。", "识别卡住调用。", nullable=True, example="2026-08-09T10:00:08+08:00"),
            F("error_code", "错误代码", "text", "失败时机器可读错误。", "聚合排障。", nullable=True, example="PROVIDER_TIMEOUT"),
        ], standard="mutable", mutation_policy="CONTROLLED_UPDATE_UNTIL_TERMINAL", checks=("completed_at IS NULL OR completed_at >= started_at",),
        retention="脱敏正文按最短必要期限保留；结构化指标可长期保留",
    ),
]
